### ISSUE TITLE
Unable to use STARTTLS on Port 587

### ISSUE THREAD

**Issue by lfuelling** [openmediavault/openmediavault#536] opened 2019-12-17 20:26 UTC
### Description of issue/question

I use STARTTLS on port 587 on my mailserver and according to [this forum post](https://forum.openmediavault.org/index.php/Thread/22876-BUG-SSL-TLS-settings-from-notification-menu-are-incorrectly-named-used/?postID=174911#post174911) openmediavault uses the port number to "automatically" determine what to use. 
 
This leads to SSL errors in openmediavault because it "automatically" tries to use SSL. :roll_eyes: 

### Steps to reproduce issue
1. Create mail server with STARTTLS on port 587
2. Try to connect it to openmediavault
3. Check the logs for a message like the following:
`postfix/smtp[31228]: warning: TLS library problem: error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../ssl/record/ssl3_record.c:332:`

A quick Google search will reveal that this message seems to appear when trying to do SSL with something that is not SSL.

### Versions report
5.1.3-1 (Usul)

ps: It's a real pain to excavate the log message with the devtools on a page that's constantly refreshing. Why is there a prevention to copy stuff in the logs? :eyes:

**Comment by lfuelling** [comment] 2019-12-17 20:28
I have to add that I also tried changing the postfix config manually. But every time I change something in the WebUI, the config file is reverted and my customization is lost.

**Comment by ryecoaaron** [comment] 2019-12-17 20:57
Can’t help with the tls error but the copy prevention is part of the extjs framework (I think). The config changing back is the whole concept of OMV. It completely owns the config files.

**Comment by lfuelling** [comment] 2019-12-17 21:39
The solution to the error probably would be adding a way to explicitly switch between SSL and STARTTLS in the Mailserver config.

**Comment by votdev** [comment] 2019-12-17 21:49
Wrap mode is auto-activated for port 465.

**Comment by votdev** [comment] 2019-12-17 21:50
> The solution to the error probably would be adding a way to explicitly switch between SSL and STARTTLS in the Mailserver config.

That does not fit the concept of OMV. Things are automatically done in the background to simplify things for novice users.

**Comment by votdev** [comment] 2019-12-17 21:52
> ps: It's a real pain to excavate the log message with the devtools on a page that's constantly refreshing. Why is there a prevention to copy stuff in the logs? eyes

That's a ExtJS behaviour and can't be changed.

**Comment by votdev** [comment] 2019-12-17 22:09
This is the [related PR](https://github.com/openmediavault/openmediavault/commit/d60175802fa77af295d8ee64221c1cfb09409220).

**Comment by votdev** [comment] 2019-12-17 22:10
I close this issue because i can't see any relation between the postfix config generated by OMV and 587.

**Comment by lfuelling** [comment] 2019-12-18 11:22
@votdev I am not using port 465 at all on my mail server. I am using port 587 with STARTTLS.

I am also unable to reopen the issue.

> That does not fit the concept of OMV. Things are automatically done in the background to simplify things for novice users.

This statement just destroyed all my interest in the software. Things are automatically done and there is no way to forcibly change this behavior, wtf...

**Comment by votdev** [comment] 2019-12-18 11:42
You can customize the behavior of OMV by overriding some environment variables, but this is limited because this is not how OMV works. I think Webmin is the software of your choice then.

**Comment by lfuelling** [comment] 2019-12-18 11:46
I think I will use plain debian.
The webinterface would have been nice but not if it's not properly configurable.

**Comment by votdev** [comment] 2019-12-18 12:20
After thinking about it might possibly make sense to add a config option for that. I do not like it because of the amount of changes this simple feature requires and it does not fit in the concept of OMV finally, but might help to get OMV working with non common setups.

**Comment by lfuelling** [comment] 2019-12-18 12:51
Sorry if I don't get something here but would replacing the "SSL" switch with a radio group with "No Encryption", "STARTTLS" and "SSL" would be that much of a hurdle?

**Comment by ryecoaaron** [comment] 2019-12-18 13:14
There are actually quite a few spots where code would have to change.  And you have to remember to convert old installs to the new schema.  You could always submit a pull request.

**Comment by lfuelling** [comment] 2019-12-18 13:26
Okay, will do. 
It would be nice if someone with proper access could reopen this issue and assign me.

**Comment by ryecoaaron** [comment] 2019-12-18 13:28
Sorry, I can't do that.  votdev is only one.

**Comment by lfuelling** [comment] 2019-12-18 13:47
>  And you have to remember to convert old installs to the new schema.

Is that "conversion" done with some kind of migration script? 
I can't find anything looking like this in this repo...

**Comment by ryecoaaron** [comment] 2019-12-18 13:51
Migration scripts are here - https://github.com/openmediavault/openmediavault/tree/master/deb/openmediavault/usr/share/openmediavault/confdb/migrations.d

**Comment by lfuelling** [comment] 2019-12-18 14:00
Okay, as far as I understood the migration code there also has to be a migration when adding new config values. 

I am unable too find any postfix configuration options in the migrations, does that mean that those config options do not require a migration?

**Comment by votdev** [comment] 2019-12-18 15:21
Please don't touch the translation files.

**Comment by lfuelling** [comment] 2019-12-18 15:21
Why?

**Comment by votdev** [comment] 2019-12-18 15:22
Because they are extracted in a later process.

**Closed** 2019-12-18 20:58 UTC
Labels: 5.x

**Comment by votdev** [comment] 2020-01-02 08:03
@lfuelling Any ideas about https://github.com/openmediavault/openmediavault/issues/551?

**Comment by JoshuaLyle** [comment] 2020-01-02 19:36
> @lfuelling Any ideas about #551?

https://github.com/openmediavault/openmediavault/blob/89cb095280cd43074998df3e56abfce80425376a/deb/openmediavault/srv/salt/omv/deploy/postfix/files/main.cf.j2#L41

It looks like the issue is here. The first conditional...
`config.tls == 'starttls'`
should reference the SSL/TLS
`config.tls == 'ssl'`

That's because the setting that this statement enables...
`smtp_tls_wrappermode = yes`
is only appropriate for SMTPS on port 465, not STARTTLS on port 587.

**Comment by lfuelling** [comment] 2020-01-06 15:20
Oh so I got it wrong. I read it as the `smtp_tls_wrappermode` setting toggles STARTTLS. :man_facepalming: 

@votdev shall I create a PR?

**Comment by votdev** [comment] 2020-01-07 08:34
> Oh so I got it wrong. I read it as the `smtp_tls_wrappermode` setting toggles STARTTLS. man_facepalming
> 
> @votdev shall I create a PR?

No, that's not necessary.

**Comment by TheFryingPI** [comment] 2021-01-17 17:32
I hope that the code will be freed of port 465, the official port is 587...

**Comment by votdev** [comment] 2021-01-17 18:20
> I hope that the code will be freed of port 465, the official port is 587...

According to IANA port 465 is defined for implicit TLS.

**Comment by TheFryingPI** [comment] 2021-01-17 19:17
sorry, but this is so important to know, so here you are, I recommend you try to be open for changes i mean it in a positive way, no one can do everything alone, just be open minded.

What about port 465?

Interestingly, port 465 was never published as an official SMTP transmission or submission channel by the IETF. Instead, the Internet Assigned Numbers Authority (IANA), who maintains much of the core internet infrastructure, registered port 465 for SMTPS. The purpose was to establish a port for SMTP to operate using Secure Sockets Layer (SSL). SSL is commonly used for encrypting communications over the internet.

The port was assigned for about one year when it was revoked in support of securing SMTP communications using Transport Layer Security (TLS). The nail in the coffin was a new protocol command "STARTTLS," introduced in RFC 2487. This command allows SMTP servers to communicate over existing ports by advertising whether the destination server supports TLS encryption. If so, the sending server can upgrade the connection using the "STARTTLS" SMTP command.

Port 465:

IANA has reassigned a new service to this port, and it should no longer be used for SMTP communications.

However, because it was once recognized by IANA as valid, there may be legacy systems that are only capable of using this connection method. Typically, you will use this port only if your application demands it. A quick Google search, and you'll find many consumer Inbox Service Providers' (ISPs) articles that suggest port 465 as the recommended setup. However, we do not recommend it, as it is not RFC compliant.
Port 587:

This is the default mail submission port. When an email client or outgoing server is submitting an email to be routed by a proper mail server, it should always use SMTP port 587 as the default port.

This port, coupled with TLS encryption, will ensure that email is submitted securely and following the guidelines set out by the IETF.

**Comment by TheFryingPI** [comment] 2021-01-17 19:19
http://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.txt

urd                 465        tcp    URL Rendezvous Directory for [Toerless_Eckert]                                     [Toerless_Eckert]
                                      SSM
submissions         465        tcp    Message Submission over TLS  [IESG]                                                [IETF_Chair]                                              2017-12-12                [RFC8314]
                                      protocol
igmpv3lite          465        udp    IGMP over UDP for SSM        [Toerless_Eckert]                                     [Toerless_Eckert]

**Comment by votdev** [comment] 2021-01-17 19:47
@TheFryingPI Could you please explain what the exact problem is with the code? The line `(config.tls == 'auto' and config.port == 465)` is for backward compatibility.

**Comment by TheFryingPI** [comment] 2021-01-17 20:01
I think you mentioned somewhere: That does not fit the concept of OMV. Things are automatically done in the background to simplify things for novice users. First, why you expect ALL users are novice? Secondly, if I was a novice I would hope the ones who code are doing the right thing, since your the only one who can change code.... as mentioned, that's why I took the time to respond and explain. I leave it up to you. I like your work [OMV] don't get me wrong.

**Comment by votdev** [comment] 2021-01-17 20:22
> First, why you expect ALL users are novice? 

I don't expect all users to be novice, but the concept of OMV is NOT to provide the ability to configure everything that's possible to the user. If that is your requirement, then OMV is the wrong solution for you. The concept of OMV is to provide a simplified way to configure common workflows for the user. 

> as mentioned, that's why I took the time to respond and explain.

You still do not explain what is wrong, you only quote RFCs and other documentation. You never explained why this is incorrect and how to make it better.
As far as i remember setting `smtp_tls_wrappermode` for port 465 was a user request to get GMail working. Sadly the is no GitHub issue for that, but you will surely find the related post in the forum if you want.

Provide a suggestion how to fix the issue without breaking user installations, than we can start discussion. Opening a PR with your code improvements will be the best way to do so.

**Comment by ryecoaaron** [comment] 2021-01-17 20:33
https://github.com/openmediavault/openmediavault/issues/536

**Comment by JoshuaLyle** [comment] 2021-01-17 23:57
[In RFC8314, it notes that port 465 is a de facto standard used for email submission with implicit TLS](https://tools.ietf.org/html/rfc8314#section-7.3). If a major mail server like Postfix supports port 465 TLS submissions via `smtp_tls_wrappermode` and a mail service as big as Gmail supports port 465 TLS submission then I don't see how its inclusion in OMV hurts anything. It provides the opportunity for (not so) edge cases to work correctly at no cost.

**Comment by TheFryingPI** [comment] 2021-01-18 09:57
Sure, and I bet many still use XP and Windows 7, feel free to keep using that port number :-) 
Not sure what the problem is with you guys I only mentioned that port  465 should no longer be used for that purpose.
Then IANA got mentioned,  Just my 2ct. I don't want to waste more time on this... :-)
