### ISSUE TITLE
Monit Error and Socket 2812 when hitting apply

### ISSUE THREAD

**Issue by vepicurean** [openmediavault/openmediavault#464] opened 2019-10-12 07:22 UTC
Reopening issue regarding MONIT error and Socket 2812. Brand new Openmediavault install can not add or remove shares or even update the system because of constant MONIT error. The entire system is basically unusable while this error is present.  

There are no documented correct steps to fix the problem with MONIT applied to Openmediavault, though the issue has been present with the implementation of how Openmediavault is using MONIT for a long time. 

Important to read this thread with the history of the background that was closed without having a proven fix procedure for the issue with regards to the implementation of MONIT within Openmediavault

https://github.com/openmediavault/openmediavault/issues/435

The correct documented steps anyone has to resolve this known issue as applied to Openmediavault would be appreciated.

**Comment by vepicurean** [comment] 2019-10-20 09:42
Does anyone have to steps to fix this issue with MONIT in Openmediavault? I can't do anything with the platform.  Everytime I hit apply, this error comes up, and I have to revert the changes.  Please see attached. 

Other's have run into this before, but no one explains the actual correct steps to fix the issue. 

![monit_error_openmediavault_trying_to_delete_share](https://user-images.githubusercontent.com/5864428/67157600-5566ed80-f2fc-11e9-8068-d661415b9bee.PNG)

**Comment by vepicurean** [comment] 2019-10-20 11:28
I'm just guessing if the issue centers around MONIT and how it's used by Openmediavault, but others that have encountered this issue mention it has something to do with the version of MONIT used. Apparently the fix for this is not implemented in MONIT 5.20. 0. 

It's not clear (detailed explanations are hard to find), and I don't know for sure, but one person mentioned the fix was implemented in MONIT 5.21.0.

https://mmonit.com/monit/changes/
   
I notice the version of MONIT used (5.20.0) was first released in 2016. MONIT is now up to version 5.26.0, and there's been a several important fixes it seems. But again, I'm just guessing. It's not a program I am familiar with (just from my research trying to fix this issue with Openmediavault and MONIT). Not sure why the version of MONIT used is so old. 

If someone that knows this situation well, has some scientific method based information, it would be appreciated.

**Comment by vepicurean** [comment] 2019-10-30 07:04
Is there is no proven fix for this major issue/bug with OpenMediaVault, then can the developer/project lead(s) confirm that fact, please. That way I can decide what to do. 

Thanks.

**Comment by votdev** [comment] 2019-10-30 07:23
In OMV5 monit is on 5.26.0. As often told, OMV does not and can't fix or maintain packages from upstream. You can try to build the package yourself on OMV4 and give it a try. If it fixes the problem, then we can see what to do.

**Comment by vepicurean** [comment] 2019-10-31 14:39
So I clearly understand going forward the OMV philosophy and approach to running this project. 

It seems that OMV has been operating with this known issue for a long time! And the philosophy seems to be the problem is completely OK with the developer/developers, and it's up to the users of the project to find individual fixes for themselves.  

I just want to make sure that's what I'm being told.  A simple "Yes" or "No" will suffice. Then I'll decide what to do. 

The people at Freenas warned right on their website that OMV was not a system that could be operated in a professional environment, and should only be used for personal use.  I thought they were exaggerating. 

Thanks for your help and time.

**Comment by votdev** [comment] 2019-10-31 14:45
You get what you pay for

**Comment by ryecoaaron** [comment] 2019-10-31 15:26
I just built the monit 5.26 package on OMV 4.x and uploaded the .deb.  It installed fine on my test system but I wasn't having any monit issues there.  Use at your own risk.

http://omv-extras.org/testing/monit_5.26.0-1_amd64.deb

**Comment by vepicurean** [comment] 2019-10-31 15:55
Thanks, but this is not a new issue.  Others have seen it before going back a long way. 

The first time I opened a ticket about it it was closed, and I had to re-open it. I should have mentioned FreeNAS before given this response this morning. 

Thanks for your help and time. Greatly appreciated.

**Comment by ryecoaaron** [comment] 2019-10-31 16:14
No, it may not be a new issue but I (and obviously Volker) have never been able to reproduce it.  How do you fix something when you can't reproduce it?  And as Volker said, it is a Debian bug not OMV.

Just to remind that I am not an OMV developer (just omv-extras plugins).  Volker is the only dev and can only do so much for a project that he works on in his free time.  I don't recommend bringing up FreeNAS comments to get things fixed in the future...

**Comment by vepicurean** [comment] 2019-10-31 20:14
Thank you all for your help and time. I know what I'm going to do now. Appreciated.

**Comment by mi-hol** [comment] 2020-12-16 17:51
4.x is EOL

**Closed by mi-hol** 2020-12-16 17:51 UTC
Labels: 4.x
