### ISSUE TITLE
OMV5 Nut Plugin monit Error

### ISSUE THREAD

**Issue by tmsd2001** [openmediavault/openmediavault#752] opened 2020-07-02 16:15 UTC
Raspberry Pi4 Kernel 4.19.118-v7l+
OMV 5.5.3-1 Usul
Diskstats 5.0.5-1
Nut 5.1.0-1

After installing the nut Plugin, I go to the UPS Config and activated it.
then the takeover no longer worked with these errors.

```
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; omv-salt deploy run monit 2>&1' with exit code '1': fileserver: ---------- ID: configure_monit_collectd_service Function: file.managed Name: /etc/monit/conf.d/openmediavault-collectd.conf Result: True Comment: File /etc/monit/conf.d/openmediavault-collectd.conf is in the correct state Started: 17:08:07.815805 Duration: 253.951 ms Changes: ---------- ID: configure_monit_filesystem_service Function: file.managed Name: /etc/monit/conf.d/openmediavault-filesystem.conf Result: True Comment: File /etc/monit/conf.d/openmediavault-filesystem.conf is in the correct state Started: 17:08:08.070379 Duration: 71.286 ms Changes: ---------- ID: configure_monit_nginx_service Function: file.managed Name: /etc/monit/conf.d/openmediavault-nginx.conf Result: True Comment: File /etc/monit/conf.d/openmediavault-nginx.conf is in the correct state Started: 17:08:08.142501 Duration: 50.487 ms Changes: ---------- ID: configure_monit_nut_service Function: file.managed Name: /etc/monit/conf.d/openmediavault-nut.conf Result: True Comment: File /etc/monit/conf.d/openmediavault-nut.conf updated Started: 17:08:08.193603 Duration: 79.24 ms Changes: ---------- diff: New file mode: 0644 ---------- ID: configure_monit_omv-engined_service Function: file.managed Name: /etc/monit/conf.d/openmediavault-engined.conf Result: True Comment: File /etc/monit/conf.d/openmediavault-engined.conf is in the correct state Started: 17:08:08.273603 Duration: 48.464 ms Changes: ---------- ID: configure_monit_php-fpm_service Function: file.managed Name: /etc/monit/conf.d/openmediavault-phpfpm.conf Result: True Comment: File /etc/monit/conf.d/openmediavault-phpfpm.conf is in the correct state Started: 17:08:08.322806 Duration: 54.586 ms Changes: ---------- ID: remove_monit_proftpd_service Function: file.absent Name: /etc/monit/conf.d/openmediavault-proftpd.conf Result: True Comment: File /etc/monit/conf.d/openmediavault-proftpd.conf is not present Started: 17:08:08.378159 Duration: 3.551 ms Changes: ---------- ID: configure_monit_rrdcached_service Function: file.managed Name: /etc/monit/conf.d/openmediavault-rrdcached.conf Result: True Comment: File /etc/monit/conf.d/openmediavault-rrdcached.conf is in the correct state Started: 17:08:08.382353 Duration: 77.255 ms Changes: ---------- ID: configure_monit_system_service Function: file.managed Name: /etc/monit/conf.d/openmediavault-system.conf Result: True Comment: File /etc/monit/conf.d/openmediavault-system.conf is in the correct state Started: 17:08:08.460289 Duration: 191.632 ms Changes: ---------- ID: configure_default_monit Function: file.managed Name: /etc/default/monit Result: True Comment: File /etc/default/monit is in the correct state Started: 17:08:08.652524 Duration: 30.075 ms Changes: ---------- ID: configure_monit_monitrc Function: file.managed Name: /etc/monit/monitrc Result: True Comment: File /etc/monit/monitrc is in the correct state Started: 17:08:08.683320 Duration: 161.476 ms Changes: ---------- ID: test_monit_config Function: cmd.run Name: monit -t Result: False Comment: Command "monit -t" run Started: 17:08:08.855563 Duration: 92.295 ms Changes: ---------- pid: 10865 retcode: 1 stderr: /etc/monit/conf.d/openmediavault-nut.conf:12: Program does not exist: '/usr/bin/upsc' /etc/monit/conf.d/openmediavault-nut.conf:12: Program does not exist: 'ups' /etc/monit/conf.d/openmediavault-nut.conf:14: Program does not exist: '/usr/sbin/upsdrvctl' AssertException: File '/usr/bin/upsc' does not exist raised in Command_new at src/system/Command.c:359 stdout: ---------- ID: reload_monit_service Function: service.running Name: monit Result: True Comment: Service reloaded Started: 17:08:09.280082 Duration: 281.823 ms Changes: ---------- monit: True Summary for fileserver ------------- Succeeded: 12 (changed=3) Failed: 1 ------------- Total states run: 13 Total run time: 1.396 s

Fehler #0:
OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; omv-salt deploy run monit 2>&1' with exit code '1': fileserver:
----------
          ID: configure_monit_collectd_service
    Function: file.managed
        Name: /etc/monit/conf.d/openmediavault-collectd.conf
      Result: True
     Comment: File /etc/monit/conf.d/openmediavault-collectd.conf is in the correct state
     Started: 17:08:07.815805
    Duration: 253.951 ms
     Changes:
----------
          ID: configure_monit_filesystem_service
    Function: file.managed
        Name: /etc/monit/conf.d/openmediavault-filesystem.conf
      Result: True
     Comment: File /etc/monit/conf.d/openmediavault-filesystem.conf is in the correct state
     Started: 17:08:08.070379
    Duration: 71.286 ms
     Changes:
----------
          ID: configure_monit_nginx_service
    Function: file.managed
        Name: /etc/monit/conf.d/openmediavault-nginx.conf
      Result: True
     Comment: File /etc/monit/conf.d/openmediavault-nginx.conf is in the correct state
     Started: 17:08:08.142501
    Duration: 50.487 ms
     Changes:
----------
          ID: configure_monit_nut_service
    Function: file.managed
        Name: /etc/monit/conf.d/openmediavault-nut.conf
      Result: True
     Comment: File /etc/monit/conf.d/openmediavault-nut.conf updated
     Started: 17:08:08.193603
    Duration: 79.24 ms
     Changes:
              ----------
              diff:
                  New file
              mode:
                  0644
----------
          ID: configure_monit_omv-engined_service
    Function: file.managed
        Name: /etc/monit/conf.d/openmediavault-engined.conf
      Result: True
     Comment: File /etc/monit/conf.d/openmediavault-engined.conf is in the correct state
     Started: 17:08:08.273603
    Duration: 48.464 ms
     Changes:
----------
          ID: configure_monit_php-fpm_service
    Function: file.managed
        Name: /etc/monit/conf.d/openmediavault-phpfpm.conf
      Result: True
     Comment: File /etc/monit/conf.d/openmediavault-phpfpm.conf is in the correct state
     Started: 17:08:08.322806
    Duration: 54.586 ms
     Changes:
----------
          ID: remove_monit_proftpd_service
    Function: file.absent
        Name: /etc/monit/conf.d/openmediavault-proftpd.conf
      Result: True
     Comment: File /etc/monit/conf.d/openmediavault-proftpd.conf is not present
     Started: 17:08:08.378159
    Duration: 3.551 ms
     Changes:
----------
          ID: configure_monit_rrdcached_service
    Function: file.managed
        Name: /etc/monit/conf.d/openmediavault-rrdcached.conf
      Result: True
     Comment: File /etc/monit/conf.d/openmediavault-rrdcached.conf is in the correct state
     Started: 17:08:08.382353
    Duration: 77.255 ms
     Changes:
----------
          ID: configure_monit_system_service
    Function: file.managed
        Name: /etc/monit/conf.d/openmediavault-system.conf
      Result: True
     Comment: File /etc/monit/conf.d/openmediavault-system.conf is in the correct state
     Started: 17:08:08.460289
    Duration: 191.632 ms
     Changes:
----------
          ID: configure_default_monit
    Function: file.managed
        Name: /etc/default/monit
      Result: True
     Comment: File /etc/default/monit is in the correct state
     Started: 17:08:08.652524
    Duration: 30.075 ms
     Changes:
----------
          ID: configure_monit_monitrc
    Function: file.managed
        Name: /etc/monit/monitrc
      Result: True
     Comment: File /etc/monit/monitrc is in the correct state
     Started: 17:08:08.683320
    Duration: 161.476 ms
     Changes:
----------
          ID: test_monit_config
    Function: cmd.run
        Name: monit -t
      Result: False
     Comment: Command "monit -t" run
     Started: 17:08:08.855563
    Duration: 92.295 ms
     Changes:
              ----------
              pid:
                  10865
              retcode:
                  1
              stderr:
                  /etc/monit/conf.d/openmediavault-nut.conf:12: Program does not exist: '/usr/bin/upsc'
                  /etc/monit/conf.d/openmediavault-nut.conf:12: Program does not exist: 'ups'
                  /etc/monit/conf.d/openmediavault-nut.conf:14: Program does not exist: '/usr/sbin/upsdrvctl'
                  AssertException: File '/usr/bin/upsc' does not exist
                   raised in Command_new at src/system/Command.c:359
              stdout:
----------
          ID: reload_monit_service
    Function: service.running
        Name: monit
      Result: True
     Comment: Service reloaded
     Started: 17:08:09.280082
    Duration: 281.823 ms
     Changes:
              ----------
              monit:
                  True

Summary for fileserver
-------------
Succeeded: 12 (changed=3)
Failed:     1
-------------
Total states run:     13
Total run time:    1.396 s in /usr/share/php/openmediavault/system/process.inc:182
Stack trace:
#0 /usr/share/php/openmediavault/engine/module/serviceabstract.inc(60): OMV\System\Process->execute()
#1 /usr/share/openmediavault/engined/rpc/config.inc(167): OMV\Engine\Module\ServiceAbstract->deploy()
#2 [internal function]: Engined\Rpc\Config->applyChanges(Array, Array)
#3 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#4 /usr/share/php/openmediavault/rpc/serviceabstract.inc(149): OMV\Rpc\ServiceAbstract->callMethod('applyChanges', Array, Array)
#5 /usr/share/php/openmediavault/rpc/serviceabstract.inc(588): OMV\Rpc\ServiceAbstract->OMV\Rpc\{closure}('/tmp/bgstatusty...', '/tmp/bgoutputjh...')
#6 /usr/share/php/openmediavault/rpc/serviceabstract.inc(159): OMV\Rpc\ServiceAbstract->execBgProc(Object(Closure))
#7 /usr/share/openmediavault/engined/rpc/config.inc(189): OMV\Rpc\ServiceAbstract->callMethodBg('applyChanges', Array, Array)
#8 [internal function]: Engined\Rpc\Config->applyChangesBg(Array, Array)
#9 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#10 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('applyChangesBg', Array, Array)
#11 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('Config', 'applyChangesBg', Array, Array, 1)
#12 {main}
```

**Comment by votdev** [comment] 2020-07-02 17:19
The problem occurs if you manually update Debian 9 to 10 without running `/usr/lib/convert-usrmerge` or the creators of your RPi image didn't do that.

See also
* https://freedesktop.org/wiki/Software/systemd/TheCaseForTheUsrMerge.
* https://forum.openmediavault.org/index.php?thread/31458-unable-to-use-network-ups-tools-to-monitor-my-ups/&postID=232564#post232564.

Duplicate of https://github.com/openmediavault/openmediavault/pull/632, https://github.com/openmediavault/openmediavault/issues/648 and https://github.com/openmediavault/openmediavault/pull/750.

**Closed by votdev** 2020-07-02 17:19 UTC

**Comment by votdev** [comment] 2020-07-02 17:21
An alternative problem might be that the `nut` package has not been installed correctly. You might check that running `dpkg -l | grep nut`.
