### ISSUE TITLE
setting up encrypted disks did not work from within OMV - kernel hangs on mount

### ISSUE THREAD

**Issue by DEvil0000** [openmediavault/openmediavault#495] opened 2019-11-06 16:20 UTC
### Description of issue/question
encrypted xfs volumes hang the kernel on mount (aka do not work).
this was observed about 5 month ago (around 2019-06-12) and may be solved now.

### Steps to reproduce issue
* install OMV from image
* install 4.19 kernel
* install LUKS plugin
* created raid 6
* created LUKS
* created xfs
* mount -> failed/kernel thread hangs

### other Steps to reproduce issue
* install debian the normal way (just os partition configured not the raid disks - maybe without LVM)
* install kernel
* configure ppa/sources list for OMV
* install OMV from packages
* rest of the steps as above

### Steps to work around the issue - **works for me**
* install debian the normal way but this time with everything disk related configured in the setup (system partitions plus raid disks including enc and just everything)
* install kernel
* configure ppa/sources list for OMV
* install OMV from packages
* rest of the steps as above

### Versions report
stretch/9.11
kernel 4.19 (needed to support the hardware: gigabit ports on a supermicro atom board)
arrakis at around (2019-06-12), current package version: 4.1.26-1

**Comment by votdev** [comment] 2019-11-06 20:03
I'll close this issue because if it is a kernel problem then the OMV project can not do anything because we do not maintain kernel packages. These are consumed from the upstream Debian project.

If you think it's caused by the plugin, please open a bugreport [here](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-luksencryption).

**Closed by votdev** 2019-11-06 20:03 UTC
Labels: 4.x, omv-extras.org, upstream issue
