### ISSUE TITLE
SMB Share Performance very Bad on Raspberry Pi 4 Model B 8 GB

### ISSUE THREAD

**Issue by xMisterW** [openmediavault/openmediavault#1803] opened 2024-07-29 09:09 UTC
I tried everything.

Connection via Cable i only get the Write to the Network Share faster but Reading still stays at 30-45 mbps and is slower than writing on the network share:

i tried the things here too https://github.com/raspberrypi/linux/issues/4133

**Comment by xMisterW** [comment] 2024-07-29 10:58
I tried different thins.



Raspbi OS bullseye and omv 6



On both Versions:



this:



[for anyone having slow smb/cifs check here : r/OpenMediaVault (reddit.com)](https://www.reddit.com/r/OpenMediaVault/comments/vdtogs/for_anyone_having_slow_smbcifs_check_here/)



and this:



[Extreme slow Network transfer speed - Argon 40 Forum & Community](https://forum.argon40.com/t/extreme-slow-network-transfer-speed/620/18)



1 gbit LAN is activated hdparm is good. Exe Data with 500 mb is with good transfer but bigger mkv data gets slower and only reads with round abotu 40-45 mbps



EDIT:



i did read from a Linux Kernel problem with Raspberry Pi 4 above kernel 5.48 so can i get somewhere a rasbpi OS and OMV Version with this kernels below?

On PC the HDD gets with the same files 140 mbps read and write.

So is the Problem the Raspberry Pi 4 ?

i wanted to use the network share for Media Files mkvs and so for kodi

**Comment by votdev** [comment] 2024-07-30 07:26
> So is the Problem the Raspberry Pi 4 ?

Sure it IS the problem, what do you expect?

**Comment by votdev** [comment] 2024-07-30 07:26
Closing this issue because the problem is related to the hardware.

**Closed by votdev** 2024-07-30 07:26 UTC
