### ISSUE TITLE
plugin conflict openmediavault-lvm2 7.0-2/openmediavault-md 7.0-6

### ISSUE THREAD

**Issue by lcoolerl** [openmediavault/openmediavault#1718] opened 2024-03-05 13:38 UTC
Installed OMV7 on hdd, plugins 
openmediavault-diskstats 7.0-2
openmediavault-s3 7.0-3
install openmediavault-lvm2 7.0-2 => OMV request reboot
install openmediavault-md 7.0-6 => open MultipleDevice (Error)
reboot didn't help
uninstal openmediavault-lvm2 7.0-2 => ok

Версия
7.0-32 (Sandworm)
Ядро
Linux 6.1.0-18-amd64
Процессор
AMD Athlon(tm) 64 X2 Dual Core Processor 4600+

Chrome 122.0.6261.95 64bit

**Comment by votdev** [comment] 2024-03-05 20:13
Because i can only guess what you are talking about, i'm showing that the installation of the plugins is working:
```
# apt-get install openmediavault-lvm2 openmediavault-md
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  openmediavault-lvm2 openmediavault-md
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 42.2 kB of archives.
After this operation, 441 kB of additional disk space will be used.
Get:1 http://packages.openmediavault.org/public sandworm/main amd64 openmediavault-lvm2 all 7.0-2 [25.4 kB]
Get:2 http://packages.openmediavault.org/public sandworm/main amd64 openmediavault-md all 7.0-6 [16.8 kB]
Fetched 42.2 kB in 0s (364 kB/s)        
Selecting previously unselected package openmediavault-lvm2.
(Reading database ... 40551 files and directories currently installed.)
Preparing to unpack .../openmediavault-lvm2_7.0-2_all.deb ...
Unpacking openmediavault-lvm2 (7.0-2) ...
Selecting previously unselected package openmediavault-md.
Preparing to unpack .../openmediavault-md_7.0-6_all.deb ...
Unpacking openmediavault-md (7.0-6) ...
Setting up openmediavault-md (7.0-6) ...
Append notification configuration ...
Setting up openmediavault-lvm2 (7.0-2) ...
Processing triggers for openmediavault (7.0-32) ...
Updating workbench configuration files ...
Restarting engine daemon ...
```

If you are talking about problems showing the pages in the UI, simply clear the browser cache. After that the problem should be solved.

**Comment by lcoolerl** [comment] 2024-03-06 00:39
after installing the plugins in the specified sequence and going to the Multiple Device tab (which appears after installing openmediavault-md 7.0-6), an error is displayed (I didn’t save the name of the erro)
deleted openmediavault-lvm2 7.0-2, now the plugin openmediavault-md 7.0-6 works fine
now when I try to install openmediavault-lvm2 7.0-2 falls out "500 - Internal Server Error
Failed to read from socket:"

**Comment by ryecoaaron** [comment] 2024-03-06 01:40
hit ctrl-shift-R. the 500 error isnt really an error. it happens sometimes when omv’s engined is restarted.

**Comment by votdev** [comment] 2024-03-06 07:20
> an error is displayed (I didn't save the error name)

But this is important to understand what is going wrong and how to help you.

Based on our experiences your issue is not a bug. Simply clear the browser cache and you are fine.

**Comment by votdev** [comment] 2024-03-06 07:21
I'm closing this issue because a simple browser cache refresh should fix the issue.
Please reopen if it is a different problem.

**Closed by votdev** 2024-03-06 07:21 UTC
Labels: bug, 7.x
