### ISSUE TITLE
Storage > File Systems causes Pi to reboot

### ISSUE THREAD

**Issue by snow6oy** [openmediavault/openmediavault#840] opened 2020-11-06 17:37 UTC
### 
2 USB drives mounted fine and configured for SMB use with OMV. Then moved house and setup OMV on new network.
Now the disks are listed in the GUI but attempting to list File System cause the Pi to crash

```
pi@raspberrypi:~ $ cat /etc/fstab
proc            /proc           proc    defaults          0       0
PARTUUID=d1b4cc8f-01  /boot           vfat    defaults          0       2
PARTUUID=d1b4cc8f-02            /       ext4    noatime,nodiratime,defaults     0 1
# a swapfile is not a swap partition, no line here
#   use  dphys-swapfile swap[on|off]  for that
# >>> [openmediavault]

# <<< [openmediavault]

```
Why has OMV suddenly stopped seeing my data?

### Steps to reproduce issue
No new log entries for several weeks (should they rotate) either from GUI or syslog

### Versions report
```
pi@raspberrypi:~ $ uname -a
Linux raspberrypi 5.4.51-v7l+ #1333 SMP Mon Aug 10 16:51:40 BST 2020 armv7l GNU/Linux
```

Cannot find omv version in CLI or GUI just says "latest"

**Comment by votdev** [comment] 2020-11-06 18:17
Have you tried to populate the fstab file with `omv-salt deploy run fstab`?
What is the output of the following commands?
```
# blkid
# omv-confdbadm read --prettify conf.system.filesystem.mountpoint
```

Any useful information in `/var/log/syslog`?

**Comment by yllekz** [comment] 2020-11-07 02:58
I'm having somewhat similar symptoms, and they only showed up after updating to OMV 5.5.15-1 (Usul).

I can't load the File Systems page, but my Pi does not reboot. Instead, the UI will just sit and spin at "loading" on that page. Shares are up and working, but I'm worried that I'm experiencing this.

As a side note, my Dashboard is also throwing an RPC error when trying to load File System information, referring me to syslog but all I can really get out of it is this:

```
OMV\Rpc\Exception: Invalid RPC response. Please check the syslog for more information. in /usr/share/php/openmediavault/rpc/rpc.inc:187

Error #0:
OMV\Rpc\Exception: Invalid RPC response. Please check the syslog for more information. in /usr/share/php/openmediavault/rpc/rpc.inc:187
Stack trace:
#0 /usr/share/php/openmediavault/rpc/proxy/json.inc(97): OMV\Rpc\Rpc::call('FileSystemMgmt', 'enumerateFilesy...', Array, Array, 3)
#1 /var/www/openmediavault/rpc.php(45): OMV\Rpc\Proxy\Json->handle()
#2 {main}
```

**Comment by snow6oy** [comment] 2020-11-07 09:27
```
root@raspberrypi:/home/pi# blkid
/dev/mmcblk0p1: LABEL_FATBOOT="boot" LABEL="boot" UUID="4AD7-B4D5" TYPE="vfat" PARTUUID="d1b4cc8f-01"
/dev/mmcblk0p2: LABEL="rootfs" UUID="2887d26c-6ae7-449d-9701-c5a4018755b0" TYPE="ext4" PARTUUID="d1b4cc8f-02"
/dev/sda1: LABEL_FATBOOT="EFI" LABEL="EFI" UUID="67E3-17ED" TYPE="vfat" PARTLABEL="EFI System Partition" PARTUUID="d2838e43-d9b4-4a7f-b47e-cbc61c7d0a55"
/dev/sda2: UUID="0243b443-afa8-372d-b246-54b7f0fbb3f2" LABEL="Almacenar" TYPE="hfsplus" PARTUUID="8042f66d-db5d-48fc-b731-31c5809a8273"
/dev/sda3: LABEL="A2" UUID="32adeedf-7efb-47b2-8330-54186b176cf8" TYPE="ext4" PARTUUID="dd9312a6-060c-4ab7-a0ca-924eb8a63e1c"
/dev/mmcblk0: PTUUID="d1b4cc8f" PTTYPE="dos"
root@raspberrypi:/home/pi# omv-confdbadm read --prettify conf.system.filesystem.mountpoint
[]
```
I discovered why the log timestamps were out of wack
```
root@raspberrypi:/home/pi# timedatectl
               Local time: Sun 2020-10-25 13:58:24 CET
           Universal time: Sun 2020-10-25 12:58:24 UTC
                 RTC time: n/a
                Time zone: Europe/Madrid (CET, +0100)
System clock synchronized: no
              NTP service: inactive
          RTC in local TZ: no
```
And when trying to install NTP realised that my DNS was fried.
```
root@raspberrypi:/home/pi# cat /etc/resolv.conf
# No DNS servers known
```
I am still trying to work out how to correct these errors. Setting either of them manually either causes a crash or just fails

**Comment by snow6oy** [comment] 2020-11-07 09:32
I forgot to add this output
```
root@raspberrypi:/home/pi# omv-salt deploy run fstab
raspberrypi:
----------
          ID: append_fstab_entries
    Function: file.blockreplace
        Name: /etc/fstab
      Result: True
     Comment: No changes needed to be made
     Started: 14:05:13.660122
    Duration: 8.034 ms
     Changes:   

Summary for raspberrypi
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:   8.034 ms
```
The output of `cat /etc/fstab` after this is the same as posted earlier.

**Comment by votdev** [comment] 2020-11-08 09:20
> ```
> OMV\Rpc\Exception: Invalid RPC response. Please check the syslog for more information. in /usr/share/php/openmediavault/rpc/rpc.inc:187
> 
> Error #0:
> OMV\Rpc\Exception: Invalid RPC response. Please check the syslog for more information. in /usr/share/php/openmediavault/rpc/rpc.inc:187
> Stack trace:
> #0 /usr/share/php/openmediavault/rpc/proxy/json.inc(97): OMV\Rpc\Rpc::call('FileSystemMgmt', 'enumerateFilesy...', Array, Array, 3)
> #1 /var/www/openmediavault/rpc.php(45): OMV\Rpc\Proxy\Json->handle()
> #2 {main}
> ```
Have you checked `/var/log/syslog` for detailed information as suggested in the error message?

**Comment by votdev** [comment] 2020-11-08 09:41
Does running `update-initramfs -u` including a reboot of the system fix the issue?

**Comment by snow6oy** [comment] 2020-11-08 18:00
Update: the empty resolv.conf was a side-effect of setting a static IP address. What I learnt was that in the GUI you have to tab past the IPv6 settings to the Advanced section (scrolling is broken in the pop-up windows). Adding a nameserver in the Advanced section fixed the date/time problem.

**Comment by mi-hol** [comment] 2020-12-15 17:15
@snow6oy could you please attach screenshots of the issues you mentioned above?
1) 'Cannot find omv version in CLI or GUI just says "latest"  => Menu Diagnostics/Dashboard contains usually the OMV version, expected is "5.5.17-3"
2) 'scrolling is broken in the pop-up windows' => works on my RPi
3) is 'uname -a' still reporting "raspberrypi 5.4.51-v7l+"?

**Comment by votdev** [comment] 2020-12-15 18:03
The current version can be retrieved via `dpkg -l | grep openmediavault`.

**Comment by snow6oy** [comment] 2020-12-16 21:38
![image](https://user-images.githubusercontent.com/4960142/102408775-0262f600-3fe6-11eb-8a4f-7ecf376299b0.png)

There is no way to grab the scroll bar on the pop-up window. I am using firefox on ubuntu.
https://www.mozilla.org/en-US/firefox/84.0/releasenotes/

Version from the Dashboard shows 5.5.9-1
I hadn't realised that this text was referring to OMV, maybe because it is within the pi context.

**Comment by mi-hol** [comment] 2020-12-16 21:45
@snow6oy would you mind to answer the 3 questions I asked?

**Comment by mi-hol** [comment] 2020-12-16 21:53
Please close issue if the only remaining issue is 'scrolling is broken in the pop-up windows' when using Firefox browser 84.

**Comment by votdev** [comment] 2020-12-17 14:57
> Please close issue if the only remaining issue is 'scrolling is broken in the pop-up windows' when using Firefox browser 84.

The issue occurs since a long time and is caused by something in ExtJS that i can not fix and won't be fixed by Sencha because they have stopped supporting the GPL version.

**Closed by votdev** 2020-12-17 14:57 UTC
Labels: 5.x
