### ISSUE TITLE
Mount by UUID destroys unoffical Plugin configurations

### ISSUE THREAD

**Issue by dgalli1** [openmediavault/openmediavault#908] opened 2020-12-31 14:57 UTC
**Describe the bug**
The drives now get mounted via uuid once again, which is fine i guess. (Even though i really think this is a inverior solution then the label usage).
Changes happend here: https://github.com/openmediavault/openmediavault/pull/897/commits/7dd25dd1167ee0fdb070734911c94ef3e4825a2c#diff-4a8c807b06e0e1296562764807fce7bbf6cd3df600db97d3cc7e2af895a47419

This change destroyed the unoffical Snapraid & Mergerfs Plugins configurations and everything else that access the raw paths and not a share. 

I really don't think major behavior changes should occur in minor versions.

**Expected behavior**
Stay on the old behavior for existing drives, and make the behavior configurable. Its preferable  to mount by labels for example for Snapraid so that replacing a bad drive can be done without touching the config files.
So i would suggest that we make this configurable or just stay on the mount by label default behavior. And use mount by uuid just if it fails to mount by label.

**Comment by votdev** [comment] 2020-12-31 16:06
Without this fix and using /dev/disk/by-uuid device files RasPi users with external enclosures can't use all drives because of a bug in their enclosure chipset. I am sorry about the unexpected behaviour of the code improvements. Currently I have no idea how to solve that, but using the uuid device type is currently the only solution to fix the JMicron issue. IMO the unofficial plugins need to be adapted to handle all types of device files. Limiting the core implementation seems not the right way.

**Comment by votdev** [comment] 2020-12-31 16:18
We need to find a way to get the snapraid plug-in working again without undoing the changes and cut-off Users with external enclosures from using all their plugged drives.

How is it possible that existing configuration are affected by this code change? The device file of mounted file systems only change when you unmount them and mount them again. Only in this case the backend decides to use the uuid device file in favour of the /dev/disk/by-id ones.

**Comment by votdev** [comment] 2020-12-31 16:27
I don't know how the snapraid plugin is implemented, but when it uses the openmediavault PHP filesystem backend infrastructure, then it can simply override the [getPredictableDeviceFile](https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/usr/share/php/openmediavault/system/filesystem/filesysteminterface.inc#L124) as it is done by the [BTRFS filesystem](https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/usr/share/php/openmediavault/system/filesystem/btrfs.inc#L97) for example which also does not like `/dev/disk/by-uuid` device files.

**Comment by dgalli1** [comment] 2020-12-31 16:34
First off sorry if i sounded rude, i was kinda mad previously because i didn't plan to use my day off for bug hunting ;)

> We need to find a way to get the snapraid plug-in working again without undoing the changes and cut-off Users with external enclosures from using all their plugged drives.
Its not like its not working without the update, it's a real edge case to be honest. I had to replace one of my parity drives because it failed. So normally i just remove the old drive and add a new one with the same label and sync the array. Now i have to edit the snapraid config aswell which was just unexpected, and i was looking everywhere to what i missed that it mounts via uuid. 


> How is it possible that existing configuration are affected by this code change? The device file of mounted file systems only change when you unmount them and mount them again. Only in this case the backend decides to use the uuid device file in favour of the /dev/disk/by-id ones.

Sorry i might not been clear previously, it still works. It's just annoying and was an unexpected behavior.

> I don't know how the snapraid plugin is implemented, but when it uses the openmediavault PHP filesystem backend infrastructure, then it can simply override the getPredictableDeviceFile as it is done by the BTRFS filesystem for example which also does not like /dev/disk/by-uuid device files.

That might be an option, i will look into this. Although i still think it would be better to make the mountpoint configurable. (But this would probably be done against omv gui 6?)

What do i think about this should i go ahead and implement some checkboxes to prefer a certain mount path? (With a hint about the raspberry pi issue)

**Comment by votdev** [comment] 2020-12-31 16:56
> (But this would probably be done against omv gui 6?)

This will never happen, because this will break the concept of openmediavault which is to keep is simple. If it is necessary to configure the mount point, then this mut happen under the hood by a plugin or the backend. openmediavault is no webmin or FreeNAS where you can do that, it's a software that simplifies the workflow and hides the work to be done under the hood.

**Comment by ryecoaaron** [comment] 2020-12-31 17:07
Unfortunately, any change to how the snapraid plugin determines the filesystem device/path will probably break some snapraid configs if a plugin update is installed.

**Comment by dgalli1** [comment] 2020-12-31 17:22
> Unfortunately, any change to how the snapraid plugin determines the filesystem device/path will probably break some snapraid configs if a plugin update is installed.

Well yes but the core already changed something, so it would essentaly be a rolleback. But of course it shouldn't be necessary to make the plugin unusable for raspberry pi users.

> This will never happen, because this will break the concept of openmediavault which is to keep it simple. If it is necessary to configure the mount point, then this must happen under the hood by a plugin or the backend. openmediavault is no webmin or FreeNAS where you can do that, it's a software that simplifies the workflow and hides the work to be done under the hood. The ability to customize things is reduced to the minimum by design and concept.

Alright but if we go with this philosophy stuff like the time server configuration should be removed aswell...
Honestly i don't see how it gets more difficult if you would just put a button above the Filesystems named "Advanced Options" or something and their you could handle mount options and everything. In fact i believe it gets more difficult if somebody has to drop to the console, to do easy jobs that could be done easily via a gui option. Their is no reason to look at advanced options aslong as it just works.

> Currently I have no idea how to solve that, but using the /dev/disk/by-uuid device file type is currently the only solution to fix the JMicron issue

Is it impossible to determine if a JMicron thing is used? I rather have a ugly device specific rule in the code then breaking existing installation.

**Comment by votdev** [comment] 2020-12-31 17:46
> Alright but if we go with this philosophy stuff like the time server configuration should be removed aswell... 

This is something really different. I never saw that a system auto-detects timeserver in SOHO environments.

> Honestly i don't see how it gets more difficult if you would just put a button above the Filesystems named "Advanced Options" or something and their you could handle mount options and everything.

I'm sorry, this will not happen. Such things make it more complicated than it helps. If a system has specific rules, everyone, incl. plugins, must follow them which will reduce failure and maintenance. I don't think we need to discuss about the design and concept of openmediavault here.

**Comment by ryecoaaron** [comment] 2020-12-31 17:46
The OMV change doesn’t break existing snapraid configs unless you have to add a new drive because existing drive paths dont change.  Changing the snapraid plugin would change the config on installation.  And this isn’t just about Rpi users. It affects any system using the jmicron controllers.

**Comment by mi-hol** [comment] 2021-01-06 17:25
closing due do statement "OMV change doesn’t break existing snapraid configs"

**Closed by mi-hol** 2021-01-06 17:25 UTC
Labels: 5.x affected
