### ISSUE TITLE
NUT plugin won't shutdown the system on low battery

### ISSUE THREAD

**Issue by pepalogik** [openmediavault/openmediavault#736] opened 2020-06-09 12:48 UTC
I am using OMV 4.1.35-1 (Arrakis) and have installed the NUT plugin, v. 4.0.13-1. I have activated it, so I can, e.g., see all the UPS status information.

I am new to NUT, and the NUT configuration in the OMV web interface is not very descriptive nor detailed. Thus I wanted to find out how exactly OMV has configured NUT. I have finally arrived at file `/etc/nut/upssched.conf`, and it seems to be incorrect.

If I select in the interface shutdown on low battery, then the file content is:
```
CMDSCRIPT /usr/bin/upssched-cmd
PIPEFN /var/run/nut/upssched.pipe
LOCKFN /var/run/nut/upssched.lock
AT COMMOK * EXECUTE notify
AT COMMBAD * EXECUTE notify
AT REPLBATT * EXECUTE notify
AT NOCOMM * EXECUTE notify
AT FSD * EXECUTE forced-shutdown
AT NOPARENT * EXECUTE notify
AT SHUTDOWN * EXECUTE notify
AT ONLINE * EXECUTE notify
AT ONBATT * EXECUTE notify
AT LOWBATT * EXECUTE notify
```
As far as I can understand it, this will only issue a notification but not shutdown the system if the battery is low.

If in the interface I select the default, i.e., shutdown 30 s after UPS goes on battery, then `/etc/nut/upssched.conf` contains:
```
CMDSCRIPT /usr/bin/upssched-cmd
PIPEFN /var/run/nut/upssched.pipe
LOCKFN /var/run/nut/upssched.lock
AT COMMOK * EXECUTE notify
AT COMMBAD * EXECUTE notify
AT REPLBATT * EXECUTE notify
AT NOCOMM * EXECUTE notify
AT FSD * EXECUTE forced-shutdown
AT NOPARENT * EXECUTE notify
AT SHUTDOWN * EXECUTE notify
AT ONLINE * CANCEL-TIMER shutdown
AT ONLINE * EXECUTE resume
AT ONBATT * START-TIMER shutdown 30
AT ONBATT * EXECUTE shutdown-warning
AT LOWBATT * START-TIMER shutdown
AT LOWBATT * EXECUTE shutdown-warning
```
This looks more functional, but still not quite correct. According to the [NUT documentation](https://networkupstools.org/docs/man/upssched.conf.html), the `START-TIMER` command requires two arguments, and so the last but one line is invalid (I suppose it should have `EXECUTE` rather than `START-TIMER`).

Are really both variants of the configuration file incorrect, or am I missing something? (I have not tested the configurations by disconnecting the UPS from power and waiting until the battery goes low.)

In addition, it would be nice to have alternatives to shutdown, such as sleep or hibernate.

**Comment by votdev** [comment] 2020-06-09 15:38
OMV4 is EOL in 14 days, please upgrade to OMV5.

**Comment by pepalogik** [comment] 2020-06-11 21:37
The upgrade involved plenty of problems, but I have finally done it. I now have OMV 5.5.2-1 (Usul) and NUT plugin 5.1.0-1.

The new versions of `/etc/nut/upssched.conf` differ only in details (comments, `PIPEFN`, and `LOCKFN`), and the problematic parts remain unchanged.

**Comment by kluvonog** [comment] 2020-06-15 16:30
Hi!
I think my problem not for this topic, but there is.

I have Intel Server Board S1200V3RPS and UPS Powercom RPT-1500AP.
OMV 5.3.9-1
NUT - 5.1.0-1

If I select "shutdown 30 s after UPS goes on battery", then PC goes poweroff, and then it goes startup - like reboot - and after boot - After loading, it repeats this sequence if the power was not connected to UPS.
But if I disconnect an usb-cable from UPS at the time of switching off PC, then the computer remains switched off.

**Comment by kluvonog** [comment] 2020-06-15 16:45
Problem is not in OMW or NUT.
I tested  Win10 - the same results.

**Comment by pepalogik** [comment] 2020-06-16 20:26
I have studied the NUT documentation, and it seems that NUT actually _will_ shut down the system on low battery, as described here: https://networkupstools.org/docs/user-manual.chunked/ar01s06.html#UPS_shutdown . (And it will also shut down the UPS.) This makes my bug report largely invalid. However, another question then arises: Why does `/etc/nut/upssched.conf` define special actions for the `FSD` and `LOWBATT` events (the latter only in the variant with the timer)?

**Comment by mi-hol** [comment] 2020-12-16 17:45
not caused by OMV so closing

**Closed by mi-hol** 2020-12-16 17:45 UTC
Labels: 4.x
