### ISSUE TITLE
5.x: error applying configuration

### ISSUE THREAD

**Issue by jjakob** [openmediavault/openmediavault#562] opened 2020-01-08 22:30 UTC
### Description of issue/question
Error applying configuration:
```
Error #0:
OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; omv-salt deploy run collectd 2>&1' with exit code '1': /usr/lib/python3/dist-packages/salt/utils/path.py:265: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  if not isinstance(exes, collections.Iterable):
gnubee.gnubee:
    Data failed to compile:
----------
    Rendering SLS 'base:omv.deploy.collectd.plugins.disk' failed: Problem running salt function in Jinja template: A valid link was not specified.; line 54

---
[...]
  {% if salt['mount.is_mounted'](mountpoint.dir) %}
    {% set parent_device_file = salt['omv_utils.get_fs_parent_device_file'](mountpoint.fsname) %}
    {% if parent_device_file %}
      # Get the canonical device file to extract the device name. The collectd disk
      # plugin wants this format: https://collectd.org/wiki/index.php/Plugin:Disk
      {% set canonical_parent_device_file = salt['file.readlink'](parent_device_file, True) %}    <======================
      # Extract the device name from '/dev/xxx'.
      {% set _ = disks.append(canonical_parent_device_file[5:]) %}
    {% endif %}
  {% endif %}
{% endfor %}
[...]
--- in /usr/share/php/openmediavault/system/process.inc:182
Stack trace:
#0 /usr/share/php/openmediavault/engine/module/serviceabstract.inc(60): OMV\System\Process->execute()
#1 /usr/share/openmediavault/engined/rpc/config.inc(167): OMV\Engine\Module\ServiceAbstract->deploy()
#2 [internal function]: Engined\Rpc\Config->applyChanges(Array, Array)
#3 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#4 /usr/share/php/openmediavault/rpc/serviceabstract.inc(149): OMV\Rpc\ServiceAbstract->callMethod('applyChanges', Array, Array)
#5 /usr/share/php/openmediavault/rpc/serviceabstract.inc(588): OMV\Rpc\ServiceAbstract->OMV\Rpc\{closure}('/tmp/bgstatus9e...', '/tmp/bgoutputzF...')
#6 /usr/share/php/openmediavault/rpc/serviceabstract.inc(159): OMV\Rpc\ServiceAbstract->execBgProc(Object(Closure))
#7 /usr/share/openmediavault/engined/rpc/config.inc(189): OMV\Rpc\ServiceAbstract->callMethodBg('applyChanges', Array, Array)
#8 [internal function]: Engined\Rpc\Config->applyChangesBg(Array, Array)
#9 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#10 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('applyChangesBg', Array, Array)
#11 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('Config', 'applyChangesBg', Array, Array, 1)
#12 {main}
```
### Steps to reproduce issue
Before this I tried to mount a filesystem, that apply failed due to mount error (missing kernel quota support), after recompiling the kernel and restarting the filesystem can now be mounted fine. After logging back in to the webgui and mounting the filesystem I clicked apply, this error was the result.

### Versions report
Openmediavault 5.2.2-1
Debian 10

**Comment by votdev** [comment] 2020-01-08 22:40
This looks like a duplicate of https://github.com/openmediavault/openmediavault/issues/554. Please make sure you have installed the latest [openmediavault-diskstats plugin](https://github.com/openmediavault/openmediavault/issues/554#issuecomment-571586080).

**Comment by votdev** [comment] 2020-01-08 22:41
According to the error message you do not have installed openmediavault-diskstats 5.0.3 which will fix this issue.

**Closed by votdev** 2020-01-08 22:41 UTC
Labels: 5.x, duplicate

**Comment by jjakob** [comment] 2020-01-08 23:16
Thank you, that was the issue.

**Comment by jjakob** [comment] 2020-01-09 00:47
New issue:
```
Error #0:
OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; omv-salt deploy run collectd 2>&1' with exit code '1': /usr/lib/python3/dist-packages/salt/utils/path.py:265: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  if not isinstance(exes, collections.Iterable):
gnubee.gnubee:
    Data failed to compile:
----------
    Rendering SLS 'base:omv.deploy.collectd.plugins.disk' failed: Jinja syntax error: no filter named 'is_device_file'; line 51

---
[...]
  #     "freq": 0,
  #     "fsname": "008530ff-a134-4264-898d-9ce30eeab927",
  # }
  {% if salt['mount.is_mounted'](mountpoint.dir) %}
    {% set parent_device_file = salt['omv_utils.get_fs_parent_device_file'](mountpoint.fsname) %}
    {% if parent_device_file | is_device_file %}    <======================
      # Get the canonical device file to extract the device name. The collectd disk
      # plugin wants this format: https://collectd.org/wiki/index.php/Plugin:Disk
      {% if parent_device_file | is_link %}
        {% set parent_device_file = salt['file.readlink'](parent_device_file, True) %}
      {% endif %}
[...]
--- in /usr/share/php/openmediavault/system/process.inc:182
Stack trace:
#0 /usr/share/php/openmediavault/engine/module/serviceabstract.inc(60): OMV\System\Process->execute()
#1 /usr/share/openmediavault/engined/rpc/config.inc(167): OMV\Engine\Module\ServiceAbstract->deploy()
#2 [internal function]: Engined\Rpc\Config->applyChanges(Array, Array)
#3 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#4 /usr/share/php/openmediavault/rpc/serviceabstract.inc(149): OMV\Rpc\ServiceAbstract->callMethod('applyChanges', Array, Array)
#5 /usr/share/php/openmediavault/rpc/serviceabstract.inc(588): OMV\Rpc\ServiceAbstract->OMV\Rpc\{closure}('/tmp/bgstatuslm...', '/tmp/bgoutputWN...')
#6 /usr/share/php/openmediavault/rpc/serviceabstract.inc(159): OMV\Rpc\ServiceAbstract->execBgProc(Object(Closure))
#7 /usr/share/openmediavault/engined/rpc/config.inc(189): OMV\Rpc\ServiceAbstract->callMethodBg('applyChanges', Array, Array)
#8 [internal function]: Engined\Rpc\Config->applyChangesBg(Array, Array)
#9 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#10 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('applyChangesBg', Array, Array)
#11 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('Config', 'applyChangesBg', Array, Array, 1)
#12 {main}
```

**Comment by votdev** [comment] 2020-01-09 07:51
You need to run `omv-salt stage run prepare` to fix that.

**Comment by jjakob** [comment] 2020-01-09 13:55
I ran this and it still fails in the same way. I select a filesystem, click mount, then it times out and shows an operation failed error in the gui, but the filesystem gets mounted. I then apply which fails with the above error.

I have these errors in the journal:
```
Jan 09 14:39:24 gnubee.gnubee systemd[1]: srv-dev\x2ddisk\x2dby\x2dlabel\x2dtest.mount: Succeeded.
Jan 09 14:39:35 gnubee.gnubee monit[1560]: Lookup for '/srv/dev-disk-by-label-test' filesystem failed  -- not found in /proc/self/mounts                                                                  
Jan 09 14:39:35 gnubee.gnubee monit[1560]: Filesystem '/srv/dev-disk-by-label-test' not mounted
Jan 09 14:39:35 gnubee.gnubee monit[1560]: 'filesystem_srv_dev-disk-by-label-test' unable to read filesystem '/srv/dev-disk-by-label-test' state                                                          
Jan 09 14:39:35 gnubee.gnubee monit[1560]: 'filesystem_srv_dev-disk-by-label-test' trying to restart
Jan 09 14:40:06 gnubee.gnubee monit[1560]: Filesystem '/srv/dev-disk-by-label-test' not mounted
Jan 09 14:40:06 gnubee.gnubee monit[1560]: 'filesystem_srv_dev-disk-by-label-test' unable to read filesystem '/srv/dev-disk-by-label-test' state                                                          
Jan 09 14:40:06 gnubee.gnubee monit[1560]: 'filesystem_srv_dev-disk-by-label-test' trying to restart
Jan 09 14:40:06 gnubee.gnubee monit[1560]: 'mountpoint_srv_dev-disk-by-label-test' status failed (1) -- mountpoint: /srv/dev-disk-by-label-test: No such file or directory                                
Jan 09 14:40:36 gnubee.gnubee smbd[1733]: [2020/01/09 14:40:36.402324,  2] ../source3/smbd/server.c:807(remove_child_pid)                                                                                 
Jan 09 14:40:36 gnubee.gnubee smbd[1733]:   Could not find child 2073 -- ignoring
Jan 09 14:40:37 gnubee.gnubee monit[1560]: Filesystem '/srv/dev-disk-by-label-test' not mounted
Jan 09 14:40:37 gnubee.gnubee monit[1560]: 'filesystem_srv_dev-disk-by-label-test' unable to read filesystem '/srv/dev-disk-by-label-test' state                                                          
Jan 09 14:40:37 gnubee.gnubee monit[1560]: 'filesystem_srv_dev-disk-by-label-test' trying to restart
Jan 09 14:40:37 gnubee.gnubee monit[1560]: 'mountpoint_srv_dev-disk-by-label-test' status failed (1) -- mountpoint: /srv/dev-disk-by-label-test: No such file or directory                                
Jan 09 14:41:08 gnubee.gnubee monit[1560]: Filesystem '/srv/dev-disk-by-label-test' not mounted
Jan 09 14:41:08 gnubee.gnubee monit[1560]: 'filesystem_srv_dev-disk-by-label-test' unable to read filesystem '/srv/dev-disk-by-label-test' state                                                          
Jan 09 14:41:08 gnubee.gnubee monit[1560]: 'filesystem_srv_dev-disk-by-label-test' trying to restart
Jan 09 14:41:08 gnubee.gnubee monit[1560]: 'mountpoint_srv_dev-disk-by-label-test' status failed (1) -- mountpoint: /srv/dev-disk-by-label-test: No such file or directory                                
Jan 09 14:41:39 gnubee.gnubee monit[1560]: Filesystem '/srv/dev-disk-by-label-test' not mounted
Jan 09 14:41:39 gnubee.gnubee monit[1560]: 'filesystem_srv_dev-disk-by-label-test' unable to read filesystem '/srv/dev-disk-by-label-test' state                                                          
Jan 09 14:41:39 gnubee.gnubee monit[1560]: 'filesystem_srv_dev-disk-by-label-test' trying to restart
Jan 09 14:41:39 gnubee.gnubee monit[1560]: 'mountpoint_srv_dev-disk-by-label-test' status failed (1) -- mountpoint: /srv/dev-disk-by-label-test: No such file or directory                                
Jan 09 14:41:55 gnubee.gnubee kernel: EXT4-fs (sdb1): mounted filesystem with ordered data mode. Opts: user_xattr,usrjquota=aquota.user,grpjquota=aquota.group,jqfmt=vfsv0,acl                            
Jan 09 14:41:55 gnubee.gnubee systemd[1]: Starting Enable File System Quotas...
Jan 09 14:41:55 gnubee.gnubee quotaon[3763]: quotaon: cannot find /srv/dev-disk-by-label-test/aquota.group on /dev/sdb1 [/srv/dev-disk-by-label-test]                                                     
Jan 09 14:41:55 gnubee.gnubee quotaon[3763]: quotaon: cannot find /srv/dev-disk-by-label-test/aquota.user on /dev/sdb1 [/srv/dev-disk-by-label-test]                                                      
Jan 09 14:41:55 gnubee.gnubee systemd[1]: quotaon.service: Main process exited, code=exited, status=2/INVALIDARGUMENT                                                                                     
Jan 09 14:41:55 gnubee.gnubee systemd[1]: quotaon.service: Failed with result 'exit-code'.
Jan 09 14:41:55 gnubee.gnubee systemd[1]: Failed to start Enable File System Quotas.
Jan 09 14:42:10 gnubee.gnubee monit[1560]: 'filesystem_srv_dev-disk-by-label-test' succeeded getting filesystem statistics for '/srv/dev-disk-by-label-test'                                              
Jan 09 14:42:10 gnubee.gnubee monit[1560]: 'mountpoint_srv_dev-disk-by-label-test' status failed (1) -- mountpoint: /srv/dev-disk-by-label-test: No such file or directory                                
Jan 09 14:42:41 gnubee.gnubee monit[1560]: 'mountpoint_srv_dev-disk-by-label-test' status succeeded (0) -- /srv/dev-disk-by-label-test is a mountpoint                                                    
Jan 09 14:44:27 gnubee.gnubee kernel: EXT4-fs (sdb1): re-mounted. Opts: user_xattr,usrjquota=aquota.user,grpjquota=aquota.group,jqfmt=vfsv0,acl
Jan 09 14:44:28 gnubee.gnubee kernel: EXT4-fs (sdb1): re-mounted. Opts: user_xattr,usrjquota=aquota.user,grpjquota=aquota.group,jqfmt=vfsv0,acl
Jan 09 14:44:30 gnubee.gnubee omv-engined[733]: Failed to write to socket: Broken pipe
Jan 09 14:44:30 gnubee.gnubee omv-engined[733]: 
Jan 09 14:45:01 gnubee.gnubee CRON[7829]: pam_unix(cron:session): session opened for user root by (uid=0)
Jan 09 14:45:01 gnubee.gnubee CRON[7833]: (root) CMD (/usr/sbin/omv-mkrrdgraph >/dev/null 2>&1)
Jan 09 14:47:53 gnubee.gnubee CRON[7829]: pam_unix(cron:session): session closed for user root
Jan 09 14:51:51 gnubee.gnubee omv-engined[7598]: Failed to write to socket: Broken pipe
Jan 09 14:51:51 gnubee.gnubee omv-engined[11785]: Failed to write to socket: Broken pipe
Jan 09 14:51:51 gnubee.gnubee omv-engined[11785]: 
Jan 09 14:51:51 gnubee.gnubee omv-engined[7598]: 
Jan 09 14:51:51 gnubee.gnubee omv-engined[10399]: Failed to write to socket: Broken pipe
Jan 09 14:51:51 gnubee.gnubee omv-engined[10399]: 
Jan 09 14:51:51 gnubee.gnubee omv-engined[8993]: Failed to write to socket: Broken pipe
Jan 09 14:51:51 gnubee.gnubee omv-engined[8993]: 
```
I did have a kernel without quotas enabled when I created the filesystem so the first mounts failed. I since rebuilt the kernel with quota support. Maybe that's why the quota files are missing?

**Comment by jjakob** [comment] 2020-01-09 14:47
I tried it again:
- reverted the configuration (no errors)
- created completely new filesystem on sdc (immediately shows error: communication lost, but then continues to make the filesystem (shows mkfs.ext4 output) and finishes ok)
- mounted new filesystem (after a short time shows error: communication lost, but after some time mounts the filesystem ok)
- apply configuration (works for a few minutes, then throws the above error "no filter named 'is_device_file'")

Console looks better now, no more monit errors:
```
Jan 09 15:29:24 gnubee.gnubee kernel: EXT4-fs (sdc1): mounted filesystem with ordered data mode. Opts: user_xattr,usrjquota=aquota.user,grpjquota=aquota.group,jqfmt=vfsv0,acl                            
Jan 09 15:30:02 gnubee.gnubee CRON[1592]: pam_unix(cron:session): session opened for user root by (uid=0)                                                                                                 
Jan 09 15:30:02 gnubee.gnubee CRON[1591]: pam_unix(cron:session): session opened for user root by (uid=0)                                                                                                 
Jan 09 15:30:02 gnubee.gnubee CRON[1599]: (root) CMD (/usr/sbin/omv-mkrrdgraph >/dev/null 2>&1)
Jan 09 15:30:02 gnubee.gnubee CRON[1600]: (root) CMD ([ -x /etc/init.d/anacron ] && if [ ! -d /run/systemd/system ]; then /usr/sbin/invoke-rc.d anacron start >/dev/null; fi)                             
Jan 09 15:30:02 gnubee.gnubee CRON[1592]: pam_unix(cron:session): session closed for user root
Jan 09 15:32:15 gnubee.gnubee CRON[1591]: pam_unix(cron:session): session closed for user root
Jan 09 15:32:24 gnubee.gnubee systemd[1]: Started Run anacron jobs.
Jan 09 15:32:24 gnubee.gnubee anacron[4937]: Anacron 2.3 started on 2020-01-09
Jan 09 15:32:24 gnubee.gnubee anacron[4937]: Normal exit (0 jobs run)
Jan 09 15:32:24 gnubee.gnubee systemd[1]: anacron.service: Succeeded.
Jan 09 15:37:05 gnubee.gnubee systemd[1]: Started /bin/systemctl reload monit.service.
Jan 09 15:37:05 gnubee.gnubee systemd[1]: Reloading LSB: service and resource monitoring daemon.
Jan 09 15:37:05 gnubee.gnubee monit[1560]: Reinitializing Monit -- control file '/etc/monit/monitrc'
Jan 09 15:37:05 gnubee.gnubee monit[11077]: Reloading daemon monitor configuration: monit.
Jan 09 15:37:05 gnubee.gnubee systemd[1]: Reloaded LSB: service and resource monitoring daemon.
Jan 09 15:37:05 gnubee.gnubee systemd[1]: run-rf36f0fc5ea9b43c187a43324bed16e6b.scope: Succeeded.
Jan 09 15:37:05 gnubee.gnubee monit[1560]: '\gnubee.gnubee' Monit reloaded
Jan 09 15:39:00 gnubee.gnubee systemd[1]: Starting Clean php session files...
Jan 09 15:39:01 gnubee.gnubee CRON[13649]: pam_unix(cron:session): session opened for user root by (uid=0)                                                                                                
Jan 09 15:39:01 gnubee.gnubee CRON[13666]: (root) CMD (  [ -x /usr/lib/php/sessionclean ] && if [ ! -d /run/systemd/system ]; then /usr/lib/php/sessionclean; fi)                                         
Jan 09 15:39:01 gnubee.gnubee CRON[13649]: pam_unix(cron:session): session closed for user root
Jan 09 15:39:02 gnubee.gnubee systemd[1]: phpsessionclean.service: Succeeded.
Jan 09 15:39:02 gnubee.gnubee systemd[1]: Started Clean php session files.
Jan 09 15:40:01 gnubee.gnubee omv-engined[8008]: Failed to write to socket: Broken pipe
Jan 09 15:40:01 gnubee.gnubee omv-engined[6662]: Failed to write to socket: Broken pipe
Jan 09 15:40:01 gnubee.gnubee omv-engined[6662]:
Jan 09 15:40:01 gnubee.gnubee omv-engined[9340]: Failed to write to socket: Broken pipe
Jan 09 15:40:01 gnubee.gnubee omv-engined[9340]:
Jan 09 15:40:01 gnubee.gnubee omv-engined[10763]: Failed to write to socket: Broken pipe
Jan 09 15:40:01 gnubee.gnubee omv-engined[10763]:
Jan 09 15:40:01 gnubee.gnubee omv-engined[8008]:
Jan 09 15:40:36 gnubee.gnubee smbd[1733]: [2020/01/09 15:40:36.933605,  2] ../source3/smbd/server.c:807(remove_child_pid)                                                                                 
Jan 09 15:40:36 gnubee.gnubee smbd[1733]:   Could not find child 15843 -- ignoring
Jan 09 15:41:05 gnubee.gnubee systemd[1]: Starting Enable File System Quotas...
Jan 09 15:41:05 gnubee.gnubee quotaon[16508]: quotaon: cannot find /srv/dev-disk-by-label-test2/aquota.group on /dev/sdc1 [/srv/dev-disk-by-label-test2]                                                  
Jan 09 15:41:05 gnubee.gnubee quotaon[16508]: quotaon: cannot find /srv/dev-disk-by-label-test2/aquota.user on /dev/sdc1 [/srv/dev-disk-by-label-test2]                                                   
Jan 09 15:41:05 gnubee.gnubee systemd[1]: quotaon.service: Main process exited, code=exited, status=2/INVALIDARGUMENT                                                                                     
Jan 09 15:41:05 gnubee.gnubee systemd[1]: quotaon.service: Failed with result 'exit-code'.
Jan 09 15:41:05 gnubee.gnubee systemd[1]: Failed to start Enable File System Quotas.
```
The quotaon error is when I tried to start the quotaon service to check it, so it still fails.

Can you please reopen the issue as it's not solved yet?
```

**Comment by votdev** [comment] 2020-01-09 15:02
> apply configuration (works for a few minutes, then throws the above error "no filter named 'is_device_file'")

I can not reproduce this. When the openmediavault package is installed all new Salt modules and runners are synced. This can also done manually via `omv-salt stage run prepare`. Jinja filters are [initialized here](https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/srv/salt/omv/deploy/collectd/plugins/init.sls#L21) in latest openmediavault 5.2.2 package.

**Comment by ryecoaaron** [comment] 2020-01-09 15:23
Is this happening because your mipsel kernel doesn't support quotas?

**Comment by jjakob** [comment] 2020-01-09 15:37
@ryecoaaron 
When I first installed OMV and tried to create the filesystem, the kernel didn't support quotas (I didn't even know it needed to), it wouldn't mount the new filesystem due to the quota options in fstab. I then recompiled it with quotas, it now mounts fine, all the above tests are carried out with a quota enabled kernel.

@votdev 
I installed the updated openmediavault and openmediavault-diskstats deb packages via `dpkg -i`, no errors were reported. After you suggested it I ran `omv-salt stage run prepare` which finished with success. I think I rebooted after the upgrade, I can try that again.

**Comment by jjakob** [comment] 2020-01-09 16:11
The "communication error" message pops up exactly 60 seconds after clicking e.g. the "Unmount" button as salt (`python3 /usr/sbin/omv-salt deploy run fstab`) is still crunching away. It takes 3 minutes for the omv-salt process to finish. I got a nginx 504 Gateway timeout thrown in for the first time when clicking the "Mount" button for good measure. I rebooted it, tried again and got the exact same error at applying (the apply process takes ~5-7 minutes, again due to the slowness of python on this machine).

I self-built all the openmediavault packages (except for the two I upgraded due to this issue that are downloaded from the repos), versions:
```
root@gnubee:~# dpkg -l 'openmediavault*' php-pam libjs-extjs6 wsdd
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                       Version         Architecture Description
+++-==========================-===============-============-=====================================================================================
ii  libjs-extjs6               6.2.0.981-2     all          Ext JS is a cross-browser JavaScript library for building rich internet applications.
ii  openmediavault             5.2.2-1         all          openmediavault - The open network attached storage solution
un  openmediavault-ad          <none>          <none>       (no description available)
ii  openmediavault-diskstats   5.0.3-1         all          openmediavault disk monitoring plugin
ii  openmediavault-forkeddaapd 5.0-1           all          openmediavault forked-daapd (DAAP server) plugin
ii  openmediavault-keyring     1.0             all          GnuPG archive keys of the openmediavault archive
ii  openmediavault-ldap        4.0.6-1         all          openmediavault Lightweight Directory Access Protocol (LDAP) plugin
ii  openmediavault-lvm2        5.0.1-1         all          openmediavault Logical Volume Manager (LVM2) plugin
ii  openmediavault-nut         5.0-1           all          openmediavault Network UPS Tools (NUT) plugin
ii  openmediavault-shairport   5.0-1           all          openmediavault shairport (AirPlay/RAOP receiver) plugin
ii  openmediavault-snmp        5.0-1           all          openmediavault SNMP (Simple Network Management Protocol) plugin
ii  openmediavault-tftp        5.0-1           all          openmediavault TFTP-Server plugin
ii  openmediavault-usbbackup   5.0.2-1         all          openmediavault USB/eSATA backup plugin
ii  php-pam                    1.0.3-1+deb10u1 mipsel       pam module for PHP 7
ii  wsdd                       0.5-1           all          Web Services on Devices (WSD) daemon
```
The process I used to build and install I documented [here](https://gist.github.com/jjakob/c9ab333d15105b986008863e9f4f5db8)

**Comment by votdev** [comment] 2020-01-09 16:39
IMO this machine and platform is really under-powered, i fear that the user experience is really bad. I don't think a user is happy about waiting up to 7 minutes until the configuration is deployed.

The 60 second are the usual timeout of the WebUI.

**Comment by jjakob** [comment] 2020-01-09 16:44
> IMO this machine and platform is really under-powered, i fear that the user experience is really bad. I don't think a user is happy about waiting up to 7 minutes until the configuration is deployed.
> 
> The 60 second are the usual timeout of the WebUI.

I agree, I wouldn't mind waiting that long - if it worked. I'm probably going to just do things the old fashioned way by setting up daemons manually. I'll keep this installation on a partition so that I can come back to it if this particular error gets fixed. If only Python wasn't so slow...

**Comment by ryecoaaron** [comment] 2020-01-09 18:18
Python isn't slow.  Salt is.  But that is because it is doing a lot.

**Comment by JoshuaMunoz** [comment] 2021-11-21 02:36
OMV 5 - cannot get a newly installed Seagate Exos 16TB to mount. Wiped many times, opened up a thread on the forum, nothing so far. Some people telling me the salt doesn't line up with the server - I'm not sure.

Error message here:

`Error #0:
OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; omv-salt deploy run --no-color fstab 2>&1' with exit code '1': debian:
    Data failed to compile:
----------
    Rendering SLS 'base:omv.deploy.fstab.15mergerfsfolders' failed: Jinja error: 'xsystemd'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 497, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python3/dist-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 25, in top-level template code
  File "/usr/lib/python3/dist-packages/jinja2/sandbox.py", line 385, in getattr
    value = getattr(obj, attribute)
  File "/usr/lib/python3/dist-packages/openmediavault/collectiontools.py", line 126, in __getitem__
    return dict.__getitem__(self, key)
KeyError: 'xsystemd'

; line 25

---
[...]
{% for dir in branchDirs %}
{% if dir | length > 2 %}
{% set _ = branches.append(dir) %}
{% if '*' not in dir %}
{% set parent = salt['cmd.shell']('findmnt --noheadings --output TARGET --target ' + dir) %}
{% if not pool.xsystemd %}    <======================
{% if parent | length > 1 %}
{% set _ = options.append('x-systemd.requires=' + parent) %}
{% endif %}
{% endif %}
{% endif %}
[...]
--- in /usr/share/php/openmediavault/system/process.inc:195
Stack trace:
#0 /usr/share/php/openmediavault/engine/module/serviceabstract.inc(62): OMV\System\Process->execute()
#1 /usr/share/openmediavault/engined/rpc/config.inc(167): OMV\Engine\Module\ServiceAbstract->deploy()
#2 [internal function]: Engined\Rpc\Config->applyChanges(Array, Array)
#3 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#4 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('applyChanges', Array, Array)
#5 /usr/share/openmediavault/engined/rpc/filesystemmgmt.inc(917): OMV\Rpc\Rpc::call('Config', 'applyChanges', Array, Array)
#6 [internal function]: Engined\Rpc\OMVRpcServiceFileSystemMgmt->mount(Array, Array)
#7 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#8 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('mount', Array, Array)
#9 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('FileSystemMgmt', 'mount', Array, Array, 1)
#10 {main}`

**Comment by votdev** [comment] 2021-11-21 15:37
@ryecoaaron I created a PR to fix that, see https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-mergerfsfolders/pull/8.
