### ISSUE TITLE
OMV6 check locked users script complains about missing 'tally' directory

### ISSUE THREAD

**Issue by robvdl** [openmediavault/openmediavault#1133] opened 2021-11-10 19:41 UTC
**Describe the bug**

I am getting a daily email when /etc/cron.daily/openmediavault-check_locked_users runs.

**To Reproduce**

Script runs daily on it's own.

**Expected behavior**

Shouldn't be getting an error email if this directory is missing ideally.

**openmediavault Server (please complete the following information):**

- OS version: Debian 11
- openmediavault version: 6

**Additional context**

Error email content:

```
/etc/cron.daily/openmediavault-check_locked_users:
faillock: Error reading tally directory: No such file or directory
```

**Comment by votdev** [comment] 2021-11-10 19:52
Which hardware platform are you using? How is the OMV OS been installed; ISO or omv-extras.org script?

**Comment by votdev** [comment] 2021-11-10 19:59
Are you using the `openmediavault-flashmemory` plugin?

**Comment by votdev** [comment] 2021-11-10 20:01
Which package version are you using?

**Comment by votdev** [comment] 2021-11-10 20:01
Have you read https://forum.openmediavault.org/index.php?thread/40192-faillock-error-reading-tally-directory-no-such-file-or-directory/?

**Comment by robvdl** [comment] 2021-11-10 20:03
Hi, thank you for all these links. I will check them out on Saturday when I will see my friend who is running the OMV instance.

**Comment by robvdl** [comment] 2021-11-10 20:11
All I can recall is I did a standard Debian 11 + OMV 6 installation and did not install any additional plugins. So it isn't likely the flashmemory plugin is installed unless it's part of the default set.

**Comment by robvdl** [comment] 2021-11-10 23:28
Hardware platform is AMD64 Ryzen 5600x just a regular PC with Debian 11 64 bit.

**Comment by votdev** [comment] 2021-11-11 08:53
I can not reproduce this issue. Additionally i have to say that OMV does not do any configure for `faillock`. The only reason for this issue seems to me a problem during the installation.

Try to reinstall the package, hopefully this will fix the issue: `apt-get install --reinstall libpam-modules`.

**Comment by robvdl** [comment] 2021-11-11 09:02
OK thanks, I will have a go at that. I'm playing in a VM at the moment with a fresh install. I just wanted to check something else because it talks about creating a directory /var/run/faillock and I'm thinking hang on a minute ... /var/run is a symlink to /run which is tmpfs on Debian so creating any directory there aint gonna survive a reboot :)

**Comment by robvdl** [comment] 2021-11-11 09:04
And also I can confirm that in my trial VM with Debian 11, /var/run/faillock does exist. So I'll recommend reinstalling libpam-modules as you suggest.

**Comment by mi-hol** [comment] 2021-11-28 12:34
Closing due to no feedback, assuming issue was solved

**Closed by mi-hol** 2021-11-28 12:34 UTC
Labels: feedback requested, 6.x

**Comment by robvdl** [comment] 2021-11-28 16:49
Yeah it was, I was trying to find the issue the other day but couldn't find it for some reason.

Running dpkg-reconfigure on libpam-modules made this go away, strange...
