### ISSUE TITLE
Updates Management has a changelog error

### ISSUE THREAD

**Issue by isometimescode** [openmediavault/openmediavault#489] opened 2019-11-01 23:46 UTC
### Description of issue/question
When looking at the available updates, clicking on "show changelog" for `openmediavault 5.0.11` gives me the following error:

```
Failed to execute command 'export LANG=C; dpkg-deb --fsys-tarfile '/var/cache/apt/archives/openmediavault_5.0.11_all.deb' | tar --extract --wildcards --directory='/tmp/5dbcc31d380c3' ./usr/share/doc/openmediavault/changelog* 2>&1': tar: ./usr/share/doc/openmediavault/changelog.Debian.gz: Not found in archive tar: Exiting with failure status due to previous errors
```

### Steps to reproduce issue
(Include debug logs if possible and relevant.)
<img width="789" alt="changelog_error" src="https://user-images.githubusercontent.com/7094373/68062340-09865200-fcc7-11e9-9b7c-4bc71050a9ae.png">

### Versions report
Currently running 5.0.10-1 (Usul)

**Comment by votdev** [comment] 2019-11-02 14:36
```
$ dpkg-deb --fsys-tarfile openmediavault_5.0.11_all.deb | tar -tv
...
-rw-r--r-- root/root     35914 2019-10-30 07:40 ./usr/share/doc/openmediavault
/changelog.Debian.gz
...
```
Hmmm, the file is in the archive.

**Comment by votdev** [comment] 2019-11-02 14:47
No problem to extract the changelog from CLI, but WebUI fails. Hmmmmm
```
root@omv5box:~# export LANG=C; dpkg-deb --fsys-tarfile /var/cache/apt/archives/openmediavault_5.0.11_all.deb | tar --extract --wildcards --directory='/tmp/5dbcc31d380c3' ./usr/share/doc/openmediavault/changelog*
root@omv5box:~# 
root@omv5box:~# ls -alh /tmp/5dbcc31d380c3
total 0
drwxr-xr-x  3 root root  60 Nov  2 14:45 .
drwxrwxrwt 11 root root 360 Nov  2 14:43 ..
drwxr-xr-x  3 root root  60 Nov  2 14:45 usr
```

**Comment by votdev** [comment] 2019-11-02 14:54
Currently i really have no idea what the problem is and how to fix it.

**Comment by votdev** [comment] 2019-11-02 15:00
I'm wondering what is going wrong with tar here. On the one side tar seems to have extracted the file list, because it knows the exact path of the changelog specified with wildcard in the command line (``./usr/share/doc/openmediavault/changelog* => ./usr/share/doc/openmediavault/changelog.Debian.gz``), on the other side tar fails to extract it finally (``Not found in archive tar``).

**Comment by votdev** [comment] 2019-11-02 16:45
It seems to be that ``tar`` does not like to be executed in a PHP ``exec`` environment. Had not find out what is missing in this shell. At the moment i would say this is an upstream issue because this code works since years now.
Maybe a regression in ``tar`` in the latest version.

**Comment by votdev** [comment] 2019-11-02 22:06
Fixed in openmediavault 5.0.13.

**Closed by votdev** 2019-11-02 22:06 UTC
Labels: 5.x, bug, help wanted, upstream issue
