### ISSUE TITLE
OMV5 fresh install, e-mail notification internal error (only once but still)

### ISSUE THREAD

**Issue by the-Arioch** [openmediavault/openmediavault#991] opened 2021-03-28 18:10 UTC
Release: 5.6.2-1
Codename: Usul
Linux diskoteka.local 5.10.0-0.bpo.3-amd64 #1 SMP Debian 5.10.13-1~bpo10+1 (2021-02-11) x86_64 GNU/Linux

I was setting myself e-mail notifications.
It was not straightforward task, as our ISP does not provide SMTP server and also blocks SMTP/25 traffic outside.
So i made one or two failed attempts before e-mails actually started flowing out.

Then i looked into my mailbos and saw the uncaught error message there:
```
Subject: [diskoteka.local] Anacron job 'cron.daily' on diskoteka
Body: /etc/cron.daily/openmediavault-flush-mailq:
postsuper: fatal: scan_dir_push: open directory hold: No such file or directory
run-parts: /etc/cron.daily/openmediavault-flush-mailq exited with return code 1
```

Granted, next two mails were "test message" and since then eveyrthing went smoothly.
However the first uncaught exception shows that there is somce inconsistency or race condition inside OMV codebase/setting during first time setup.

**Comment by votdev** [comment] 2021-03-28 18:42
The issue behaves as following: The cron job to flush the postfix mail queue was executed by cron exactly at that time when you setup email notification and OMV build the postfix config and starts the  daemon. Sadly you've not played lottery, because i assume this constellation will never happen twice.
Beside the fact that the cron job already does some tests before running it makes no sense to do some more hardening. Testing if postfix is up and ready before running the job is more costly than getting the error message for this really really rare situation.

If you've enabled the notifications some second later or earlier you should not have run into this issue.

I will close the issue because these unlucky conditions should not happen twice or at least too often.

**Comment by the-Arioch** [comment] 2021-03-28 19:07
Well i have that knack to get applications off balance. Would i play lotteries i would probably manage to get some negative prize...

> conditions should not happen twice

I think it is survivor's bias. I would rather think that users do see this error but do not bother to report as they do not perceive OMV polished enough to bother reporting. Frankly, from conumer perception, it was a rough ride, many small glitches. This creates overall impression of "background noise" of errors. When one sees a first error he has an urge to report it and "help reduce universe enthropy", when he sees tenth error he concludes it is no use to bother.

Perhaps all it really needs to trigger this specific race is having slow old computer  with relatively slow 2.5" HDD.  In particular, it was Atom D525 dual-core with 4GB RAM here, and x.org was running with some Python IDE, Mozilla and text editor.

> Beside the fact that the cron job already does some tests before running it makes no sense to do some more hardening.

I agree there would be no point to make tests inside the cron. Just race itself should be undone.
The cron job should be kept disabled until the very last moment when all prerequisites (dependencies) are satisfied.
When MTA is shutting down it should disable the cron job.
After configs are created and MTA is restart only after this "barrier" OMV can re-enable the job.

This way there would be no need to harden the job as the job would not be ever run until prerequisites created. Granted, there still can be race when MTA gets shut down *while* cron job is being run. Well, multithreading programming is hard.... And this coincidence should really be once a million case.

Another option could be using a function to create-or-open file path. I think it is already there in RTLs of all more or less developed languages. So if there was no queue folder when cron job started - it would just create it rather than failing. However judging by `postsuper: fatal...` the failing code is probably within MTA itself, not within your own code. Patching Postfix would really be way too much.

**Comment by votdev** [comment] 2021-03-28 19:29
>  In particular, it was Atom D525 dual-core with 4GB RAM here, and x.org was running with some Python IDE, Mozilla and text editor.

Running a GUI on OMV is absolutely not supported because OMV and GUI's work against each other. OMV is the master of the system by design.

> This way there would be no need to harden the job as the job would not be ever run until prerequisites 
> created. Granted, there still can be race when MTA gets shut down while cron job is being run. Well, 
> multithreading programming is hard.... And this coincidence should really be once a million case.

The problem here is that you've run into the situation that the cron job was started right at the moment that postfix is setting up itself. The directory `/var/spool/postfix/hold/` is created by postfix itself on startup. Because of that it does not make sense to check for postfix is running in the cron job because it WAS running already at that time, but doesn't have created the directory. Doing further checks is somewhat useless because it really does not make sense to do checks of postfix internals.

**Closed** 2021-03-28 19:29 UTC
Labels: reject

**Comment by the-Arioch** [comment] 2021-03-28 20:20
> OMV is the master of the system by design.

Until some error happens - and there are quite some, including total failure of WebUI after Extras installed, and total freeze of modal WebUI window after apt-get install (maybe after actually installing that extra, do not remember details)

So, yes, it comes with some risks of course.

>  that the cron job was started right at the moment that postfix is setting up itself.

Exactly. Definition of race conditions in async/SMP programming. That should had be precluded. Cron job should be disabled and not re-enabled until prerequisites are created. The concept is simple, the implemnentatio nnot so much.

>  it does not make sense to check for postfix is running in the cron job because it WAS running already at that time

Cron job, ideally, should not be checking a thing. It is putting the horse before the cart.
It should become impossible for cron job to get fired until all prerequisits are satisfied.
Like push vs pull, like polling v s interrupts, activity direction beter be reversed.

Postfix should have some flag/event when it is "all up and running", and cron job should only get enabled AFTER all dependencies are cleared.
an
Since `OMV is the master of the system` use of defensive programmin (cron job checking if it was launched into unready void) idealyl has to be unneeded. The goal has to be different, ensuring job can no way be launcehed until everything is ready.

Granted, understanding and documenting and keeping dependencies tree is easy to say much harder to do.

Still, focusing on making cron job having checks is thinking about painkillers instead of curing the disease. One pill a mopnth is probably okay, but living on drugs tends to be snowballing beyond reasonable.

Like, commenting out that specific anacron job https://docs.oracle.com/cd/E37670_01/E41138/html/ch07s03.html
Or making specific "mailing enabled" flag file that this job would check as their first line...
Snowballing thousand small checks is really a dead end, this i agree.

**Comment by votdev** [comment] 2021-03-28 20:47
> Exactly. Definition of race conditions in async/SMP programming. That should had be precluded. Cron 
> job should be disabled and not re-enabled until prerequisites are created. The concept is simple, the 
> implemnentatio nnot so much.

Looking forward for your contribution.
