### ISSUE TITLE
NFS Mounts Break on Shared Folder Path Change

### ISSUE THREAD

**Issue by Xipherisroot** [openmediavault/openmediavault#118] opened 2018-06-02 17:47 UTC
openmediavault information
--
Release: 3.0.99
Codename: Erasmus

System information
--
Linux NAS 4.9.0-0.bpo.6-amd64 #1 SMP Debian 4.9.88-1+deb9u1~bpo8+1 (2018-05-13) x86_64 GNU/Linux

I had a shared folder that was on a single disk that was referenced as an NFS share.

I copied the contents of the folder to a different drive with the same path on that device.

I went to the 'Shared Folders' area and modified the associated share to change it from the old device to the new one with the same folder path on that new device as the old one.

I tested the matching SMB share and it was now working and pointed to the new device.

I checked the NFS share and in the dialogue it showed it was also pointed to the new device.

I tested the NFS mount and it was still pointing to the old drive, I restarted the NFS service, still pointing to the old drive, restarted the entire NAS, still pointing to the old drive, unmounted the file system of the old drive, wouldn't let me because although its not 'referenced' its in use, restarted the NAS again with the mount disabled, the system booted and showed everything was fine, it was not.

The NFS mount no longer worked but still showed it was pointing to the new drive, trying to delete the NFS share caused issues because removing the associated mount point from the "/export" area failed since it got a "Device or Resource busy" error when attempting to do so... because even with the old drive's filesystem not mounted, it was still mounting that specific _folder_ from the old drive to that "/export" location to facilitate the NFS share all while the system thought the share was pointing to the new drive and that the old drive wasn't even mounted.

I had to manually unmount the "/export" location since any change I made on the system was broken without doing so.

The bug seems to be that if you edit the location of a 'Shared Folder", the NFS share assocaited _thinks_ its pointing to the new location since the name is the same, but its not and it never will, there's also no way to edit an NFS share's path which is more than a mild annoyance.

**Comment by subzero79** [comment] 2018-06-08 09:51
That;s a known issue, it was reported on the old bugtracker. The answer by that time was no fix,i cannot recall why. The problem is the fstab mount bind used for nfs is not unmounted, and remounted with the new source force.
Maybe with the new approach  on salt that can change.

**Comment by votdev** [comment] 2018-07-09 14:02
Does this issue also happen to you in OMV4? There were many changes related this problem.

**Comment by Samuel12321** [comment] 2019-11-05 07:19
Tested on OMV 4.1.26-1(Arrakis), Issue doesnt occur. Appears to be fixed by OMV4.
Suggest closing issue.

**Closed** 2019-11-05 08:11 UTC
Labels: 3.x
