### ISSUE TITLE
networking.service fails to start (times out after 5 minutes) when both IPv4 and IPv6 are enabled for an interface

### ISSUE THREAD

**Issue by amezin** [openmediavault/openmediavault#116] opened 2018-06-01 08:32 UTC
When I enable both IPv4 and IPv6 for some interface (DHCP in both cases), omv boots very slowly. The problem is networking.service. It freezes and times out after 5 minutes:

```
root@omv:~# systemctl status networking.service 
● networking.service - Raise network interfaces
   Loaded: loaded (/lib/systemd/system/networking.service; enabled; vendor preset: enabled)
   Active: failed (Result: timeout) since Fri 2018-06-01 14:20:43 +06; 3min 41s ago
     Docs: man:interfaces(5)
  Process: 463 ExecStart=/sbin/ifup -a --read-environment (code=killed, signal=TERM)
  Process: 332 ExecStartPre=/bin/sh -c [ "$CONFIGURE_INTERFACES" != "no" ] && [ -n "$(ifquery --read-environment --list --exclude=lo)" ] && udevadm settle (code=exited, status=0/SUCCESS)
 Main PID: 463 (code=killed, signal=TERM)

Jun 01 14:15:42 omv systemd[1]: Starting Raise network interfaces...
Jun 01 14:15:43 omv ifup[463]: ifup: waiting for lock on /run/network/ifstate.enp0s3
Jun 01 14:20:43 omv systemd[1]: networking.service: Start operation timed out. Terminating.
Jun 01 14:20:43 omv systemd[1]: networking.service: Main process exited, code=killed, status=15/TERM
Jun 01 14:20:43 omv systemd[1]: Failed to start Raise network interfaces.
Jun 01 14:20:43 omv systemd[1]: networking.service: Unit entered failed state.
Jun 01 14:20:43 omv systemd[1]: networking.service: Failed with result 'timeout'.
```

But the interface gets an IPv6 address:

```
root@omv:~# ifconfig enp0s3
enp0s3: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.140  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::a00:27ff:fed8:1436  prefixlen 64  scopeid 0x20<link>
        inet6 2a02:2698:5422:c615:a00:27ff:fed8:1436  prefixlen 64  scopeid 0x0<global>
        ether 08:00:27:d8:14:36  txqueuelen 1000  (Ethernet)
        RX packets 889  bytes 102471 (100.0 KiB)
        RX errors 0  dropped 1  overruns 0  frame 0
        TX packets 733  bytes 68035 (66.4 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

Reproducible on real hardware and in VirtualBox. Installed OMV 4 on top of a minimal installation of Debian 9 using this guide: http://openmediavault.readthedocs.io/en/latest/installation/on_debian.html
The same problem didn't occur on Debian prior to installation of OMV

**Comment by jonathanmmm** [comment] 2019-03-08 09:26
I have the same issue after I changed my motherboard and had to reconfigure (enp4s0 changed to enp2s0).

But removing auto (as in refferenced) will propably dissable autostart of the network interface and make the machine after restart not available over network (if I understand correctly what auto does, it autostarts the interface on bootup?).

Before the system also needed some time to boot up but maybe I have never typed:
systemctl status networking.service.
I just looked at ifconfig or similar outputs.

If I disable ipv6 with omv-firstaid all works properly.

I chose both auto (dhcpv6 and slaac?) ways for IPv6 both didn´t work.

The system gets ipv6 (fd55..., fe80..., 2003...) and can ping6 ipv6.google.com and also an ipv6 (2003) of another device in my network.

So all seems to work. But still the networking.service failed. I don´t believe this is good.

**Comment by votdev** [comment] 2019-03-08 14:44
> The same problem didn't occur on Debian prior to installation of OMV

Does this apply to the same machines your using to test OMV? If yes, does the /etc/network/interfaces file looks exact the same? I'm wondering because OMV does not do any special things to the userland network stack.

The only thing that comes into mind is the systemd unit openmediavault-issue. Can you give it a try and disable this unit. Maybe this will fix the boot issue.

**Comment by shbatm** [comment] 2019-04-17 14:32
The following fix worked for me:

 in your `/etc/network/interfaces`, change this:

```
# The primary network interface
auto eth0
iface eth0 inet dhcp
```

to this:

```
# The primary network interface
allow-hotplug eth0
iface eth0 inet dhcp
```

Substitute `eth0` for all of your ethernet adapter names. 

This will start interface eth0 when the kernel detects a hotplug event from the interface (i.e. when you plug a cable in), instead of starting it at boot.

**Comment by votdev** [comment] 2019-04-17 14:39
> to this:
> 
> ```
> # The primary network interface
> allow-hotplug eth0
> iface eth0 inet dhcp
> ```
> 

This is strange because this is exacly what OMV does when it [creates the configuration file](https://github.com/openmediavault/openmediavault/blob/4.x/deb/openmediavault/usr/share/openmediavault/mkconf/interfaces.d/20ethernet#L43).

**Comment by shbatm** [comment] 2019-04-17 22:54
Let me clarify, I had to remove `auto eth0` line and just have the hotplug line. OMV added it back though, so back to square one.

**Comment by jonathanmmm** [comment] 2019-04-18 14:45
Same Here.

Changed
# enp2s0 network interface                                               
auto enp2s0                                                             
allow-hotplug enp2s0                                                     
iface enp2s0 inet static
(And so on)
To:
# enp2s0 network interface                                               
#auto enp2s0                                                             
allow-hotplug enp2s0                                                     
iface enp2s0 inet static
(And so on)

(I commented auto enps20 Out)
And restarted the status was active and not failed:
root@MyServer:~# systemctl status networking                                                                                     ● networking.service - Raise network interfaces
   Loaded: loaded (/lib/systemd/system/networking.service; enabled; vendor preset: enabled)
   Active: active (exited) since Thu 2019-04-18 16:36:03 CEST; 4min 5s ago
     Docs: man:interfaces(5)
  Process: 12972 ExecStart=/sbin/ifup -a --read-environment (code=exited, status=0/SUCCESS)
  Process: 12968 ExecStartPre=/bin/sh -c [ "$CONFIGURE_INTERFACES" != "no" ] && [ -n "$(ifquery --read-environment --list --exclude=lo)" ] 
&& udevadm settle (code=exited, status=1/FAILURE)
 Main PID: 12972 (code=exited, status=0/SUCCESS)
    Tasks: 0 (limit: 4915)
   CGroup: /system.slice/networking.service

Apr 18 16:36:03 MyServer systemd[1]: Starting Raise network interfaces...
Apr 18 16:36:03 MyServer systemd[1]: Started Raise network interfaces.

@amezin your Problem should be solved.
Is OMV patched to not include "Auto <devicename>" anymore in the omv-firstaid

But why does it only fail with Auto on when ipv6 is also enabled (haven't tried only ipv6 to see If it fails when both are enabled or if the Problem is in ipv6).

**Comment by jonathanmmm** [comment] 2019-04-18 14:52
https://github.com/openmediavault/openmediavault/issues/116#issuecomment-484118704
But it also does put auto in there (Look one Line above in the Code)

**Comment by OverByThere** [comment] 2019-05-09 19:39
I just wanted to add that this fixed the issue for me. I was stuck with the UI telling me to save my changes, it was only by having the `interfaces` file open and constantly saving it as it ran the save changes that I was able to get past this point.

**Comment by latency-dev** [comment] 2019-06-08 17:07
This fixed it for me until it gets patched out by omv updates. The gui wil omv first aid will generate good interface configuration files now which won't error out.

Edit:
/usr/share/openmediavault/mkconf/interfaces.d/20ethernet

Remove the line:
-v "concat('auto ',devicename)" -n \

**Comment by 8jef** [comment] 2020-11-11 20:05
Have the same problem with Renegade roc-rk3328-cc arm soc. Tried many hack found at many places. Used last Armbian Buster headless built with latest OMV built. Did everything as in the manual. Re-installed twice just to be sure. Armbian on itself works right (before OMV install). Unfortunately, all fixes I've found are for RPI ot x86 installs, and do no apply here.

So, upon reboot of the device, eth0 is lost. Spends 5 mins trying to boot. 

omv-firstaid fixes it, temporarily, until next reboot. Tried dhcp and fixed ip with same results.

Only fix so far: never reboot, always on scenario. 

This problem seems to happen for some time, to quite many people, across losts of different platforms. It there a cure? Hope let live they say.

**Comment by votdev** [comment] 2020-11-11 21:05
> So, upon reboot of the device, eth0 is lost. Spends 5 mins trying to boot.

This sounds to me that predictable device names are not enabled, right? Maybe it would help to find this out.

**Comment by 8jef** [comment] 2020-11-11 22:27
@shbatm I can cross that out, only one interface here - once I've got through omv-firstaid scheme to create it.

@votdev Thanks for the answer. How can I find out? I've read some pages about it, then this https://wiki.debian.org/NetworkInterfaceNames - but I'm kinda lost and over my head.

So please, how and where to look for predictable device names enabling?

Thanks

**Comment by mi-hol** [comment] 2020-12-16 17:36
@8jef please use the OMV forum at https://forum.openmediavault.org/ to get support.

@all others, from reading this thru my conclusion is that this issue has been fixed in 5.x.
In case I got it wrong please reply and provide your OMV version via caommand "dpkg -l | grep openmediavault"

**Comment by mi-hol** [comment] 2021-01-06 16:58
no feedback received, closing

**Closed by mi-hol** 2021-01-06 16:58 UTC
Labels: 5.x affected, PR welcome, bug, cleanup, feedback requested
