### ISSUE TITLE
PhotoPrism allow users to change the mariadb buffer pool size

### ISSUE THREAD

**Issue by boatmon0** [openmediavault/openmediavault#1614] opened 2023-10-16 15:34 UTC
I have a lot of photos, maybe 700,000 they seem to get bigger every few years.  The UI on photoprism is very very slow.  Maybe a couple of minutes to refresh a page.  It's running on a fairly new machine, and obviously has a lot of storage and memory.  Stats on memory show 20gb free cpu utilization is about 5%.  This leads me to believe that I need to do some tuning.

I WOULD LIKE THE CONFIGURATION TO INCLUDE MEMORY TO ALLOCATE TO THIS APPLICATION

The first thing in improving performance is:
The [InnoDB buffer pool](https://mariadb.com/kb/en/innodb-buffer-pool/) serves as a cache for data and indexes. It is a key component for optimizing MariaDB performance. Its size should be as large as possible to keep frequently used data in memory and reduce disk I/O - typically the biggest bottleneck.

Modify docker compose to increase memory for photoprism
services:
  mariadb:
    command: mysqld --innodb-buffer-pool-size=1G ...

If you think I have some other problem just sing out and I will try anything.  Thanks for your consideration.

**Comment by votdev** [comment] 2023-10-16 15:51
If you are talking about the Docker compose plugin and the example template for PhotoPrism, please raise the issue at https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-compose.

If you are talking about the `openmediavault-photoprism` plugin you can use the `OMV_PHOTOPRISM_DB_CONTAINER_START_OPTIONS` [environment variable](https://docs.openmediavault.org/en/stable/various/advset.html#environmental-variables) to append additional Podman command line args to set environment variables.

**Comment by boatmon0** [comment] 2023-10-16 23:35
I'm new to photoprism,  is the close to the proper syntax to set memory for the database?

omv-env set -- OMV_PHOTOPRISM_APP_CONTAINER_START_OPTIONS innodb-buffer-pool-size=1G

If I'm on track can I go as high as 10gb if I have plenty of memory?

I used the automatic install for photoprism, so I'm not sure that I have access to docker compose.

**Comment by votdev** [comment] 2023-10-17 06:07
> I'm new to photoprism, is the close to the proper syntax to set memory for the database?
> 
> omv-env set -- OMV_PHOTOPRISM_APP_CONTAINER_START_OPTIONS innodb-buffer-pool-size=1G
> 
> If I'm on track can I go as high as 10gb if I have plenty of memory?
> 
> I used the automatic install for photoprism, so I'm not sure that I have access to docker compose.

I don't think so, you need to have a look [here for the env variables](https://hub.docker.com/_/mariadb) that are supported by the container or somewhere else how to inject those setting into the MariaDB container.

**Comment by votdev** [comment] 2023-10-17 06:10
I am closing this issue because it is not a bug and it is better off in the [forum](https://forum.openmediavault.org/).

**Closed by votdev** 2023-10-17 06:10 UTC
Labels: feature
