### ISSUE TITLE
UPS ISSUE.

### ISSUE THREAD

**Issue by insp1re2600** [openmediavault/openmediavault#1065] opened 2021-07-11 11:10 UTC
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; omv-salt deploy run --no-color collectd 2>&1' with exit code '1': debian:
----------
          ID: configure_collectd_conf_cpu_plugin
    Function: file.managed
        Name: /etc/collectd/collectd.conf.d/cpu.conf
      Result: True
     Comment: File /etc/collectd/collectd.conf.d/cpu.conf is in the correct state
     Started: 12:09:37.741686
    Duration: 16.398 ms
     Changes:
----------
          ID: configure_collectd_conf_df_plugin
    Function: file.managed
        Name: /etc/collectd/collectd.conf.d/df.conf
      Result: True
     Comment: File /etc/collectd/collectd.conf.d/df.conf is in the correct state
     Started: 12:09:37.758185
    Duration: 5.133 ms
     Changes:
----------
          ID: configure_collectd_conf_interface_plugin
    Function: file.managed
        Name: /etc/collectd/collectd.conf.d/interface.conf
      Result: True
     Comment: File /etc/collectd/collectd.conf.d/interface.conf is in the correct state
     Started: 12:09:37.763457
    Duration: 4.93 ms
     Changes:
----------
          ID: configure_collectd_conf_load_plugin
    Function: file.managed
        Name: /etc/collectd/collectd.conf.d/load.conf
      Result: True
     Comment: File /etc/collectd/collectd.conf.d/load.conf is in the correct state
     Started: 12:09:37.768533
    Duration: 1.451 ms
     Changes:
----------
          ID: configure_collectd_conf_memory_plugin
    Function: file.managed
        Name: /etc/collectd/collectd.conf.d/memory.conf
      Result: True
     Comment: File /etc/collectd/collectd.conf.d/memory.conf is in the correct state
     Started: 12:09:37.770113
    Duration: 2.052 ms
     Changes:
----------
          ID: configure_collectd_conf_nut_plugin
    Function: file.managed
        Name: /etc/collectd/collectd.conf.d/nut.conf
      Result: True
     Comment: File /etc/collectd/collectd.conf.d/nut.conf is in the correct state
     Started: 12:09:37.772324
    Duration: 1.406 ms
     Changes:
----------
          ID: configure_collectd_conf_rrdcached_plugin
    Function: file.managed
        Name: /etc/collectd/collectd.conf.d/rrdcached.conf
      Result: True
     Comment: File /etc/collectd/collectd.conf.d/rrdcached.conf is in the correct state
     Started: 12:09:37.773830
    Duration: 1.581 ms
     Changes:
----------
          ID: configure_collectd_conf_syslog_plugin
    Function: file.managed
        Name: /etc/collectd/collectd.conf.d/syslog.conf
      Result: True
     Comment: File /etc/collectd/collectd.conf.d/syslog.conf is in the correct state
     Started: 12:09:37.775556
    Duration: 1.545 ms
     Changes:
----------
          ID: configure_collectd_conf_unixsock_plugin
    Function: file.managed
        Name: /etc/collectd/collectd.conf.d/unixsock.conf
      Result: True
     Comment: File /etc/collectd/collectd.conf.d/unixsock.conf is in the correct state
     Started: 12:09:37.777200
    Duration: 1.28 ms
     Changes:
----------
          ID: configure_collectd_conf_uptime_plugin
    Function: file.managed
        Name: /etc/collectd/collectd.conf.d/uptime.conf
      Result: True
     Comment: File /etc/collectd/collectd.conf.d/uptime.conf is in the correct state
     Started: 12:09:37.778576
    Duration: 1.31 ms
     Changes:
----------
          ID: prereq_collectd_service_monit
    Function: salt.state
      Result: True
     Comment: States ran successfully. Updating debian.
     Started: 12:09:37.780926
    Duration: 398.965 ms
     Changes:
              debian:
              ----------
                        ID: configure_monit_collectd_service
                  Function: file.managed
                      Name: /etc/monit/conf.d/openmediavault-collectd.conf
                    Result: True
                   Comment: File /etc/monit/conf.d/openmediavault-collectd.conf is in the correct state
                   Started: 12:09:38.022917
                  Duration: 24.515 ms
                   Changes:
              ----------
                        ID: configure_monit_filesystem_service
                  Function: file.managed
                      Name: /etc/monit/conf.d/openmediavault-filesystem.conf
                    Result: True
                   Comment: File /etc/monit/conf.d/openmediavault-filesystem.conf is in the correct state
                   Started: 12:09:38.047540
                  Duration: 9.181 ms
                   Changes:
              ----------
                        ID: configure_monit_nginx_service
                  Function: file.managed
                      Name: /etc/monit/conf.d/openmediavault-nginx.conf
                    Result: True
                   Comment: File /etc/monit/conf.d/openmediavault-nginx.conf is in the correct state
                   Started: 12:09:38.056807
                  Duration: 8.387 ms
                   Changes:
              ----------
                        ID: configure_monit_nut_service
                  Function: file.managed
                      Name: /etc/monit/conf.d/openmediavault-nut.conf
                    Result: True
                   Comment: File /etc/monit/conf.d/openmediavault-nut.conf is in the correct state
                   Started: 12:09:38.065288
                  Duration: 7.089 ms
                   Changes:
              ----------
                        ID: configure_monit_omv-engined_service
                  Function: file.managed
                      Name: /etc/monit/conf.d/openmediavault-engined.conf
                    Result: True
                   Comment: File /etc/monit/conf.d/openmediavault-engined.conf is in the correct state
                   Started: 12:09:38.072450
                  Duration: 5.091 ms
                   Changes:
              ----------
                        ID: configure_monit_php-fpm_service
                  Function: file.managed
                      Name: /etc/monit/conf.d/openmediavault-phpfpm.conf
                    Result: True
                   Comment: File /etc/monit/conf.d/openmediavault-phpfpm.conf is in the correct state
                   Started: 12:09:38.077614
                  Duration: 5.08 ms
                   Changes:
              ----------
                        ID: remove_monit_proftpd_service
                  Function: file.absent
                      Name: /etc/monit/conf.d/openmediavault-proftpd.conf
                    Result: True
                   Comment: File /etc/monit/conf.d/openmediavault-proftpd.conf is not present
                   Started: 12:09:38.082769
                  Duration: 0.388 ms
                   Changes:
              ----------
                        ID: configure_monit_rrdcached_service
                  Function: file.managed
                      Name: /etc/monit/conf.d/openmediavault-rrdcached.conf
                    Result: True
                   Comment: File /etc/monit/conf.d/openmediavault-rrdcached.conf is in the correct state
                   Started: 12:09:38.083226
                  Duration: 5.231 ms
                   Changes:
              ----------
                        ID: configure_monit_system_service
                  Function: file.managed
                      Name: /etc/monit/conf.d/openmediavault-system.conf
                    Result: True
                   Comment: File /etc/monit/conf.d/openmediavault-system.conf is in the correct state
                   Started: 12:09:38.088531
                  Duration: 10.689 ms
                   Changes:
              ----------
                        ID: configure_default_monit
                  Function: file.managed
                      Name: /etc/default/monit
                    Result: True
                   Comment: File /etc/default/monit is in the correct state
                   Started: 12:09:38.099295
                  Duration: 1.409 ms
                   Changes:
              ----------
                        ID: divert_default_monit
                  Function: omv_dpkg.divert_add
                      Name: /etc/default/monit
                    Result: True
                   Comment: Leaving 'local diversion of /etc/default/monit to /etc/default/monit.distrib'
                   Started: 12:09:38.101105
                  Duration: 9.158 ms
                   Changes:
              ----------
                        ID: configure_monit_monitrc
                  Function: file.managed
                      Name: /etc/monit/monitrc
                    Result: True
                   Comment: File /etc/monit/monitrc is in the correct state
                   Started: 12:09:38.110467
                  Duration: 12.572 ms
                   Changes:
              ----------
                        ID: divert_monit_monitrc
                  Function: omv_dpkg.divert_add
                      Name: /etc/monit/monitrc
                    Result: True
                   Comment: Leaving 'local diversion of /etc/monit/monitrc to /etc/monit/monitrc.distrib'
                   Started: 12:09:38.123119
                  Duration: 9.171 ms
                   Changes:
              ----------
                        ID: test_monit_config
                  Function: cmd.run
                      Name: monit -t
                    Result: True
                   Comment: Command "monit -t" run
                   Started: 12:09:38.133636
                  Duration: 7.92 ms
                   Changes:
                            ----------
                            pid:
                                1620304
                            retcode:
                                0
                            stderr:
                            stdout:
                                Control file syntax OK
              ----------
                        ID: reload_monit_service
                  Function: service.running
                      Name: monit
                    Result: True
                   Comment: The service monit is already running
                   Started: 12:09:38.154534
                  Duration: 23.249 ms
                   Changes:

              Summary for debian
              -------------
              Succeeded: 15 (changed=1)
              Failed:     0
              -------------
              Total states run:     15
              Total run time:  139.130 ms
----------
          ID: configure_collectd_conf
    Function: file.managed
        Name: /etc/collectd/collectd.conf
      Result: True
     Comment: File /etc/collectd/collectd.conf is in the correct state
     Started: 12:09:38.180024
    Duration: 24.194 ms
     Changes:
----------
          ID: divert_collectd_conf
    Function: omv_dpkg.divert_add
        Name: /etc/collectd/collectd.conf
      Result: True
     Comment: Leaving 'local diversion of /etc/collectd/collectd.conf to /etc/collectd/collectd.conf.distrib'
     Started: 12:09:38.204722
    Duration: 11.673 ms
     Changes:
----------
          ID: start_collectd_service
    Function: service.running
        Name: collectd
      Result: False
     Comment: Job for collectd.service failed because the control process exited with error code.
              See "systemctl status collectd.service" and "journalctl -xe" for details.
     Started: 12:09:38.226585
    Duration: 9732.562 ms
     Changes:
----------
          ID: monitor_collectd_service
    Function: module.run
      Result: False
     Comment: One or more requisite failed: omv.deploy.collectd.default.start_collectd_service
     Started: 12:09:47.962980
    Duration: 0.008 ms
     Changes:
----------
          ID: install_mkrrdgraph_cron_job
    Function: file.managed
        Name: /etc/cron.d/openmediavault-mkrrdgraph
      Result: True
     Comment: File /etc/cron.d/openmediavault-mkrrdgraph is in the correct state
     Started: 12:09:47.963145
    Duration: 4.843 ms
     Changes:
----------
          ID: generate_rrd_graphs
    Function: cmd.run
        Name: /usr/sbin/omv-mkrrdgraph
      Result: True
     Comment: Command "/usr/sbin/omv-mkrrdgraph" run
     Started: 12:09:47.969413
    Duration: 2249.364 ms
     Changes:
              ----------
              pid:
                  1620452
              retcode:
                  0
              stderr:
              stdout:

Summary for debian
-------------
Succeeded: 15 (changed=2)
Failed:     2
-------------
Total states run:     17
Total run time:   12.459 s

OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; omv-salt deploy run --no-color collectd 2>&1' with exit code '1': debian:
----------
          ID: configure_collectd_conf_cpu_plugin
    Function: file.managed
        Name: /etc/collectd/collectd.conf.d/cpu.conf
      Result: True
     Comment: File /etc/collectd/collectd.conf.d/cpu.conf is in the correct state
     Started: 12:09:37.741686
    Duration: 16.398 ms
     Changes:
----------
          ID: configure_collectd_conf_df_plugin
    Function: file.managed
        Name: /etc/collectd/collectd.conf.d/df.conf
      Result: True
     Comment: File /etc/collectd/collectd.conf.d/df.conf is in the correct state
     Started: 12:09:37.758185
    Duration: 5.133 ms
     Changes:
----------
          ID: configure_collectd_conf_interface_plugin
    Function: file.managed
        Name: /etc/collectd/collectd.conf.d/interface.conf
      Result: True
     Comment: File /etc/collectd/collectd.conf.d/interface.conf is in the correct state
     Started: 12:09:37.763457
    Duration: 4.93 ms
     Changes:
----------
          ID: configure_collectd_conf_load_plugin
    Function: file.managed
        Name: /etc/collectd/collectd.conf.d/load.conf
      Result: True
     Comment: File /etc/collectd/collectd.conf.d/load.conf is in the correct state
     Started: 12:09:37.768533
    Duration: 1.451 ms
     Changes:
----------
          ID: configure_collectd_conf_memory_plugin
    Function: file.managed
        Name: /etc/collectd/collectd.conf.d/memory.conf
      Result: True
     Comment: File /etc/collectd/collectd.conf.d/memory.conf is in the correct state
     Started: 12:09:37.770113
    Duration: 2.052 ms
     Changes:
----------
          ID: configure_collectd_conf_nut_plugin
    Function: file.managed
        Name: /etc/collectd/collectd.conf.d/nut.conf
      Result: True
     Comment: File /etc/collectd/collectd.conf.d/nut.conf is in the correct state
     Started: 12:09:37.772324
    Duration: 1.406 ms
     Changes:
----------
          ID: configure_collectd_conf_rrdcached_plugin
    Function: file.managed
        Name: /etc/collectd/collectd.conf.d/rrdcached.conf
      Result: True
     Comment: File /etc/collectd/collectd.conf.d/rrdcached.conf is in the correct state
     Started: 12:09:37.773830
    Duration: 1.581 ms
     Changes:
----------
          ID: configure_collectd_conf_syslog_plugin
    Function: file.managed
        Name: /etc/collectd/collectd.conf.d/syslog.conf
      Result: True
     Comment: File /etc/collectd/collectd.conf.d/syslog.conf is in the correct state
     Started: 12:09:37.775556
    Duration: 1.545 ms
     Changes:
----------
          ID: configure_collectd_conf_unixsock_plugin
    Function: file.managed
        Name: /etc/collectd/collectd.conf.d/unixsock.conf
      Result: True
     Comment: File /etc/collectd/collectd.conf.d/unixsock.conf is in the correct state
     Started: 12:09:37.777200
    Duration: 1.28 ms
     Changes:
----------
          ID: configure_collectd_conf_uptime_plugin
    Function: file.managed
        Name: /etc/collectd/collectd.conf.d/uptime.conf
      Result: True
     Comment: File /etc/collectd/collectd.conf.d/uptime.conf is in the correct state
     Started: 12:09:37.778576
    Duration: 1.31 ms
     Changes:
----------
          ID: prereq_collectd_service_monit
    Function: salt.state
      Result: True
     Comment: States ran successfully. Updating debian.
     Started: 12:09:37.780926
    Duration: 398.965 ms
     Changes:
              debian:
              ----------
                        ID: configure_monit_collectd_service
                  Function: file.managed
                      Name: /etc/monit/conf.d/openmediavault-collectd.conf
                    Result: True
                   Comment: File /etc/monit/conf.d/openmediavault-collectd.conf is in the correct state
                   Started: 12:09:38.022917
                  Duration: 24.515 ms
                   Changes:
              ----------
                        ID: configure_monit_filesystem_service
                  Function: file.managed
                      Name: /etc/monit/conf.d/openmediavault-filesystem.conf
                    Result: True
                   Comment: File /etc/monit/conf.d/openmediavault-filesystem.conf is in the correct state
                   Started: 12:09:38.047540
                  Duration: 9.181 ms
                   Changes:
              ----------
                        ID: configure_monit_nginx_service
                  Function: file.managed
                      Name: /etc/monit/conf.d/openmediavault-nginx.conf
                    Result: True
                   Comment: File /etc/monit/conf.d/openmediavault-nginx.conf is in the correct state
                   Started: 12:09:38.056807
                  Duration: 8.387 ms
                   Changes:
              ----------
                        ID: configure_monit_nut_service
                  Function: file.managed
                      Name: /etc/monit/conf.d/openmediavault-nut.conf
                    Result: True
                   Comment: File /etc/monit/conf.d/openmediavault-nut.conf is in the correct state
                   Started: 12:09:38.065288
                  Duration: 7.089 ms
                   Changes:
              ----------
                        ID: configure_monit_omv-engined_service
                  Function: file.managed
                      Name: /etc/monit/conf.d/openmediavault-engined.conf
                    Result: True
                   Comment: File /etc/monit/conf.d/openmediavault-engined.conf is in the correct state
                   Started: 12:09:38.072450
                  Duration: 5.091 ms
                   Changes:
              ----------
                        ID: configure_monit_php-fpm_service
                  Function: file.managed
                      Name: /etc/monit/conf.d/openmediavault-phpfpm.conf
                    Result: True
                   Comment: File /etc/monit/conf.d/openmediavault-phpfpm.conf is in the correct state
                   Started: 12:09:38.077614
                  Duration: 5.08 ms
                   Changes:
              ----------
                        ID: remove_monit_proftpd_service
                  Function: file.absent
                      Name: /etc/monit/conf.d/openmediavault-proftpd.conf
                    Result: True
                   Comment: File /etc/monit/conf.d/openmediavault-proftpd.conf is not present
                   Started: 12:09:38.082769
                  Duration: 0.388 ms
                   Changes:
              ----------
                        ID: configure_monit_rrdcached_service
                  Function: file.managed
                      Name: /etc/monit/conf.d/openmediavault-rrdcached.conf
                    Result: True
                   Comment: File /etc/monit/conf.d/openmediavault-rrdcached.conf is in the correct state
                   Started: 12:09:38.083226
                  Duration: 5.231 ms
                   Changes:
              ----------
                        ID: configure_monit_system_service
                  Function: file.managed
                      Name: /etc/monit/conf.d/openmediavault-system.conf
                    Result: True
                   Comment: File /etc/monit/conf.d/openmediavault-system.conf is in the correct state
                   Started: 12:09:38.088531
                  Duration: 10.689 ms
                   Changes:
              ----------
                        ID: configure_default_monit
                  Function: file.managed
                      Name: /etc/default/monit
                    Result: True
                   Comment: File /etc/default/monit is in the correct state
                   Started: 12:09:38.099295
                  Duration: 1.409 ms
                   Changes:
              ----------
                        ID: divert_default_monit
                  Function: omv_dpkg.divert_add
                      Name: /etc/default/monit
                    Result: True
                   Comment: Leaving 'local diversion of /etc/default/monit to /etc/default/monit.distrib'
                   Started: 12:09:38.101105
                  Duration: 9.158 ms
                   Changes:
              ----------
                        ID: configure_monit_monitrc
                  Function: file.managed
                      Name: /etc/monit/monitrc
                    Result: True
                   Comment: File /etc/monit/monitrc is in the correct state
                   Started: 12:09:38.110467
                  Duration: 12.572 ms
                   Changes:
              ----------
                        ID: divert_monit_monitrc
                  Function: omv_dpkg.divert_add
                      Name: /etc/monit/monitrc
                    Result: True
                   Comment: Leaving 'local diversion of /etc/monit/monitrc to /etc/monit/monitrc.distrib'
                   Started: 12:09:38.123119
                  Duration: 9.171 ms
                   Changes:
              ----------
                        ID: test_monit_config
                  Function: cmd.run
                      Name: monit -t
                    Result: True
                   Comment: Command "monit -t" run
                   Started: 12:09:38.133636
                  Duration: 7.92 ms
                   Changes:
                            ----------
                            pid:
                                1620304
                            retcode:
                                0
                            stderr:
                            stdout:
                                Control file syntax OK
              ----------
                        ID: reload_monit_service
                  Function: service.running
                      Name: monit
                    Result: True
                   Comment: The service monit is already running
                   Started: 12:09:38.154534
                  Duration: 23.249 ms
                   Changes:

              Summary for debian
              -------------
              Succeeded: 15 (changed=1)
              Failed:     0
              -------------
              Total states run:     15
              Total run time:  139.130 ms
----------
          ID: configure_collectd_conf
    Function: file.managed
        Name: /etc/collectd/collectd.conf
      Result: True
     Comment: File /etc/collectd/collectd.conf is in the correct state
     Started: 12:09:38.180024
    Duration: 24.194 ms
     Changes:
----------
          ID: divert_collectd_conf
    Function: omv_dpkg.divert_add
        Name: /etc/collectd/collectd.conf
      Result: True
     Comment: Leaving 'local diversion of /etc/collectd/collectd.conf to /etc/collectd/collectd.conf.distrib'
     Started: 12:09:38.204722
    Duration: 11.673 ms
     Changes:
----------
          ID: start_collectd_service
    Function: service.running
        Name: collectd
      Result: False
     Comment: Job for collectd.service failed because the control process exited with error code.
              See "systemctl status collectd.service" and "journalctl -xe" for details.
     Started: 12:09:38.226585
    Duration: 9732.562 ms
     Changes:
----------
          ID: monitor_collectd_service
    Function: module.run
      Result: False
     Comment: One or more requisite failed: omv.deploy.collectd.default.start_collectd_service
     Started: 12:09:47.962980
    Duration: 0.008 ms
     Changes:
----------
          ID: install_mkrrdgraph_cron_job
    Function: file.managed
        Name: /etc/cron.d/openmediavault-mkrrdgraph
      Result: True
     Comment: File /etc/cron.d/openmediavault-mkrrdgraph is in the correct state
     Started: 12:09:47.963145
    Duration: 4.843 ms
     Changes:
----------
          ID: generate_rrd_graphs
    Function: cmd.run
        Name: /usr/sbin/omv-mkrrdgraph
      Result: True
     Comment: Command "/usr/sbin/omv-mkrrdgraph" run
     Started: 12:09:47.969413
    Duration: 2249.364 ms
     Changes:
              ----------
              pid:
                  1620452
              retcode:
                  0
              stderr:
              stdout:

Summary for debian
-------------
Succeeded: 15 (changed=2)
Failed:     2
-------------
Total states run:     17
Total run time:   12.459 s in /usr/share/php/openmediavault/system/process.inc:195
Stack trace:
#0 /usr/share/php/openmediavault/engine/module/serviceabstract.inc(62): OMV\System\Process->execute()
#1 /usr/share/openmediavault/engined/rpc/config.inc(167): OMV\Engine\Module\ServiceAbstract->deploy()
#2 [internal function]: Engined\Rpc\Config->applyChanges(Array, Array)
#3 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#4 /usr/share/php/openmediavault/rpc/serviceabstract.inc(149): OMV\Rpc\ServiceAbstract->callMethod('applyChanges', Array, Array)
#5 /usr/share/php/openmediavault/rpc/serviceabstract.inc(588): OMV\Rpc\ServiceAbstract->OMV\Rpc\{closure}('/tmp/bgstatusUs...', '/tmp/bgoutput4Q...')
#6 /usr/share/php/openmediavault/rpc/serviceabstract.inc(159): OMV\Rpc\ServiceAbstract->execBgProc(Object(Closure))
#7 /usr/share/openmediavault/engined/rpc/config.inc(189): OMV\Rpc\ServiceAbstract->callMethodBg('applyChanges', Array, Array)
#8 [internal function]: Engined\Rpc\Config->applyChangesBg(Array, Array)
#9 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#10 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('applyChangesBg', Array, Array)
#11 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('Config', 'applyChangesBg', Array, Array, 1)
#12 {main}

**Comment by insp1re2600** [comment] 2021-07-11 11:27
root@retronas:~# systemctl status collectd.service
● collectd.service - Statistics collection and monitoring daemon
     Loaded: loaded (/lib/systemd/system/collectd.service; enabled; vendor pres>
    Drop-In: /etc/systemd/system/collectd.service.d
             └─openmediavault.conf
     Active: activating (auto-restart) (Result: exit-code) since Sun 2021-07-11>
       Docs: man:collectd(1)
             man:collectd.conf(5)
             https://collectd.org
    Process: 1644230 ExecStartPre=/usr/sbin/collectd -t (code=exited, status=0/>
    Process: 1644233 ExecStart=/usr/sbin/collectd (code=exited, status=1/FAILUR>
   Main PID: 1644233 (code=exited, status=1/FAILURE)
        CPU: 33ms

**Comment by insp1re2600** [comment] 2021-07-11 11:29
Jul 11 12:28:23 retronas systemd[1]: collectd.service: Main process exited, cod>
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ An ExecStart= process belonging to unit collectd.service has exited.
░░
░░ The process' exit code is 'exited' and its exit status is 1.
Jul 11 12:28:23 retronas systemd[1]: collectd.service: Failed with result 'exit>
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ The unit collectd.service has entered the 'failed' state with result 'exit-c>
Jul 11 12:28:23 retronas systemd[1]: Failed to start Statistics collection and >
░░ Subject: A start job for unit collectd.service has failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ A start job for unit collectd.service has finished with a failure.
░░
░░ The job identifier is 5840753 and the job result is failed.

**Comment by insp1re2600** [comment] 2021-07-11 11:29
THERE IS NO NUT PLUGIN FOR COLLECTD

**Comment by votdev** [comment] 2021-07-11 12:03
The bug report is pretty useless in this state as it does not contain any information on how the problem came about or how it is to be reproduced.

**Comment by insp1re2600** [comment] 2021-07-11 12:13
> The bug report is pretty useless in this state as it does not contain any information on how the problem came about or how it is to be reproduced.
> 
> Please provide this information, the bug report template was added to request exactly those required information.

im showing your predefined error logs for it, what do you need?

i enable ups it throws up error saying collectd doesnt have the nut plugin.

plugin_load: Could not find plugin "nut" in /usr/lib/collectd
There is configuration for the `nut' plugin, but the plugin isn't loaded. Please check your configuration.

**Comment by votdev** [comment] 2021-07-11 12:42
> im showing your predefined error logs for it, what do you need?

Which version are we talking about? OMV5 or OMV6? For OMV5 the plugin has worked in the past. Did you have installed backports on your system?

**Comment by votdev** [comment] 2021-07-11 12:46
Please post the output of `dpkg -l | grep nut` and `dpkg -l | grep collect`.

**Comment by votdev** [comment] 2021-07-11 12:47
Are you using OMV on Raspbian?

**Comment by votdev** [comment] 2021-07-11 12:51
OK, i'm pretty sure you are using collectd 5.11.0-7 or greater on your system. It seems the nut driver has been removed. Need to investigate that for OMV6. For OMV5, make sure you do not use backports on your system, this is NOT supported because of the problem you maybe have now. For OMV only collectd 5.8.1 is supported.

**Comment by votdev** [comment] 2021-07-11 12:53
For OMV6, the nut plugin has been cut out in Debian Bullseye. There is a [bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=989805) related to this issue.

**Comment by insp1re2600** [comment] 2021-07-11 15:54
Using omv6, was specified as the latest version on the download site, no mention of it being a beta or unreleased till I installed it,

half of its knackered

**Comment by ryecoaaron** [comment] 2021-07-11 16:14
https://www.openmediavault.org/?p=2932

**Comment by insp1re2600** [comment] 2021-07-11 17:10
> https://www.openmediavault.org/?p=2932

Not everyone reads through pages of a blog, it was classed as latest release on sourceforge

**Comment by ryecoaaron** [comment] 2021-07-11 17:13
I understand that.  I was providing info not pointing out that you didn't read the blog.  Being the latest release on SF does not mean it is stable either.

**Comment by ryecoaaron** [comment] 2021-07-11 17:18
You can cut your reading down to one page to get a release status - https://openmediavault.readthedocs.io/en/latest/releases.html

**Comment by insp1re2600** [comment] 2021-07-11 17:19
> I understand that. I was providing info not pointing out that you didn't read the blog. Being the latest release on SF does not mean it is stable either.

3====D

**Comment by insp1re2600** [comment] 2021-07-21 12:28
still no joy with the ups issue...

**Comment by votdev** [comment] 2021-07-21 13:38
I'm waiting till upstream fixes the issue in the collectd package.

**Comment by mi-hol** [comment] 2021-11-15 11:24
@votdev according to [your comment in forum ](https://forum.openmediavault.org/index.php?thread/40587-failing-on-installation-of-plugin-openmediavault-nut-6-0-6/&postID=285303#post285303) this issue should be fixed.
Is this correct?

**Closed by mi-hol** 2021-11-15 11:24 UTC
Labels: upstream issue, 6.x

**Comment by mi-hol** [comment] 2021-11-15 11:26
@insp1re2600 please reopen in case there are still issues
