### ISSUE TITLE
Cannot remove storage

### ISSUE THREAD

**Issue by connected201** [openmediavault/openmediavault#1366] opened 2022-07-30 15:45 UTC
hi, all, i need help from comunity! i cannot remove storage:
![image](https://user-images.githubusercontent.com/20506433/181924353-9e1ec9e1-b297-4983-8da6-cff154b53d19.png)
![image](https://user-images.githubusercontent.com/20506433/181924502-c8fad282-aa02-4ff2-8b57-87f74ba276e4.png)
![image](https://user-images.githubusercontent.com/20506433/181924132-796fc508-b3c1-4f2f-a98a-b0e64fb8b90f.png)
![image](https://user-images.githubusercontent.com/20506433/181924861-c4f4eb7d-53dd-4c38-9237-a01f99664e53.png)

where i can find this reference? i deleted any users from system , but not help

**Comment by connected201** [comment] 2022-07-30 15:58
i tested, help only reboot openmediavault, but it's not solution!

**Comment by votdev** [comment] 2022-07-30 16:07
@ryecoaaron Is it possible to remove the DM device when it is unused? I think it is somehow possible to do that. I remember that it is possible via sysfs for MD devices.

**Comment by connected201** [comment] 2022-07-30 16:09
i cannot make device to not be used, only reboot help to unmount device.

**Comment by ryecoaaron** [comment] 2022-07-30 16:26
cryptsetup can remove a device.  That is about all I can think of.

**Comment by connected201** [comment] 2022-07-31 08:02
why delete button is inactive? where i can find "referended" to this disk?

**Comment by connected201** [comment] 2022-07-31 08:07
mount collision? (this is same drive) it's possible to mount same drive 2 times?
![image](https://user-images.githubusercontent.com/20506433/182016191-8d49ebd4-4d8e-4ec1-8203-0d4a3a3aed92.png)

**Comment by connected201** [comment] 2022-07-31 08:08
unmount error from both drives:
![image](https://user-images.githubusercontent.com/20506433/182016260-8456febc-03ef-4490-8c50-38a785a902fc.png)

**Comment by votdev** [comment] 2022-07-31 13:30
> why delete button is inactive? where i can find "referended" to this disk?

The `referenced` flag is set when the file system is used by a shared folder. YOu need to delete the shared folders before you are able to unmount/unuse the file system.

**Comment by votdev** [comment] 2022-07-31 13:46
> mount collision? (this is same drive) it's possible to mount same drive 2 times? ![image](https://user-images.githubusercontent.com/20506433/182016191-8d49ebd4-4d8e-4ec1-8203-0d4a3a3aed92.png)

There are checks to prevent that, but it seems there are edge cases that are not detected by them. Please post the output of the command `omv-confdbadm read --prettify conf.system.filesystem.mountpoint`.

**Comment by votdev** [comment] 2022-07-31 13:47
Please also provide the output of `omv-rpc -u admin 'FileSystemMgmt' 'getMountCandidates' | jq`

**Comment by connected201** [comment] 2022-07-31 14:44
**omv-confdbadm read --prettify conf.system.filesystem.mountpoint:**
```
[
    {
        "comment": "",
        "dir": "/srv/dev-disk-by-id-dm-name-sdb-crypt",
        "freq": 0,
        "fsname": "/dev/disk/by-id/dm-name-sdb-crypt",
        "hidden": false,
        "opts": "defaults,nofail",
        "passno": 2,
        "type": "btrfs",
        "usagewarnthreshold": 90,
        "uuid": "b35c3c81-b955-4eb4-aa14-81e87224d284"
    },
    {
        "comment": "",
        "dir": "/srv/dev-disk-by-uuid-f9d7007d-6a77-4928-9bd6-d6cbdefda291",
        "freq": 0,
        "fsname": "/dev/disk/by-uuid/f9d7007d-6a77-4928-9bd6-d6cbdefda291",
        "hidden": false,
        "opts": "defaults,nofail",
        "passno": 2,
        "type": "btrfs",
        "usagewarnthreshold": 90,
        "uuid": "cb1f9032-bcd8-417c-ae90-17ded2cb2ba3"
    }
]
```
```

root@openmediavault:~# omv-rpc -u admin 'FileSystemMgmt' 'getMountCandidates' | jq
[]
root@openmediavault:~# 
```

**Comment by votdev** [comment] 2022-07-31 15:20
Please post the output of the following commands:
```
# blkid
# udevadm info --query=property --name=/dev/disk/by-id/dm-name-sdb-crypt
# udevadm info --query=property --name=/dev/disk/by-uuid/f9d7007d-6a77-4928-9bd6-d6cbdefda291
```

**Comment by connected201** [comment] 2022-07-31 22:02
```
root@openmediavault:~# blkid
/dev/sda1: UUID="cacba1bb-4472-495c-921d-0918967d3a49" BLOCK_SIZE="4096" TYPE="ext4" PARTUUID="03b9e555-01"
/dev/sda5: UUID="d4b85fae-65dc-46ac-b1b2-0706107c8fd7" TYPE="swap" PARTUUID="03b9e555-05"
/dev/sdb: UUID="47c2749a-11b1-4725-9318-8d76bce7a53f" LABEL="encrypted-hdd" TYPE="crypto_LUKS"
/dev/mapper/sdb-crypt: UUID="f9d7007d-6a77-4928-9bd6-d6cbdefda291" UUID_SUB="07593b3f-ae69-44b2-a781-55dda3785a0c" BLOCK_SIZE="4096" TYPE="btrfs"
root@openmediavault:~# 

```

```
root@openmediavault:~# udevadm info --query=property --name=/dev/disk/by-id/dm-name-sdb-crypt
DEVPATH=/devices/virtual/block/dm-0
DEVNAME=/dev/dm-0
DEVTYPE=disk
DISKSEQ=5
MAJOR=253
MINOR=0
SUBSYSTEM=block
USEC_INITIALIZED=133899905
DM_UDEV_DISABLE_LIBRARY_FALLBACK_FLAG=1
DM_UDEV_PRIMARY_SOURCE_FLAG=1
DM_ACTIVATION=1
DM_NAME=sdb-crypt
DM_UUID=CRYPT-LUKS2-47c2749a11b1472593188d76bce7a53f-sdb-crypt
DM_SUSPENDED=0
DM_UDEV_RULES=1
DM_UDEV_RULES_VSN=2
ID_FS_UUID=f9d7007d-6a77-4928-9bd6-d6cbdefda291
ID_FS_UUID_ENC=f9d7007d-6a77-4928-9bd6-d6cbdefda291
ID_FS_UUID_SUB=07593b3f-ae69-44b2-a781-55dda3785a0c
ID_FS_UUID_SUB_ENC=07593b3f-ae69-44b2-a781-55dda3785a0c
ID_FS_TYPE=btrfs
ID_FS_USAGE=filesystem
ID_BTRFS_READY=1
DEVLINKS=/dev/mapper/sdb-crypt /dev/disk/by-id/dm-uuid-CRYPT-LUKS2-47c2749a11b1472593188d76bce7a53f-sdb-crypt /dev/disk/by-uuid/f9d7007d-6a77-4928-9bd6-d6cbdefda291 /dev/disk/by-id/dm-name-sdb-crypt
TAGS=:systemd:
CURRENT_TAGS=:systemd:
root@openmediavault:~# 
```

```
root@openmediavault:~# udevadm info --query=property --name=/dev/disk/by-uuid/f9d7007d-6a77-4928-9bd6-d6cbdefda291
DEVPATH=/devices/virtual/block/dm-0
DEVNAME=/dev/dm-0
DEVTYPE=disk
DISKSEQ=5
MAJOR=253
MINOR=0
SUBSYSTEM=block
USEC_INITIALIZED=133899905
DM_UDEV_DISABLE_LIBRARY_FALLBACK_FLAG=1
DM_UDEV_PRIMARY_SOURCE_FLAG=1
DM_ACTIVATION=1
DM_NAME=sdb-crypt
DM_UUID=CRYPT-LUKS2-47c2749a11b1472593188d76bce7a53f-sdb-crypt
DM_SUSPENDED=0
DM_UDEV_RULES=1
DM_UDEV_RULES_VSN=2
ID_FS_UUID=f9d7007d-6a77-4928-9bd6-d6cbdefda291
ID_FS_UUID_ENC=f9d7007d-6a77-4928-9bd6-d6cbdefda291
ID_FS_UUID_SUB=07593b3f-ae69-44b2-a781-55dda3785a0c
ID_FS_UUID_SUB_ENC=07593b3f-ae69-44b2-a781-55dda3785a0c
ID_FS_TYPE=btrfs
ID_FS_USAGE=filesystem
ID_BTRFS_READY=1
DEVLINKS=/dev/mapper/sdb-crypt /dev/disk/by-id/dm-uuid-CRYPT-LUKS2-47c2749a11b1472593188d76bce7a53f-sdb-crypt /dev/disk/by-id/dm-name-sdb-crypt /dev/disk/by-uuid/f9d7007d-6a77-4928-9bd6-d6cbdefda291
TAGS=:systemd:
CURRENT_TAGS=:systemd:
root@openmediavault:~# 
```

**Comment by votdev** [comment] 2022-08-01 06:34
What version are you running? I can not reproduce this issue with `6.0.32`.

**Comment by votdev** [comment] 2022-08-01 06:49
> unmount error from both drives: ![image](https://user-images.githubusercontent.com/20506433/182016260-8456febc-03ef-4490-8c50-38a785a902fc.png)

You need to apply the configuration changes first before you can unmount the file system. This is because applying the config changes will restart all services that have used that file system before.

**Comment by votdev** [comment] 2022-08-01 06:50
I'm closing this because i can not reproduce any error or some errors are follow errors caused due incorrect usage.

**Closed by votdev** 2022-08-01 06:50 UTC
Labels: user error, can't reproduce, 6.x
