### ISSUE TITLE
I got this error when I clicked Apply on configuration chages.

### ISSUE THREAD

**Issue by hobbygirl** [openmediavault/openmediavault#657] opened 2020-03-29 12:53 UTC
Error #0:
OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; omv-salt deploy run monit 2>&1' with exit code '1': /usr/lib/python3/dist-packages/salt/utils/path.py:265: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  if not isinstance(exes, collections.Iterable):
OMV:
----------
          ID: configure_monit_collectd_service
    Function: file.managed
        Name: /etc/monit/conf.d/openmediavault-collectd.conf
      Result: True
     Comment: File /etc/monit/conf.d/openmediavault-collectd.conf is in the correct state
     Started: 13:52:02.431289
    Duration: 84.264 ms
     Changes:
----------
          ID: configure_monit_filesystem_service
    Function: file.managed
        Name: /etc/monit/conf.d/openmediavault-filesystem.conf
      Result: True
     Comment: File /etc/monit/conf.d/openmediavault-filesystem.conf updated
     Started: 13:52:02.515853
    Duration: 38.18 ms
     Changes:
              ----------
              diff:
                  ---
                  +++
                  @@ -4,3 +4,19 @@
                           then alert else if succeeded for 10 cycles then alert

                  +check filesystem filesystem_srv_dev-disk-by-label-Books with path "/srv/dev-disk-by-label-Books"
                  +    if space usage > 85% for 5 times within 15 cycles
                  +        then alert else if succeeded for 10 cycles then alert
                  +
                  +
                  +check program mountpoint_srv_dev-disk-by-label-Books with path "/bin/mountpoint '/srv/dev-disk-by-label-Books'"
                  +    if status != 0 then alert
                  +
                  +check filesystem filesystem_srv_dev-disk-by-label-Books with path "/srv/dev-disk-by-label-Books"
                  +    if space usage > 85% for 5 times within 15 cycles
                  +        then alert else if succeeded for 10 cycles then alert
                  +
                  +
                  +check program mountpoint_srv_dev-disk-by-label-Books with path "/bin/mountpoint '/srv/dev-disk-by-label-Books'"
                  +    if status != 0 then alert
                  +
----------
          ID: configure_monit_nginx_service
    Function: file.managed
        Name: /etc/monit/conf.d/openmediavault-nginx.conf
      Result: True
     Comment: File /etc/monit/conf.d/openmediavault-nginx.conf is in the correct state
     Started: 13:52:02.554382
    Duration: 22.916 ms
     Changes:
----------
          ID: configure_monit_omv-engined_service
    Function: file.managed
        Name: /etc/monit/conf.d/openmediavault-engined.conf
      Result: True
     Comment: File /etc/monit/conf.d/openmediavault-engined.conf is in the correct state
     Started: 13:52:02.577597
    Duration: 22.507 ms
     Changes:
----------
          ID: configure_monit_php-fpm_service
    Function: file.managed
        Name: /etc/monit/conf.d/openmediavault-phpfpm.conf
      Result: True
     Comment: File /etc/monit/conf.d/openmediavault-phpfpm.conf is in the correct state
     Started: 13:52:02.600400
    Duration: 21.06 ms
     Changes:
----------
          ID: remove_monit_proftpd_service
    Function: file.absent
        Name: /etc/monit/conf.d/openmediavault-proftpd.conf
      Result: True
     Comment: File /etc/monit/conf.d/openmediavault-proftpd.conf is not present
     Started: 13:52:02.621758
    Duration: 0.801 ms
     Changes:
----------
          ID: configure_monit_rrdcached_service
    Function: file.managed
        Name: /etc/monit/conf.d/openmediavault-rrdcached.conf
      Result: True
     Comment: File /etc/monit/conf.d/openmediavault-rrdcached.conf is in the correct state
     Started: 13:52:02.622801
    Duration: 21.05 ms
     Changes:
----------
          ID: configure_monit_system_service
    Function: file.managed
        Name: /etc/monit/conf.d/openmediavault-system.conf
      Result: True
     Comment: File /etc/monit/conf.d/openmediavault-system.conf is in the correct state
     Started: 13:52:02.644151
    Duration: 43.47 ms
     Changes:
----------
          ID: configure_default_monit
    Function: file.managed
        Name: /etc/default/monit
      Result: True
     Comment: File /etc/default/monit is in the correct state
     Started: 13:52:02.687922
    Duration: 3.918 ms
     Changes:
----------
          ID: configure_monit_monitrc
    Function: file.managed
        Name: /etc/monit/monitrc
      Result: True
     Comment: File /etc/monit/monitrc is in the correct state
     Started: 13:52:02.692121
    Duration: 42.894 ms
     Changes:
----------
          ID: test_monit_config
    Function: cmd.run
        Name: monit -t
      Result: False
     Comment: Command "monit -t" run
     Started: 13:52:02.736717
    Duration: 28.6 ms
     Changes:
              ----------
              pid:
                  5978
              retcode:
                  1
              stderr:
                  /etc/monit/conf.d/openmediavault-filesystem.conf:15: Service name conflict, filesystem_srv_dev-disk-by-label-Books already defined '"/srv/dev-disk-by-label-Books"'
                  /etc/monit/conf.d/openmediavault-filesystem.conf:20: Service name conflict, mountpoint_srv_dev-disk-by-label-Books already defined ''/srv/dev-disk-by-label-Books''
              stdout:
----------
          ID: reload_monit_service
    Function: service.running
        Name: monit
      Result: True
     Comment: Service reloaded
     Started: 13:52:02.883646
    Duration: 110.612 ms
     Changes:
              ----------
              monit:
                  True

Summary for OMV
-------------
Succeeded: 11 (changed=3)
Failed:     1
-------------
Total states run:     12
Total run time:  440.272 ms in /usr/share/php/openmediavault/system/process.inc:182
Stack trace:
#0 /usr/share/php/openmediavault/engine/module/serviceabstract.inc(60): OMV\System\Process->execute()
#1 /usr/share/openmediavault/engined/rpc/config.inc(167): OMV\Engine\Module\ServiceAbstract->deploy()
#2 [internal function]: Engined\Rpc\Config->applyChanges(Array, Array)
#3 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#4 /usr/share/php/openmediavault/rpc/serviceabstract.inc(149): OMV\Rpc\ServiceAbstract->callMethod('applyChanges', Array, Array)
#5 /usr/share/php/openmediavault/rpc/serviceabstract.inc(588): OMV\Rpc\ServiceAbstract->OMV\Rpc\{closure}('/tmp/bgstatussO...', '/tmp/bgoutputDm...')
#6 /usr/share/php/openmediavault/rpc/serviceabstract.inc(159): OMV\Rpc\ServiceAbstract->execBgProc(Object(Closure))
#7 /usr/share/openmediavault/engined/rpc/config.inc(189): OMV\Rpc\ServiceAbstract->callMethodBg('applyChanges', Array, Array)
#8 [internal function]: Engined\Rpc\Config->applyChangesBg(Array, Array)
#9 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#10 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('applyChangesBg', Array, Array)
#11 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('Config', 'applyChangesBg', Array, Array, 1)
#12 {main}

**Comment by votdev** [comment] 2020-03-29 13:15
You made it somehow to mount the filesystem with the label `Books` twice. Any idea how you made this?

**Comment by hobbygirl** [comment] 2020-03-29 14:12
The drive label is books and I titled the file share books.

**Comment by votdev** [comment] 2020-03-30 04:21
Please post the output of the following commands.
```
# omv-confdbadm read --prettify conf.system.filesystem.mountpoint
# omv-rpc DiskMgmt enumerateDevices | jq
# blkid
# mount
```

**Comment by Sulfkain** [comment] 2020-05-04 06:55
Hey @hobbygirl, this has happen to me too.

And I found this fix:
```
sudo rm /etc/systemd/network/99-default.link
sudo netplan apply
sudo omv-salt deploy run systemd-networkd
```

From:
https://forum.openmediavault.org/index.php?thread/32133-interface-eth0-error-on-raspberry-pi-4/

**Comment by Wikinaut** [comment] 2020-05-10 22:02
Hello all, can someome please have a look if my problem - described in the forum - is the same: https://forum.openmediavault.org/index.php?thread/32544-omv5-regression-in-5-4-5-1-shared-folder-cannot-be-removed-anymore-omv-fails-to/#post239031

**Comment by mi-hol** [comment] 2020-12-17 17:42
@Wikinaut @hobbygirl is this still an open issue using latest versions?

**Comment by Wikinaut** [comment] 2020-12-17 18:43
> @Wikinaut @hobbygirl is this still an open issue using latest versions?

Haven't noticed it since then.

**Comment by votdev** [comment] 2020-12-17 20:57
I think we can close this because this was surely a SaltStack issue while they have been migrated to Python3.

**Closed by votdev** 2020-12-17 20:57 UTC
Labels: 5.x, cleanup, feedback requested
