### ISSUE TITLE
Activate WakeOnLan renames Interface

### ISSUE THREAD

**Issue by NobbyNet** [openmediavault/openmediavault#902] opened 2020-12-28 22:28 UTC
I use Debian Buster 10.7 (netplan.io 0.95-2) with openmediavault 5.5.19-1.

After active WakeOnLan via Web-Interface (Network -> Interfaces -> Select enp5s0 -> Edit -> Enable Wake-on-LAN) sometimes changes my device-name changes from enp5s0  to eth0 and I have an invalid configuration.

If I add "set-name: enp5s0" to /etc/netplan/20-openmediavault-enp5s0.yaml, everything works fine till next change.

/etc/netplan/20-openmediavault-enp5s0.yaml is generated with /srv/salt/omv/deploy/systemd-networkd/files/ethernet.j2.

Change
{%- if interface.wol | to_bool %}
      wakeonlan: true
{%- endif %}
to
{%- if interface.wol | to_bool %}
      wakeonlan: true
      set-name: {{ interface.devicename }}
{%- endif %}

make the change persistent.

**Comment by votdev** [comment] 2020-12-28 23:12
According to the [manual](https://netplan.io/reference/) it seems to me not the right way to use this in general for all devices.

**Comment by NobbyNet** [comment] 2020-12-29 17:17
On virtual devices _match_ and _set-name_ are not applicable. You use _match_ for this interface and so _set-name_ should be valid. Otherwise _match_ sholud be also invalid. On the otherhand we only confirm the current used name and don't change it.
If I understand netplan correctly, it ignores invalid values.
This is a quick fix. Another solution can bei add this option or free parameters to the GUI.

**Comment by votdev** [comment] 2020-12-29 17:32
> Another solution can bei add this option or free parameters to the GUI.

I'm not a fan of such solutions, because of that this will not happen.

**Comment by votdev** [comment] 2020-12-29 17:35
> After active WakeOnLan via Web-Interface (Network -> Interfaces -> Select enp5s0 -> Edit -> Enable Wake-on-LAN) sometimes changes my device-name changes from enp5s0 to eth0 and I have an invalid configuration.

This is the problem that must be solved, everything else if working around the origin source of the problem.

Maybe this is a problem of the driver? Or systemd must be told to re-initialize the interface correct after wake-up somehow.

**Comment by votdev** [comment] 2020-12-29 17:39
Until the real problem is fixed you can write your own netplan configuration file. All files and their configuration will be merged by netplan.io, so it is possible to split the configuration options across different files. This is the way to go to append custom configurations without changing the openmediavault settings.

**Comment by NobbyNet** [comment] 2020-12-29 18:22
I also don't like a GUI change.
How can we come closer to the problem?
If I activate WOL and reboot, then the interface name is changed without using set-name.
I use a Gigabyte A520 AORUS Elite Board with AMD Ryzen 3 PRO 4350G. The NIC is Realtek® GbE LAN. (RTL8168h/8111h)

**Comment by votdev** [comment] 2020-12-29 18:55
Maybe you hit the this [issue in systemd](https://github.com/systemd/systemd/issues/7293). 

The problem is, i can't and will not add any dirty workaround that is only necessary to fix your problem. I never heard about that problem till now, so it really seems to affect single installations. It's an absolute no-go to apply such workarounds to 100 thousands of installations  only to fix a single users issue.

**Comment by votdev** [comment] 2020-12-29 19:11
You should be able to customize netplan.io by creating the file `/etc/netplan/99-openmediavault-enp5s0.yaml` with the content
```
network:
  ethernets:
    enp5s0:
      set-name: enp5s0
```
Using `set-name` here is a dirty workaround. By default this setting is used to rename the cryptic predictable device names to more human readable ones.

**Comment by NobbyNet** [comment] 2020-12-29 20:03
If I create an additional file inside /etc/netplan/ like 99-openmediavault-enp5s0.yaml or 21-openmediavault-enp5s0.yaml, this files are delete, if I change something within the network configuration.

**Comment by ryecoaaron** [comment] 2020-12-29 20:23
It only removes files in /etc/netplan if they have openmediavault in the name - https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/srv/salt/omv/deploy/systemd-networkd/10cleanup.sls#L41.  So, just remove the openmediavault part of the filename.

**Comment by NobbyNet** [comment] 2020-12-29 20:35
Ok, this works.

**Closed** 2021-01-01 17:44 UTC
Labels: 5.x affected, upstream issue
