### ISSUE TITLE
Error on Filesystem page with BTRFS 

### ISSUE THREAD

**Issue by fri-sch** [openmediavault/openmediavault#828] opened 2020-10-19 20:36 UTC
### Description of issue/question
Opening the "Filesystem" tab causes endless loading of the page and finally an error message. This only happens with a BTRFS device as described here: https://forum.openmediavault.org/index.php?thread/30245-omv-5-2-1-storage-file-system-constant-loading/.

### Steps to reproduce issue
```
Oct 19 22:13:53 openmediavault omv-engined[321]: PHP Fatal error: Uncaught TypeError: Argument 2 passed to array_keys_exists() must be of the type array, null given, called in /usr/share/php/openmediavault/system/filesystem/backend/manager.inc on line 286 and defined in /usr/share/php/openmediavault/functions.inc:140
Oct 19 22:13:53 openmediavault omv-engined[321]: Stack trace:
Oct 19 22:13:53 openmediavault omv-engined[321]: #0 /usr/share/php/openmediavault/system/filesystem/backend/manager.inc(286): array_keys_exists(Array, NULL)
Oct 19 22:13:53 openmediavault omv-engined[321]: #1 /usr/share/php/openmediavault/system/filesystem/filesystem.inc(821): OMV\System\Filesystem\Backend\Manager->enumerate()
Oct 19 22:13:53 openmediavault omv-engined[321]: #2 /usr/share/openmediavault/engined/rpc/filesystemmgmt.inc(71): OMV\System\Filesystem\Filesystem::getFilesystems()
Oct 19 22:13:53 openmediavault omv-engined[321]: #3 [internal function]: Engined\Rpc\OMVRpcServiceFileSystemMgmt->enumerateFilesystems(NULL, Array)
Oct 19 22:13:53 openmediavault omv-engined[321]: #4 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
Oct 19 22:13:53 openmediavault omv-engined[321]: #5 /usr/share/openmediavault/engined/rpc/filesystemmgmt.inc(323): OMV\Rpc\ServiceAbstract->callMethod('enumerateFilesy...', NULL, Array)
Oct 19 22:13:53 openmediavault omv-engined[321]: #6 [internal function]: Engined\Rpc\OMVRpcServiceFileSystemMgmt->getList(Arra in /usr/share/php/openmediavault/functions.inc on line 140
```

### Versions report
5.5.11-1

**Comment by votdev** [comment] 2020-10-19 20:53
What is the output of `blkid`?

**Comment by fri-sch** [comment] 2020-10-20 17:47
I probably should mention that I'm experimenting with btrfs on top of bcache on top of mdadm, but I'm not sure if this matters here at all.

```
root@openmediavault:~# blkid 
/dev/sdc: UUID="af449fad-73fb-8636-b829-4ac1ef45ca8d" UUID_SUB="955e23e7-2010-7bb2-ef7f-ec1101e9ec5e" LABEL="openmediavault:raid1" TYPE="linux_raid_member"
/dev/sdb: UUID="eec0dbb0-3fc9-4527-9a6f-4d50cbe27944" TYPE="bcache"
/dev/sda1: UUID="a586b171-b3bb-4128-82b2-5a35226798f6" TYPE="ext4" PARTUUID="4503d250-01"
/dev/sda5: UUID="435785a0-4b7e-4568-8e9d-9035444a2ccc" TYPE="swap" PARTUUID="4503d250-05"
/dev/md0: UUID="1b331c8e-f34f-4a5c-a910-6449c9e00f66" TYPE="bcache"
/dev/sdd: UUID="af449fad-73fb-8636-b829-4ac1ef45ca8d" UUID_SUB="ea50a1ee-6597-1537-180d-a111f63b1336" LABEL="openmediavault:raid1" TYPE="linux_raid_member"
/dev/bcache0: UUID="fba3f805-8882-4237-bac2-abeb1b110cba" UUID_SUB="b2255a92-553b-474c-b99e-40552e193769" TYPE="btrfs"
```

**Comment by PrplHaz4** [comment] 2020-10-20 18:16
> 
> 
> I probably should mention that I'm experimenting with btrfs on top of bcache on top of mdadm, but I'm not sure if this matters here at all.
> 

I just recently converted btrfs on top of mdadm RAID1 to btrfs RAID1, and the OMV UI didn't snap back into shape until I ran `udevadm trigger` - so it may be referencing something that wasn't updated after the filesystem was created or moved...

**Comment by fri-sch** [comment] 2020-10-20 18:24
> I just recently converted btrfs on top of mdadm RAID1 to btrfs RAID1, and the OMV UI didn't snap back into shape until I ran `udevadm trigger` - so it may be referencing something that wasn't updated after the filesystem was created or moved...

Good hint! Running `udevadm trigger` indeed fixes the UI error.

**Comment by votdev** [comment] 2020-10-20 20:46
> Good hint! Running `udevadm trigger` indeed fixes the UI error.

So we can close this issue?

**Comment by fri-sch** [comment] 2020-10-21 16:05
> So we can close this issue?

If you consider this a valid fix. In my opinion it looks more like a workaround for a bug. Unfortunately I don't have the time to come up with a proper fix at the moment.

**Comment by votdev** [comment] 2020-10-21 17:54
> > So we can close this issue?
> 
> If you consider this a valid fix. In my opinion it looks more like a workaround for a bug. Unfortunately I don't have the time to come up with a proper fix at the moment.

I don't see a reason for searching for solutions that are caused by manual CLI interactions. If such manual actions are done, then the user is responsible for that. I also do not see a point where this should be handled by OMV.

**Closed by votdev** 2020-10-21 17:54 UTC
Labels: 5.x

**Comment by fri-sch** [comment] 2020-10-21 18:38
> I don't see a reason for searching for solutions that are caused by manual CLI interactions. If such manual actions are done, then the user is responsible for that. I also do not see a point where this should be handled by OMV.

Valid point. I didn't think of the scope of OMV only being to handle what is done in the UI.

**Comment by Daxx** [comment] 2021-03-31 10:56
> > Good hint! Running `udevadm trigger` indeed fixes the UI error.
> 
> So we can close this issue?

I vote NO

https://forum.openmediavault.org/index.php?thread/38595-storage-file-systems-view-not-loading/
