### ISSUE TITLE
Dashboard link in "Home" page not working OMV 4

### ISSUE THREAD

**Issue by dzogas** [openmediavault/openmediavault#127] opened 2018-06-29 10:34 UTC
Good day to you all!!

I hope it hasnt been reported before.

If you click the Home button where all the icons are, clicking on dashboard does nothing.

**Comment by votdev** [comment] 2018-07-09 09:12
This is a know issue since years. The problem is that it does not happen everytime and is really hard to identify. I think it's something deep in the ExtJS code.

**Comment by votdev** [comment] 2018-07-09 13:58
Fixed in openmediavault 4.1.9.

**Closed by votdev** 2018-07-09 13:58 UTC
Labels: 3.x, 4.x, 5.x, known issue
