### ISSUE TITLE
UI logs out automatically on graphs page

### ISSUE THREAD

**Issue by evilbunny2008** [openmediavault/openmediavault#1246] opened 2022-03-21 11:53 UTC
If you navigate to the graphs section of performance statistics and stay there for 10-15 minutes you will be logged out and need to log in again regardless for what you set the time out to be.

It'd be nice if the graphs updated every 15 minutes to match when graphs are re-drawn.

**Comment by votdev** [comment] 2022-03-21 11:57
What are your workbench settings? Is a auto-logout configured? If yes, to what time.

**Comment by votdev** [comment] 2022-03-21 11:59
On which page did you notice the issue? Does this issue happens on all graph pages or a specific one?

**Comment by evilbunny2008** [comment] 2022-03-21 12:00
I set my logout to both 1 day and disabled logout, it doesn't seem to matter which graph page you leave open.

**Comment by votdev** [comment] 2022-03-21 12:02
> It'd be nice if the graphs updated every 15 minutes to match when graphs are re-drawn.

The auto-reload feature has been disabled on all graph pages by intention because the frontend does not know when the graphs are regenerated. So it can happen that the page reloads the graphs that are already N minutes old. Because of that it makes more sense to let the user decide when to reload.

**Comment by evilbunny2008** [comment] 2022-03-21 12:06
> > It'd be nice if the graphs updated every 15 minutes to match when graphs are re-drawn.
> 
> The auto-reload feature has been disabled on all graph pages by intention because the frontend does not know when the graphs are regenerated. So it can happen that the page reloads the graphs that are already N minutes old. Because of that it makes more sense to let the user decide when to reload.

What about an option to enable refresh then, you can assume say 15 seconds past the quarter hour should have most/all graphs drawn on a default system.

**Comment by votdev** [comment] 2022-03-21 12:23
> > > It'd be nice if the graphs updated every 15 minutes to match when graphs are re-drawn.
> > 
> > 
> > The auto-reload feature has been disabled on all graph pages by intention because the frontend does not know when the graphs are regenerated. So it can happen that the page reloads the graphs that are already N minutes old. Because of that it makes more sense to let the user decide when to reload.
> 
> What about an option to enable refresh then, you can assume say 15 seconds past the quarter hour should have most/all graphs drawn on a default system. It already refreshes when you manually update graphs so it's part way there.

That might work, but then you have to check the current time constantly in the UI. You also keep in mind that the host clock and system clock might not in sync, e.g one of them is not using a time server or the RTC is not working correct. This will bring this idea out of sync.

All that is feasible, but i do not see any benefit here. TBH, the cost of implementing this feature is higher that the benefit IMO. So i let this to the community to implement that feature.

**Comment by votdev** [comment] 2022-03-21 12:24
BTW, i can not reproduce the auto-logout. The CPU graph page is open for 22 minutes now.

**Comment by evilbunny2008** [comment] 2022-03-21 12:28
I'm testing now too, when it does occur, clicking on a diff graph page and it shows broken image icons, not the sad graph icon, and then refreshes to the login page.

**Comment by votdev** [comment] 2022-03-21 12:28
IMO the better solution would be to implement a realtime graph that gets the data from the RRD database directly. The problem is that there is no project that allows to do that using PHP (the OMV backend and RPC stack is build on that). I have that idea already some years in mind, but without having the tools it's not possible to implement it.

**Comment by votdev** [comment] 2022-03-21 12:43
> > IMO the better solution would be to implement a realtime graph that gets the data from the RRD database directly. The problem is that there is no project that allows to do that using PHP (the OMV backend and RPC stack is build on that). I have that idea already some years in mind, but without having the tools it's not possible to implement it.
> 
> Something like highcharts? where you pass data in json format and it gets plotted in javascript

More or less, but OSS based and nothing proprietary.

**Comment by evilbunny2008** [comment] 2022-03-21 12:47
> More or less, but OSS based and nothing proprietary.

I always forget the name of the free one... cloudflare host it on their JS CDN

https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.3.2/chart.min.js

**Comment by votdev** [comment] 2022-03-21 12:48
I'll close this issue now because i was not able to reproduce the issue on FireFox and Chrome.

> > More or less, but OSS based and nothing proprietary.
> 
> I always forget the name of the free one... cloudflare host it on their JS CDN
> 
> [cdnjs.cloudflare.com/ajax/libs/Chart.js/3.3.2/chart.min.js](https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.3.2/chart.min.js)

OMV is already using ChartJS for dashboard widgets. The problem is getting data out of the RRD database.

**Comment by evilbunny2008** [comment] 2022-03-21 12:49
> OMV is already using ChartJS for dashboard widgets. The problem is getting data out of the RRD database.

Can you point me to examples and I can try hacking something together.

**Comment by votdev** [comment] 2022-03-21 12:51
> > OMV is already using ChartJS for dashboard widgets. The problem is getting data out of the RRD database.
> 
> Can you point me to examples and I can try hacking something together.

What exactly do you want to know? If you want to hack something, a good starting point is to check the source code on your own to get a feeling how everything works.

**Comment by evilbunny2008** [comment] 2022-03-21 12:57
I was after example text output from rrd, google didn't yeild anything

**Comment by evilbunny2008** [comment] 2022-03-21 12:59
Getting back to the bug, I was just logged out, not sure how long it took, but I was periodically browsing different graphs.

**Comment by votdev** [comment] 2022-03-21 13:03
I can not reproduce the issue in FireFox 98.0.1 and Chrome 99.0.4844.74 . FireFox was open now for 50mins and Chrome for 20mins. Zapping between different graph pages does not force an logout.

You need to provide more information, e.g. is there a message in the browser dev tools cosole? What was the last network request, it surely was returned a 401.

**Comment by evilbunny2008** [comment] 2022-03-21 13:11
Yes OMV 6.0.17-1 (Shaitan), I'm using the brave browser, which is based on chrome, [Version 1.36.112 Chromium: 99.0.4844.51 (Official Build)

**Comment by votdev** [comment] 2022-03-21 21:01
Closed because not reproducible. Please reopen if there are more information available that can be used to digg unto the problem.

**Closed by votdev** 2022-03-21 21:01 UTC
Labels: bug, help welcome, 6.x, backlog

**Comment by evilbunny2008** [comment] 2022-03-22 10:20
I've been doing further testing, so far it consistently happens in brave on the interfaces graphs, and this was spat out by rrd.php?name=interface-br0-hour.png

```
Error #0:
OMV\HttpErrorException: Session expired. in /usr/share/php/openmediavault/session.inc:157
Stack trace:
#0 /usr/share/php/openmediavault/session.inc(209): OMV\Session->validateTimeout()
#1 /var/www/openmediavault/rrd.php(28): OMV\Session->validate()
#2 {main}
```

**Comment by votdev** [comment] 2022-03-22 10:41
> I've been doing further testing, so far it consistently happens in brave on the interfaces graphs, and this was spat out by rrd.php?name=interface-br0-hour.png
> 
> ```
> Error #0:
> OMV\HttpErrorException: Session expired. in /usr/share/php/openmediavault/session.inc:157
> Stack trace:
> #0 /usr/share/php/openmediavault/session.inc(209): OMV\Session->validateTimeout()
> #1 /var/www/openmediavault/rrd.php(28): OMV\Session->validate()
> #2 {main}
> ```

But this would mean that you have configured the auto-logout feature, otherwise the code wouldn't exit, see https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/usr/share/php/openmediavault/session.inc#L134.

**Comment by evilbunny2008** [comment] 2022-03-22 10:56
I have logout set to disabled, same thing happened when it was set to 1 day, and it seems to only be interfaces, rather than graphs in general, I'm still trying to reproduce it in firefox.

**Comment by votdev** [comment] 2022-03-22 10:59
> I have logout set to disabled, same thing happened when it was set to 1 day, and it seems to only be interfaces, rather than graphs in general, I'm still trying to reproduce it in firefox.

In that case the only possible reason is that the configuration database is corrupted and the [catch block is executed](https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/usr/share/php/openmediavault/session.inc#L130). But this would trigger a logout after 5 minutes. I do not see any other reason. The code does not allow other expectations.

**Comment by evilbunny2008** [comment] 2022-03-22 11:03
> In that case the only possible reason is that the configuration database is corrupted and the [catch block is executed](https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/usr/share/php/openmediavault/session.inc#L130). But this would trigger a logout after 5 minutes. I do not see any other reason. The code does not allow other expectations.

If it happened on other screens of the webui I'd agree that something is up with my installation, but the fact it's only raring it's head on the network interfaces graph screen I'm stumped.

**Comment by evilbunny2008** [comment] 2022-03-22 11:04
The error just happened in firefox.

**Comment by evilbunny2008** [comment] 2022-03-22 11:07
> OK, last possible reason is `/etc/cron.d/php` which is deleting the PHP session data every hour at 9 and 39 minutes. But that didn't affect my testing yesterday as both of those timings were definitely affected.

Don't you set a cookie rather than a session cookie?

**Comment by votdev** [comment] 2022-03-22 11:11
> > OK, last possible reason is `/etc/cron.d/php` which is deleting the PHP session data every hour at 9 and 39 minutes. But that didn't affect my testing yesterday as both of those timings were definitely affected.
> 
> Don't you set a cookie rather than a session cookie?

PHP is storing the session information on the system and the browser is storing/transferring the ID of the session on every request.

**Comment by votdev** [comment] 2022-03-22 11:16
I can not confirm that there is a problem, so for me the issue has been solved. Please investigate on your own and provide a fix if you have found a bug.

**Comment by evilbunny2008** [comment] 2022-03-22 11:25
Try this, open the network interfaces graphs, then right click on one of the images, and then refresh the image, the problem seems to be with rrd.php

**Comment by evilbunny2008** [comment] 2022-03-22 11:50
I also found out rrd has a json output method:

https://sourceforge.net/projects/javascriptrrd/

**Comment by votdev** [comment] 2022-03-22 12:03
> I also found out rrd has a json output method:
> 
> [sourceforge.net/projects/javascriptrrd](https://sourceforge.net/projects/javascriptrrd/)

Maybe something for OMV7. If the community wants to have it earlier, then a community contribution is welcome. That is how open source software works. TBH, i do not have to do everything on my own.

**Comment by votdev** [comment] 2022-03-22 12:03
> Try this, open the network interfaces graphs, then right click on one of the images, and then refresh the image, the problem seems to be with rrd.php

I do not see a menu option to reload the image.

![Bildschirmfoto von 2022-03-22 12-34-58](https://user-images.githubusercontent.com/1897962/159477795-c3dd2912-016e-4cae-a6a2-7f9fa95bcc05.png)

**Comment by evilbunny2008** [comment] 2022-03-22 12:14
you have to open image in new tab and then refresh the image a few times till it logs you out.

**Comment by votdev** [comment] 2022-03-22 12:21
> you have to open image in new tab and then refresh the image a few times till it logs you out.

Nothing happens
![Peek 2022-03-22 13-20](https://user-images.githubusercontent.com/1897962/159480851-896c89d7-fd50-42f4-9e90-a552d34b4268.gif)

**Comment by evilbunny2008** [comment] 2022-03-22 12:32
it takes 10-15minutes to occur, doesn't seem to line up with the session cleanup times either.

**Comment by ryecoaaron** [comment] 2022-03-22 12:49
I've been trying to replicate this as well with no luck.  It has been 20 mins now.

**Comment by ryecoaaron** [comment] 2022-03-22 13:42
It finally logged me out but I really don't see why this would ever cause anyone an issue.  Why are you opening an image in a new tab and manually refreshing it? That was the only way I could hit this.

**Comment by evilbunny2008** [comment] 2022-03-23 01:26
I was only doing that because that's how I could reproduce the problem.
