### ISSUE TITLE
Bad drivers dont populate /sys file system with correct vendor and model information

### ISSUE THREAD

**Issue by johnjore** [openmediavault/openmediavault#783] opened 2020-08-14 12:20 UTC
### Description of issue/question
Bad drivers don't populate /sys file system with correct vendor and model information

### Steps to reproduce issue
```
cat /sys/block/sda/device/model
24AS

```
```
cat /sys/block/sda/device/vendor
ST310005

```
### Versions report
5.5.6-1

**Comment by johnjore** [comment] 2020-08-14 12:25
Example scripts for udev:

KERNEL=="sd*", ATTRS{idVendor}=="1058", ATTRS{idProduct}=="0a10", SUBSYSTEMS=="usb", PROGRAM="/usr/local/sbin/serial.sh %k", ENV{ID_SERIAL}="USB-%c", ENV{ID_SERIAL_SHORT}="%c"
KERNEL=="sd*", ATTRS{idVendor}=="1058", ATTRS{idProduct}=="0a10", SUBSYSTEMS=="usb", PROGRAM="/usr/local/sbin/model.sh %k", ENV{ID_MODEL}="%c"
KERNEL=="sd*", ATTRS{idVendor}=="1058", ATTRS{idProduct}=="0a10", SUBSYSTEMS=="usb", PROGRAM="/usr/local/sbin/vendor.sh %k", ENV{ID_VENDOR}="%c", ENV{ID_VENDOR_ENC}="%c"


Model:
```
#!/bin/bash
/sbin/hdparm -I /dev/$1 2> /dev/null | grep 'Model Number' | awk '{print $NF}
```

Vendor:
```
#!/bin/bash
smartctl -i /dev/$1 | grep -i "Model Family" | awk '{print $3}'
```

**Comment by votdev** [comment] 2020-08-14 12:47
The problem is the controller of your hardware.

I will close this issue because it is not the job of the OMV project to fix this. Please maintain it locally if you want to fix such issues.

**Closed by votdev** 2020-08-14 12:47 UTC

**Comment by votdev** [comment] 2020-08-14 12:55
OK, saw that #783 is needed to apply the changes locally. LGTM.

**Comment by johnjore** [comment] 2020-08-14 12:57
No, it think its more a a combination of disk and controller as my Hitachi disk is reflected correctly, but 3 of 3 Seagate disks are not.

Happy to maintain locally, but thought I would share what I have, along with PR #784, as I know others will have same issue, as I am using the ROCK PI SATA HAT on a RPI 4, https://wiki.radxa.com/News/2019/12/introduce-rockpi-sata-hat, and I suspect there will be a few others posting about the same here...

JJ
