### ISSUE TITLE
Insufficient rights clamdscan

### ISSUE THREAD

**Issue by MARCELJDSMIT** [openmediavault/openmediavault#512] opened 2019-11-20 11:51 UTC
### Description of issue/question
OMV5 on Debian Buster has the error "lstat() failed". There are not sufficient rights to scan de shared folder. See also #381

### Steps to reproduce issue
1. Out of the box installation OMV.
2. Add user and shared folder.
3. Add and activate Clamav plugin
4. Create scheduled job for shared folder and run the job.

### Versions report
OMV5
Debian10

### Research
Created clamdscan cron jobs are running without --fdpass option. 

### Additional findings
- Debain has known bug [[827909](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=827909)]. As stated in your [answer](https://forum.openmediavault.org/index.php/Thread/24012-OMV-Antivirus/) as workaround: restart clamav-freshclam to recreate/sync localsocket. 
- clamdscan option Detectbrokenexecutables is deprecated. Correct options are [here](https://blog.clamav.net/2018/12/clamav-01010-has-been-released.html).
- --multiscan as additional option for the clamdscan cronjob, its much faster but it takes also amounts of resource....
- I think it's not necessary to overrule user clamav with root in clamd.conf if --fdpass is used.

**Comment by votdev** [comment] 2019-11-20 17:59
Partly fixed with e3a318d4d7d3aff03ba0881142014b6d63cebc79

**Comment by votdev** [comment] 2019-11-20 18:11
> I think it's not necessary to overrule user clamav with root in clamd.conf if --fdpass is used.

I remember that i did some research on this a while ago and didn't implement it that way because of reasons i do not remember anymore.

**Closed by votdev** 2019-11-20 18:11 UTC
Labels: 5.x, bug

**Comment by szech** [comment] 2020-01-30 01:26
i think this issue should be re-opened, because i experienced the same issue as OP; even after giving clamav user + group permissions in ACL.


for the record, it seems to be caused by (lack of) apparmor permissions.
i created a local rule as described here in the [clamav forum](https://narkive.com/ETNfCHCj.7) and clamav now scans as expected.

would be great if omv/clamav setup could modify this config.

**Comment by votdev** [comment] 2020-01-30 08:09
@szech Which platform are you using? The ISO image delivered by OMV does not use Appamor.

To get it implemented right on systems that seem to use Appamor i think the best approach is to ship an Apparmor configuration, though OMV does not use it. @szech could you please share your config?

**Comment by szech** [comment] 2020-01-31 00:57
i installed omv on top of fresh debian 10 instead of using the omv image.
seems like apparmor is enabled as standard in those distributions

my config is to edit `/etc/apparmor.d/local/usr.sbin.clamd` and put
```
# add omv shared folders
/srv/** krw,
```

and edit the bottom of `/etc/apparmor.d/usr.sbin.clamd` to enable the local rule
```
  # Site-specific additions and overrides. See local/README for details.
   include <local/usr.sbin.clamd>
```

i attach the config files here as txt for your convenience.
i'm a linux newbie, so a second opinion on the local config is appreciated. 

[local_usr.sbin.clamd.txt](https://github.com/openmediavault/openmediavault/files/4137032/local_usr.sbin.clamd.txt)

[usr.sbin.clamd.txt](https://github.com/openmediavault/openmediavault/files/4137030/usr.sbin.clamd.txt)

**Comment by votdev** [comment] 2020-01-31 07:58
@szech Can you please execute the command `cat /proc/cmdline`and post the output.

**Comment by szech** [comment] 2020-01-31 19:08
```
$ cat /proc/cmdline
BOOT_IMAGE=/boot/vmlinuz-5.4.0-0.bpo.2-amd64 root=UUID=2d166f82-9a22-48cc-b03d-29c6f60a9bf8 ro quiet
```
