### ISSUE TITLE
Recyle bin for home directories

### ISSUE THREAD

**Issue by derIckeBrln** [openmediavault/openmediavault#1171] opened 2021-12-29 10:32 UTC
As discussed in https://forum.openmediavault.org/index.php?thread/13870-samba-recycle-bin-for-user-home-shares/ it would be really helpful to have the recycle-bin option for shares of home directories as well.

Currently it is possible to enable it with a combination of global settings and manual manipulation of the smb.configuration. But this way it is set for any share, it is not permanent and the auto cleanup does not work for those folders as well.

It would be good to have a configuration section for the home shares like it exists for the individual shares (but only with the options that make sense for home shares). So you can configure the recycle bin, show dot files, allow hosts, ... there (for all homes, not individually)

**Comment by votdev** [comment] 2021-12-29 10:54
Duplicate of https://github.com/openmediavault/openmediavault/issues/1165

**Closed by votdev** 2021-12-29 10:54 UTC
Labels: duplicate
