### ISSUE TITLE
[Request] Choose partition during installation

### ISSUE THREAD

**Issue by Ansem93** [openmediavault/openmediavault#263] opened 2019-01-11 15:56 UTC
Hi,
do you think it will be possible to let us choose the partition where we want to install OMV?
It's kinda annoying that we can't choose it in my opinion.

**Comment by ryecoaaron** [comment] 2019-01-11 16:33
OMV wipes the disk and creates the partitions.  There should only be one partition (other than swap) since the concept of OMV dictates that data is stored on other disks.  If you want a different partition layout, install Debian first.

**Comment by Ansem93** [comment] 2019-01-13 19:11
Why not add an ädvanced"option where we can choose partition and swap size? I read more than one topic about swap partition being too big or not wanted.

**Comment by votdev** [comment] 2019-01-13 21:47
If you want to keep it simple for non technical skilled users, the current approach is the best. Another thing is that Debian installer is greatly customizable, but not in this topic as i would like to have it.

**Comment by votdev** [comment] 2019-01-13 21:50
If you want to have more control over the installation process, then simply use the Debian Netinst ISO and manually install OMV as described in the forum. The OMV ISO does finally do nothing more.

**Comment by Ansem93** [comment] 2019-01-16 18:05
I get that you want to keep it simple, and I think you're right about it.
Maybe is because I'm used to Windows/Linux normal installer, but I find very confusing that it doesn't ask the partition and just format the entire disk. If someone is already at the point of using OMV and not buying a QNAP/Synology I hope he can at least choose the partition on his disk!

**Comment by ryecoaaron** [comment] 2019-01-16 18:09
If you can choose the partition, then they need to be able to create a partition.  That is the confusing part and there are many noobs who can't do that.

**Comment by votdev** [comment] 2019-01-16 18:15
Why do you want to choose a partition. OMV/Debian installer will use the chosen device and creates the partition for the OS and swap. I do not see any sense in choosing a single partition.

**Comment by Ansem93** [comment] 2019-01-16 18:36
most of SSDs right now are at least 60GB, so it's possible that someone want to have more than one partition on it (in my case I made a dedicate partition for docker+some other files).
Of course this doesn't apply for microSD of 16/32GB.

**Comment by Gremlingroj** [comment] 2019-05-04 08:00
Solution:
Change openmediavault_5.0.1-amd64.iso\session1\install\preseed.cfg, and resave image
Use # to comment this operations
### Partitioning
# This makes partman automatically partition without confirmation.
# d-i partman-auto/method string regular
# d-i partman-auto/init_automatically_partition select some_device
# d-i partman-auto/choose_recipe select atomic
# d-i partman/default_filesystem string ext4
# d-i partman/choose_partition select finish
# d-i partman/confirm_write_new_label boolean true
# d-i partman/confirm_nooverwrite boolean true
# d-i partman/confirm boolean true
# d-i partman-lvm/device_remove_lvm boolean true
# d-i partman-md/device_remove_md boolean true

**Comment by votdev** [comment] 2019-05-09 16:56
Auto selected partition must be confirmed now. Please give it a try with https://sourceforge.net/projects/openmediavault/files/5.0.1beta/. Will be included in the next OMV4 ISO.

**Closed by votdev** 2019-05-09 16:56 UTC

**Comment by lpalgarvio** [comment] 2023-02-21 18:12
OMV 6.0.24 ISO is still defaulting to try rewriting everything and if i choose NO on the typical debian partition menus it includes, it just asks again until the user says YES or shuts down the system. This is not reasonable. Why arent you unlocking custom partition as Debian ISO has by default?

**Comment by votdev** [comment] 2023-02-21 18:19
> OMV 6.0.24 ISO is still defaulting to try rewriting everything and if i choose NO on the typical debian partition menus it includes, it just asks again until the user says YES or shuts down the system. This is not reasonable. Why arent you unlocking custom partition as Debian ISO has by default?

This behaviour is by intention to simplify the installation for users that are not familiar to Linux. If you don’t like that behaviour, simply use the Debian Netinst ISO and install openmediavault manually. You have already the choice which way to go.

**Comment by lpalgarvio** [comment] 2023-02-21 19:02
i've understanded that, but what harm can come of unlocking advanced/custom partititioning, provided you write a disclaimer at the top on the screen about it, that you dont support nor recommend it?
because going the full debian way like im doing, just adds additional work that could be avoided (apt setup and all).
are you considering that some users have EFI/GPT systems and not BIOS/MBR?
or that some users dont want a swap?
are SSDs medium being considered, ie, discard?
does the installer accomodate for any of that?

**Comment by lpalgarvio** [comment] 2023-02-21 19:09
from the attempts i did with OMV ISO it looks like its a OK fit for a VM under Proxmox for example, where its unlikely you will need an EFI bootable VM (you're not passthrouging video for example).
would be ok too for a simple HDD install for old MBR/BIOS hardware.

but users will be missing out or having issues if they use modern hardware, ie, EFI/GPT, SSDs.
SSDs is the least of the issues, because you can tune fstab to enable discard at least, but EFI is a bigger issue.

**Comment by votdev** [comment] 2023-02-21 19:15
That’s all right. If you do not like the current situation feel free to contribute a build script that supports all the missing features. I, the project and all its users will be happy to benefit from your work. Otherwise there is still to opportunity to use the Debian ISO.

**Comment by geez0r** [comment] 2023-09-03 13:45
For God's sake just leave the option there for people to manually amend the partitioning when your script gets it wrong... 
Removing the ability to fix things for the sake of """the wider audience""" is not making it better nor easier to use in any way.

**Comment by votdev** [comment] 2023-09-03 14:16
> For God's sake just leave the option there for people to manually amend the partitioning when your script gets it wrong... Removing the ability to fix things for the sake of """the wider audience""" is not making it better nor easier to use in any way.

You can still use Debians Netinst ISO if you need more control over the installation. Afterwards [install OMV as documented](https://docs.openmediavault.org/en/stable/installation/on_debian.html).

**Comment by acordtag** [comment] 2024-05-08 13:29
Perhaps the installation could detect the already partitioned drive and let us choose? - Nowadays it hard to get SSDs smaller that 120Gb and partition become a must. Also, this could allow us to restore/reintall OS on the specific partition if something goes wrong in the future.

**Comment by votdev** [comment] 2024-05-08 13:39
> Perhaps the installation could detect the already existing partitioned drive and let us choose? - Nowadays it hard to get SSDs smaller that 120Gb and partitions become a must. Also, this could allow us to restore/reinstall OS on the specific partition if something goes wrong in the future.

Nowadays 120Gb SSD is about 12 Euro. At this price, it makes absolutely no difference if 100Gb remain unused.

OMV does not support hosting the OS and user data on the same disk. If the OS drive crashes, the user data is gone, too.

For the data storage, it is not necessary to have partitions because it absolutely does not make sense to use them here. Nowadays the disk space can't be big enough, so why supporting partitions.
