### ISSUE TITLE
omv-release-upgrade shows "W: --force-yes is deprecated" & can't find it in repository

### ISSUE THREAD

**Issue by mi-hol** [openmediavault/openmediavault#1409] opened 2022-10-20 10:20 UTC
I'd love to fix "W: --force-yes is deprecated" but unfortunate can't find it in repository

**Describe the bug**

A deprecated option is used in command:
apt-get --yes --force-yes --fix-missing --auto-remove --allow-unauthenticated \
  --show-upgraded --option Dpkg::Options::="--force-confdef" \
  --option DPkg::Options::="--force-confold" --no-install-recommends \
  dist-upgrade

**To Reproduce**

1. execute omv-release-upgrade
2.  See warning

**Comment by ryecoaaron** [comment] 2022-10-20 10:59
Deprecated means it will be removed in Debian 12.  This is still listed in the man page and serving a purpose.  So, it is not a bug.  Without it, held packages would not be upgraded and could cause more problems than the warning "causes".  That said, it could probably be replaced with the --allow-downgrades , --allow-remove-essential , --allow-change-held-packages flags to avoid this dreadful warning that you should one time.

**Comment by votdev** [comment] 2022-10-20 11:12
This code is only executed on the migration of Debian 10 to 11 where it is deprecated (incl. a warning), but fully functional. Because of that there is no need to fix it.

For the migration of OMV6 (Debian 11) -> OMV7 (Debian 12) the code will be adapted. Currently the code does not exist in the repository, so it can not be fixed right now.

I'm closing this because of the reasons above and the fact that there is no need for a reminder at the time the migration to Debian 11 becomes reality.

**Closed by votdev** 2022-10-20 11:12 UTC
Labels: bug

**Comment by mi-hol** [comment] 2022-10-20 11:22
> Currently the code does not exist in the repository, so it can not be fixed right now.

this makes searching the code base much more difficult. I.e. searches in github have no result.
Is it planned to add scripts to github?

**Comment by ryecoaaron** [comment] 2022-10-20 11:33
The script is added when there is something to upgrade to which can't happen until a suitable version of OMV 7 exists.  Until then, it should not exist.  All previous versions of OMV have followed this process.

**Comment by votdev** [comment] 2022-10-20 11:36
> > Currently the code does not exist in the repository, so it can not be fixed right now.
> 
> this makes searching the code base much more difficult. I.e. searches in github have no result or only partially correct result. Is it planned to add scripts to github?

Since the early age of OMV the `omv-release-upgrade` command was only available at that time a migration was possible. This will happen in future when there is a alpha/beta of OMV7 available, not earlier because it does not make any sense if there is nothing to migrate.

**Comment by votdev** [comment] 2022-10-20 11:40
@mi-hol Please remember that I/we have been doing this for over a decade now and should know how to do some things. There is no need to keep digging. That may have been necessary in your profession, but not here.

**Comment by votdev** [comment] 2022-10-20 11:41
> what about 'omv-upgrade' (which is actively used)? github can't find it either

Please check the changelog.

**Comment by votdev** [comment] 2022-10-20 11:48
> what about 'omv-upgrade' (which is actively used)? github can't find it either

`omv-upgrade` was the name of the tool for OMV4. 

The changelog does not mention the adding of the `omv-release-upgrade` tool because not all users should know about it at that time. It was only for interesting for developers. The first public announcement was https://www.openmediavault.org/?p=3010.

**Comment by ryecoaaron** [comment] 2022-10-20 12:07
Many users don't read any OMV docs and rely on other web sites or videos we can't control.

> Also I had a case of omv-release-upgrade reporting "running a desktop environment" when I was sure to have used a server (aka lite) image for installation.

It would only report that if it found a package.  This is [very exact](https://github.com/openmediavault/openmediavault/blob/5.x/deb/openmediavault/usr/sbin/omv-release-upgrade#L50) and the starting image does not matter if you installed the package at a later point.

**Comment by ryecoaaron** [comment] 2022-10-20 14:35
Did you notice the 'q' flag in the grep statement?  That means quiet which is why nothing would ever be displayed.

I can't explain what displayed the message.  If this was truly a problem, more people would be seeing it.  This is offtopic for this issue though.

**Comment by mi-hol** [comment] 2022-10-20 15:55
> Did you notice the 'q' flag in the grep statement?

good hint, actually I didn't notice, but 2. would have corrected this oversight
