### ISSUE TITLE
Disks with identical attributes to others not being enumerated

### ISSUE THREAD

**Issue by Catdaemon** [openmediavault/openmediavault#665] opened 2020-04-04 02:23 UTC
### Description of issue/question
I have a drive array consisting of two identical 4-bay USB3 JBOD enclosures. These are running off a raspberry pi 4. I have successfully set this up with 7 drives. Upon adding the 8th drive, all of the drives in that enclosure disappear from the Disks section of OMV. The drives in the other enclosure are still there. Everything else works fine and they are all detected by the operating system. All of the filesystems on the disks show in the File Systems area, but I am obviously unable to create a filesystem on the new drive via the UI.  If I then remove the added drive they all show in the Disks section again.

I haven't read the code, but I have a feeling this may be caused by the cheap-ish JBOD enclosures I'm using, they're JMicron controllers with identical IDs, serial numbers etc. which is annoying and I assume is the problem. I thought this might be similar to #639 maybe except my filesystems work fine, and all was good until the last disk was added. Here they are via `ls -l /dev/disk/by-id/ | awk '{print $9,$10,$11}'`:
```
usb-JMicron_Generic_DISK00_0123456789ABCDEF-0:0 -> ../../sde
usb-JMicron_Generic_DISK00_0123456789ABCDEF-0:0-part1 -> ../../sde1
usb-JMicron_Generic_DISK01_0123456789ABCDEF-0:1 -> ../../sdf
usb-JMicron_Generic_DISK01_0123456789ABCDEF-0:1-part1 -> ../../sdf1
usb-JMicron_Generic_DISK02_0123456789ABCDEF-0:2 -> ../../sdg
usb-JMicron_Generic_DISK02_0123456789ABCDEF-0:2-part1 -> ../../sdg1
usb-JMicron_Generic_DISK03_0123456789ABCDEF-0:3 -> ../../sdh
usb-JMicron_Generic_DISK03_0123456789ABCDEF-0:3-part1 -> ../../sdh1
```
I added an entry to my udev rules to stop these links being overwritten by the duplicates and see if this would fix it:
```
# JMicron drive hack
KERNEL=="sd*", ENV{ID_VENDOR}=="JMicron", PROGRAM="/root/get_disk_serial.sh %k", SYMLINK+="disk/by-id/usb-enc-%c"
```

This makes the drives appear as follows:
```
usb-enc-GTA000PAG91YEA -> ../../sdb1
usb-enc-GTA000PAGAEBHA -> ../../sdh1
usb-enc-GTA000PAGAJ9JA -> ../../sdg1
usb-enc-GTA000PAGAKY1A -> ../../sda1
usb-enc-S13PJ90S124059 -> ../../sdf1
usb-enc-WD-WCC3F5843267 -> ../../sdc1
usb-enc-WD-WCC3F5886569 -> ../../sdd1
usb-enc-WD-WMC0S0714396 -> ../../sde1
```

However they still aren't visible in the UI. I know my setup is not great but I'd really like to get it working and I'm at a bit of a loss. Any help is appreciated :)

### Versions report
5.3.9-1 (Usul)

**Comment by votdev** [comment] 2020-04-06 05:56
Please post the output of `$ omv-rpc DiskMgmt enumerateDevices | jq` and `omv-rpc -u admin 'FileSystemMgmt' 'getCandidates' | jq`.

**Comment by Catdaemon** [comment] 2020-04-06 13:02
Hi,

`omv-rpc DiskMgmt enumerateDevices | jq`

```
[
  {
    "devicename": "mmcblk0",
    "canonicaldevicefile": "/dev/mmcblk0",
    "devicefile": "/dev/disk/by-id/mmc-NCard_0x00000c83",
    "devicelinks": [
      "/dev/disk/by-id/mmc-NCard_0x00000c83",
      "/dev/disk/by-path/platform-fe340000.emmc2"
    ],
    "model": "",
    "size": "8068792320",
    "description": "n/a [/dev/mmcblk0, 7.51 GiB]",
    "vendor": "",
    "serialnumber": "",
    "israid": false,
    "isroot": true
  },
  {
    "devicename": "sda",
    "canonicaldevicefile": "/dev/sda",
    "devicefile": "/dev/disk/by-id/usb-JMicron_Generic_DISK00_0123456789ABCDEF-0:0",
    "devicelinks": [
      "/dev/disk/by-id/usb-JMicron_Generic_DISK00_0123456789ABCDEF-0:0",
      "/dev/disk/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1:1.0-scsi-0:0:0:0"
    ],
    "model": "Generic DISK00",
    "size": "1000204886016",
    "description": "Generic DISK00 [/dev/sda, 931.51 GiB]",
    "vendor": "JMicron",
    "serialnumber": "0123456789ABCDEF",
    "israid": false,
    "isroot": false
  },
  {
    "devicename": "sdb",
    "canonicaldevicefile": "/dev/sdb",
    "devicefile": "/dev/disk/by-id/usb-JMicron_Generic_DISK01_0123456789ABCDEF-0:1",
    "devicelinks": [
      "/dev/disk/by-id/usb-JMicron_Generic_DISK01_0123456789ABCDEF-0:1",
      "/dev/disk/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1:1.0-scsi-0:0:0:1"
    ],
    "model": "Generic DISK01",
    "size": "1000204886016",
    "description": "Generic DISK01 [/dev/sdb, 931.51 GiB]",
    "vendor": "JMicron",
    "serialnumber": "0123456789ABCDEF",
    "israid": false,
    "isroot": false
  },
  {
    "devicename": "sdc",
    "canonicaldevicefile": "/dev/sdc",
    "devicefile": "/dev/disk/by-id/usb-JMicron_Generic_DISK02_0123456789ABCDEF-0:2",
    "devicelinks": [
      "/dev/disk/by-id/usb-JMicron_Generic_DISK02_0123456789ABCDEF-0:2",
      "/dev/disk/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1:1.0-scsi-0:0:0:2"
    ],
    "model": "Generic DISK02",
    "size": "1000204886016",
    "description": "Generic DISK02 [/dev/sdc, 931.51 GiB]",
    "vendor": "JMicron",
    "serialnumber": "0123456789ABCDEF",
    "israid": false,
    "isroot": false
  },
  {
    "devicename": "sdd",
    "canonicaldevicefile": "/dev/sdd",
    "devicefile": "/dev/disk/by-id/usb-JMicron_Generic_DISK03_0123456789ABCDEF-0:3",
    "devicelinks": [
      "/dev/disk/by-id/usb-JMicron_Generic_DISK03_0123456789ABCDEF-0:3",
      "/dev/disk/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1:1.0-scsi-0:0:0:3"
    ],
    "model": "Generic DISK03",
    "size": "1000204886016",
    "description": "Generic DISK03 [/dev/sdd, 931.51 GiB]",
    "vendor": "JMicron",
    "serialnumber": "0123456789ABCDEF",
    "israid": false,
    "isroot": false
  },
  {
    "devicename": "sde",
    "canonicaldevicefile": "/dev/sde",
    "devicefile": "/dev/disk/by-id/usb-JMicron_Generic_DISK00_0123456789ABCDEF-0:0",
    "devicelinks": [
      "/dev/disk/by-id/usb-JMicron_Generic_DISK00_0123456789ABCDEF-0:0",
      "/dev/disk/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:2:1.0-scsi-0:0:0:0"
    ],
    "model": "Generic DISK00",
    "size": "1000204886016",
    "description": "Generic DISK00 [/dev/sde, 931.51 GiB]",
    "vendor": "JMicron",
    "serialnumber": "0123456789ABCDEF",
    "israid": false,
    "isroot": false
  },
  {
    "devicename": "sdf",
    "canonicaldevicefile": "/dev/sdf",
    "devicefile": "/dev/disk/by-id/usb-JMicron_Generic_DISK01_0123456789ABCDEF-0:1",
    "devicelinks": [
      "/dev/disk/by-id/usb-JMicron_Generic_DISK01_0123456789ABCDEF-0:1",
      "/dev/disk/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:2:1.0-scsi-0:0:0:1"
    ],
    "model": "Generic DISK01",
    "size": "1000204886016",
    "description": "Generic DISK01 [/dev/sdf, 931.51 GiB]",
    "vendor": "JMicron",
    "serialnumber": "0123456789ABCDEF",
    "israid": false,
    "isroot": false
  },
  {
    "devicename": "sdg",
    "canonicaldevicefile": "/dev/sdg",
    "devicefile": "/dev/disk/by-id/usb-JMicron_Generic_DISK02_0123456789ABCDEF-0:2",
    "devicelinks": [
      "/dev/disk/by-id/usb-JMicron_Generic_DISK02_0123456789ABCDEF-0:2",
      "/dev/disk/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:2:1.0-scsi-0:0:0:2"
    ],
    "model": "Generic DISK02",
    "size": "1000204886016",
    "description": "Generic DISK02 [/dev/sdg, 931.51 GiB]",
    "vendor": "JMicron",
    "serialnumber": "0123456789ABCDEF",
    "israid": false,
    "isroot": false
  },
  {
    "devicename": "sdh",
    "canonicaldevicefile": "/dev/sdh",
    "devicefile": "/dev/disk/by-id/usb-JMicron_Generic_DISK03_0123456789ABCDEF-0:3",
    "devicelinks": [
      "/dev/disk/by-id/usb-JMicron_Generic_DISK03_0123456789ABCDEF-0:3",
      "/dev/disk/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:2:1.0-scsi-0:0:0:3"
    ],
    "model": "Generic DISK03",
    "size": "1000204886016",
    "description": "Generic DISK03 [/dev/sdh, 931.51 GiB]",
    "vendor": "JMicron",
    "serialnumber": "0123456789ABCDEF",
    "israid": false,
    "isroot": false
  }
]
```

`omv-rpc -u admin 'FileSystemMgmt' 'getCandidates' | jq`

```
[]
```

**Comment by votdev** [comment] 2020-04-06 13:23
The create filesystem dialog does not show you devices which already contain a filesystem or part of a LVM or MDRAID. To confirm that all of your devices already occupied please post the output of `blkid`. You can format/clean a device in the `Pyhsical devices` page.

**Comment by Catdaemon** [comment] 2020-04-06 13:30
I'm aware of that - I ended up creating the filesystem on my last disk manually as it wouldn't show up in OMV. The issue isn't necessarily that I can't create the filesystem, it's that something is wrong and I'm not sure what other issues it might cause - I also can't set up SMART monitoring with the UI for example.

This is correct:
![filesystems](https://user-images.githubusercontent.com/173231/78563344-b898fd80-7812-11ea-8e6b-7b6d77888abd.png)
This is missing 4 drives:
![disks](https://user-images.githubusercontent.com/173231/78563346-ba62c100-7812-11ea-9d30-34757d7c0f60.png)

**Comment by votdev** [comment] 2020-04-06 13:34
OMV does nothing magic when detecting the disks. It uses UDEV and sysfs to do that. If there are incorrect data, then OMV can not use and display them.
You're not the first user that reported the JMicron issue with duplicate ID's. I think the best is to replace the enclosure.

**Comment by votdev** [comment] 2020-04-06 13:35
And please tell me which device is missing. I've not the time to cross check every console output and screenshot.

**Comment by Catdaemon** [comment] 2020-04-06 13:38
/dev/sd[a-c] are missing, /dev/sd[e-h] are present.

I think replacing the enclosures is ideal too, but it seems a waste of what appears to be a working and performant (and cheap!) enclosure. Linux itself doesn't seem to have a problem addressing and using the drives, so there must be a way to get this working. Could you help me by illustrating how exactly OMV is enumerating the drives so I can perhaps develop a workaround for that pulls the "real" IDs off the drives?

**Comment by votdev** [comment] 2020-04-06 13:51
The device enumeration starts here: https://github.com/openmediavault/openmediavault/blob/5.x/deb/openmediavault/usr/share/php/openmediavault/system/storage/storagedevice.inc#L239

In https://github.com/openmediavault/openmediavault/tree/5.x/deb/openmediavault/usr/share/php/openmediavault/system/storage/backend you will find a specialized implementation that handle various device types. Have a look into https://github.com/openmediavault/openmediavault/blob/5.x/deb/openmediavault/usr/share/php/openmediavault/system/storage/backend/sd.inc for `/dev/sdX` devices.

The `Physical disks`page will call the following RPC to get a list of devices: https://github.com/openmediavault/openmediavault/blob/5.x/deb/openmediavault/usr/share/openmediavault/engined/rpc/diskmgmt.inc#L57

**Comment by votdev** [comment] 2020-04-06 13:58
> Could you help me by illustrating how exactly OMV is enumerating the drives so I can perhaps develop a workaround for that pulls the "real" IDs off the drives?

I don't think that will work because OMV is fully generic in this case.

**Comment by votdev** [comment] 2020-04-06 14:08
The problem is that the disks have duplicate device files:
```
    "devicename": "sda",
    "canonicaldevicefile": "/dev/sda",
    "devicefile": "/dev/disk/by-id/usb-JMicron_Generic_DISK00_0123456789ABCDEF-0:0",
    "devicelinks": [
      "/dev/disk/by-id/usb-JMicron_Generic_DISK00_0123456789ABCDEF-0:0",
      "/dev/disk/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1:1.0-scsi-0:0:0:0"
    ],
```
and
```
    "devicename": "sde",
    "canonicaldevicefile": "/dev/sde",
    "devicefile": "/dev/disk/by-id/usb-JMicron_Generic_DISK00_0123456789ABCDEF-0:0",
    "devicelinks": [
      "/dev/disk/by-id/usb-JMicron_Generic_DISK00_0123456789ABCDEF-0:0",
      "/dev/disk/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:2:1.0-scsi-0:0:0:0"
    ],
```
The UI uses the `devicefile`attribute as unique identifier and filters duplicate entries. This can't be fixed because a devicefile is ALWAYS unique.

**Comment by votdev** [comment] 2020-04-06 14:18
I close this issue because this is an hardware problem. You may ask 'why not using a nother devicefile like the `/dev/disk/by-path`'? This is because OMV tries to use devicefiles the following order: `/dev/disk/by-id`, `/dev/disk/by-path` and canonical paths like `/dev/xxx`. Due the fact that all is generical, there is no way to say uh, this devicefile seems to be duplicate in the system, so lets choose another once. There is never a need because it is a general assumption that a devicefile is unique across the system. If the hardware reports incorrect values, this will break the whole system.

**Closed by votdev** 2020-04-06 14:18 UTC
Labels: 5.x

**Comment by Catdaemon** [comment] 2020-04-06 14:20
I've had a look and the RPC is actually returning all of the drives, so it does indeed appear to be the UI that's filtering them. That's promising and makes sense, but I wonder why my udev edit didn't solve the problem in that case. I may have not fully refreshed everything! I will continue to mess around with that as it looks like the way to go.
It seems to me that the UI could be changed to use the canonicaldevicefile entry instead, or a combination of multiple fields perhaps? I understand that you do not want to fix this just for my weird hardware and I appreciate your help, but something to think about for the future as others may not have the necessary skills to DIY this like I do.

**Comment by votdev** [comment] 2020-04-06 14:22
> It seems to me that the UI could be changed to use the canonicaldevicefile entry instead, or a combination of multiple fields perhaps?

This will only relocate the problem into another layer and will make problems somewhere else.

**Comment by Catdaemon** [comment] 2020-04-06 14:24
You are probably right, I don't have enough experience with this to say otherwise. I will persevere with this udev rule as it seems to be the cleanest way, and if I can get it to work maybe it can be put in a FAQ somewhere so you can point other people to it in the future :)

**Comment by votdev** [comment] 2020-04-06 14:27
If you apply the udev rule (without rebooting the system) you should take care to reload udev with `udevadm control --reload-rules`. If `udevadmin` will output you the modified devicefile paths then OMV will also see them because it uses `udevadm` to collect the data.

**Comment by votdev** [comment] 2020-04-06 14:51
> maybe it can be put in a FAQ somewhere so you can point other people to it in the future :)

Please feel free to add a hint to the [Troubleshooting section](https://openmediavault.readthedocs.io/en/latest/troubleshooting.html). Simply create a PR against `master` [here](https://github.com/openmediavault/openmediavault-docs).

**Comment by Catdaemon** [comment] 2020-04-06 16:33
Thank you for all of your help - I have got it working now!
![drives](https://user-images.githubusercontent.com/173231/78582036-9dd38280-782c-11ea-9c2b-dfd9538de55f.png)
It's quite an easy fix so I have opened a PR with the instructions as suggested. I can't seem to get the manufacturer and model to pull through even though they show up in `udevadm` but it's really not worth looking into that further imo.

**Comment by MarcS1975** [comment] 2020-08-13 18:46
Hi. I had a similar problem with JMicron controlers and slmost got it working. The disks show up in the OMV GUI under disk and under SMART devices, but not inside the Encryption Plugin.
Can anyone help? How does the Encryption Plugin read the available disks?
Any pointers much appreciated.
