### ISSUE TITLE
I can't login webui, it's shown "502 bad gateway"

### ISSUE THREAD

**Issue by bhj128128** [openmediavault/openmediavault#1309] opened 2022-05-24 08:11 UTC
**Please only open an issue here, when advised by a moderator in openmediavault forum.**

Requests for support and questions shall be addressed first to openmediavault forum: https://forum.openmediavault.org/

**Note:** Issues for non-core plugins are to be raised in the corresponding https://github.com/OpenMediaVault-Plugin-Developers repository

**Describe the bug**

I can't login webui, it's shown "502 bad gateway". if I run "omv-firstaid",select "2 configure web control panel"，it will show “ERROR: [Errno 11] Resource temporarily unavailable”

**Comment by votdev** [comment] 2022-05-24 10:19
I'm sorry, but i close this issue because it does not provide any useful information to identify the issue or give any hint.
The help message when creating a new bug report is explicitly requesting information from the user. I am really tired of answering or helping when those information is not provided.

**Closed by votdev** 2022-05-24 10:19 UTC
Labels: bug

**Comment by votdev** [comment] 2022-05-24 10:33
If you want to get this issue processed, provide the information how to reproduce the issue. Which platform are you using, what plugins have been installed? What config changes did you have done?

To get a broader audience, ask the question in the forum.
