### ISSUE TITLE
Navigation menu sidebar not scrollable on Firefox

### ISSUE THREAD

**Issue by alvinhochun** [openmediavault/openmediavault#1869] opened 2024-12-12 08:52 UTC
**Describe the bug**

When the viewport height is small and enough navigation menu subitems have been expanded, no scrollbar appears on the sidebar and it is not scrollable with mouse wheel either.

**To Reproduce**

1. Go to the OMV dashboard
2. Expand 'Diagnostics' -> 'Performance Statistics'
3. Resize browser viewport to be small enough that the menu item overflows the bottom
4. Try to scroll down in the sidebar

**Expected behavior**

The scrollbar should be visible on the sidebar and scrolling down should be possible.

**Screenshots**

Firefox:
![Firefox](https://github.com/user-attachments/assets/a00ff8f6-5106-4ea3-9ee9-6c179d801827)

Chrome (working):
![Chrome](https://github.com/user-attachments/assets/23179d3f-40c1-4a1f-8dcb-909b298bfa7d)

**openmediavault Server (please complete the following information):**

- OS version: `Linux localhost 6.1.0-28-marvell #1 Debian 6.1.119-1 (2024-11-22) armv5tel GNU/Linux`
- openmediavault version: 7.4.15-2

**Client (please complete the following information):**

- Device: PC
- OS: Windows 10
- Browser: Firefox 
- Version: 134.0b9

**Comment by votdev** [comment] 2024-12-12 09:51
Can not reproduce that with the latest Firefox 133.0.3 on Ubuntu:

[Bildschirmaufzeichnung vom 2024-12-12 10-46-07.webm](https://github.com/user-attachments/assets/b5a8a379-26dc-43c1-ab3a-daa9ce50ecdf)

I'm wondering why your Chrome browser is showing a scroll bar for the sub menus. This is incorrect. It should look like this:

[Bildschirmaufzeichnung vom 2024-12-12 10-47-54.webm](https://github.com/user-attachments/assets/cefa3ad3-f2c3-4752-b1d6-e62580a8c8b1)

**Comment by alvinhochun** [comment] 2024-12-12 10:13
> Can not reproduce that with the latest Firefox 133.0.3 on Ubuntu:

Hm, so this seems to be a new regression of Firefox 134. Mozregression pointed at https://phabricator.services.mozilla.com/D151310, I haven't looked at it in detail yet.


> I'm wondering why your Chrome browser is showing a scroll bar for the sub menus. This is incorrect. It should look like this:

It's fine, the scrollbar does cover the entire sidebar, it's just a bit too short.

**Comment by alvinhochun** [comment] 2024-12-12 10:48
Good news, it seems to be fixed on Firefox 135 (dev) by https://phabricator.services.mozilla.com/D231087 which resolved https://bugzilla.mozilla.org/show_bug.cgi?id=1931490

Maybe bad news, there is a chance the fix won't be backported to Firefox 134 (beta). I cannot make a comment there since they disallow comments on closed issues.

**Comment by votdev** [comment] 2024-12-12 10:53
> Good news, it seems to be fixed on Firefox 135 (dev) by [phabricator.services.mozilla.com/D231087](https://phabricator.services.mozilla.com/D231087) which resolved [bugzilla.mozilla.org/show_bug.cgi?id=1931490](https://bugzilla.mozilla.org/show_bug.cgi?id=1931490)

That is good news.

> Maybe bad news, there is a chance the fix won't be backported to Firefox 134 (beta). I cannot make a comment there since they disallow comments on closed issues.

This is out of control of OMV and users have to live with it until Firefox is fixing the issue.

**Comment by votdev** [comment] 2024-12-12 10:53
Closing this because it looks like an upstream issue with Firefox.

**Comment by votdev** [comment] 2024-12-12 11:49
Closing this because it looks like an upstream issue with Firefox.

**Closed by votdev** 2024-12-12 11:49 UTC
Labels: wontfix, upstream issue, 7.x

**Comment by alvinhochun** [comment] 2024-12-17 11:29
Just an update, the fix has landed for Firefox 134 RC. If nothing goes wrong this means stable release of Firefox will not be affected.
